### ISSUE TITLE
Allow injecting a CiJ library

### ISSUE THREAD

**Issue by nervetattoo** [elrumordelaluz/reactour#100]
As a lot of the CSS-in-JS libraries offer the same API, `reactour` is in fact entirely compatible with for example [emotion](https://emotion.sh), which we happen to use. Now I could get it to use emotion by using a build-time alias to replace `styled-components` but 
1. That is a hack
2. peerDependencies will make it fail

My first thought of a solution that will open up Reactour to different stacks is to make the CiJ library injectable, with perhaps even a fallback to simple `style` prop defaults.

A simple prop could be used for dead simple app global configuration:

```js
import Reactour from 'reactour'
import styled from 'my-cij'

Reactour.styled = styled
```

It would also require the removal of the peerDependency and ideally adding of the API-compliant CiJ libraries as `optionalDependencies`

One caveat is that this would effectively block anything more involved, like using keyframes (different export in emotion than styled-components), which Reactour currently isn't doing in the final build.

I wanted to get more input on this before slinging up a PR for it.

**Comment by elrumordelaluz** [comment]
Sound absolutely valid and could be pretty cool to inject the _CSS-in-JS_ lib the end user want. 
A couple of months ago I was thinking in switching into [styled-jsx](https://github.com/zeit/styled-jsx) but the `v4` of sc comes with lots of improvements.

Could be awesome to have a list of _injectable_ libraries, and why not [some tests](https://github.com/elrumordelaluz/reactour/issues/5) 😁
