### ISSUE TITLE
Big positioning jump when bottom of viewport hits the tour

### ISSUE THREAD

**Issue by nelsonwong1012** [elrumordelaluz/reactour#101]
I'm encounter an issue where if the viewport is small enough (or the tour is large and low enough), the tour is positioned way higher than it should be and there is a big jump when the bottom of the viewport hits the tour while resizing the window. I feel that the jump should at least be gradual. For my purposes, I would love an option where the modal would be positioned relative to the target element no matter what. I'm customizing my tour to have an arrow that points to the target and I don't want that to move.

You can see what I'm talking about at: https://codesandbox.io/s/l9zvv1ox4q

Here's what it looks like when there is enough space under the tour:
![screen shot 2019-01-16 at 5 18 43 pm](https://user-images.githubusercontent.com/4106256/51284928-dc281c00-19b2-11e9-8b90-48dd859f074d.png)

And here is the big positioning jump that happens when you resize the window so it hits the bottom of the tour:
![screen shot 2019-01-16 at 5 18 53 pm](https://user-images.githubusercontent.com/4106256/51284947-eea25580-19b2-11e9-8026-21ca6a06f1a0.png)

**Comment by elrumordelaluz** [comment]
Hi @nelsonwong1012, thanks for report this _Issue_.

If I understand well, you see this as an issue when trying to implement the arrow that point to the _target_, but instead internally is a _feature_ to guarantee the visibility of the _Helper_ also afrer viewport size changes. 

Comes in mind two possibilities, one if the yet [requested](https://github.com/elrumordelaluz/reactour/issues/98) (by you, right? 🎉 ) implementation of the native arrow so respect calculations an repositioning automatically. An alternative is to add a `prop` to pass to avoid extra calculations, something like `fixedPosition` or something.
Personally I prefer the first one.

Thanks again for open to new ideas/features.

**Comment by nelsonwong1012** [comment]
@elrumordelaluz Thanks for the quick response. Would you say this is working as designed? Regardless of the arrow, I would have expected the _Helper_ to reposition gradually, perhaps as fast as the user is reducing the height of the window, rather than simply jump up abruptly. But that's just my expectation, of course.

A native pointer solution that will would continue pointing at the target even if the _Helper_ repositioned would certainly alleviate the issue. Though, I wouldn't mind seeing the `fixedPosition` solution as well!
