### ISSUE TITLE
Fix position of popovers

### ISSUE THREAD

**Issue by gdsrosa** [elrumordelaluz/reactour#105]
I have a question, can I set a fix position for every popover of Tour?
Eg: Every single time I start the Tour has to be on Top, always. Can I do that?

**Comment by elrumordelaluz** [comment]
Hi @gdsrosa 
Seems something related on what [talking](https://github.com/elrumordelaluz/reactour/issues/101#issuecomment-455094610) in #101 
Just to be sure, what you mean is `top` position relative to the _highlighted_ element, right?

**Comment by gdsrosa** [comment]
Kind of,  I have a Tour that is set do `bottom` but the `viewport` is too short for the popover so the position will be "automatically" set to  `top`

**Comment by gdsrosa** [comment]
This issue can be closed, I solved with `inViewThreshold` prop.
