### ISSUE TITLE
Reactour as higher order component

### ISSUE THREAD

**Issue by developdeez** [elrumordelaluz/reactour#107]
Can this be used as a hgiher order component?
I notice it only need state to open and close but is there another way? 
Ideally I'd like to send the tour config to the HOC and start the tour automatically if it hasn't been seen by the user

**Comment by elrumordelaluz** [comment]
Didn't work for you the [update](https://github.com/elrumordelaluz/reactour#update) prop? In case, I am curious why? In case you didn't try, this `prop` lets you force a render when passing a different value, i.e `location.pathname` in case you change page. [Here](https://codesandbox.io/s/myry48155p) is an example where the `steps` changes base in the `location`.

**Comment by developdeez** [comment]
Oh no that wasn't the problem. It seems that your can't go far down the component tree. I had it at the same level as my routes. And was setting the selectors within those pages. It's fine.
