### ISSUE TITLE
chances to disable helper transition ?

### ISSUE THREAD

**Issue by rachmadideni** [elrumordelaluz/reactour#108]
hi thanks for this great library. is there any chances to disable helper transition? what i would like to do is when each step is entered. my custom helper will stick based on highlight position.

**Comment by rachmadideni** [comment]
wow Thanks @elrumordelaluz for your kind efforts.

**Comment by elrumordelaluz** [comment]
Thanks @rachmadideni, happy that `reactour` is useful for you!
