### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by jovstern** [elrumordelaluz/reactour#11]
Hi, 
i just discover your library and it's Awesome.
One thing that is missing is the option to change steps from other components, from outside the content (goto).
A lot of the onboarding libraries today suggest that option.
Tnx.

**Comment by elrumordelaluz** [comment]
hi @jovstern,
Sounds interesting! Could you please expand your idea with an hypothetic _use-case_.
I want to understand well what you mean with
> …to change steps from other components, from outside the content (goto).

Thanks,

**Comment by jovstern** [comment]
Lets say the app opens with the first time onboarding widget, the widget light up or point on a certain button that you want from the user to click on, when he does it you go to the next level in the tour screens and in the same time the app render by the action that the user just did.
The tour screens continuing to progress by the actions of the user and not necessary by clicking on the arrows of the tour-widget.
![tour-steps](https://user-images.githubusercontent.com/10359237/29818184-d195d7fa-8cc3-11e7-9e11-a0837476ad2e.jpg)

**Comment by elrumordelaluz** [comment]
Thank for the graphic explanation, absolutely clear!
At the moment I am doing something like what you are looking for using the `update` prop (in my case, when the `location.pathname` changes) and in some cases, updating/changing the `steps`.

Don't know if this solution could helps you. 
Anyway I am pretty interested in improve these kind of features for `reactour` (PR welcome!).

As soon as I have a peace of time, I'll dive in this specific scenario where I think it is necessary something like a global `ref` for the _Tour_. 

Let me know if the workaround works or if you have an idea to improve…

**Comment by jovstern** [comment]
so, in the last version the update/location.pathname can be use already?
by the way, it will be great for other user if you can expend your readme file, most of my knowledge about your widget came from the code itself.

**Comment by elrumordelaluz** [comment]
> by the way, it will be great for other user if you can expend your readme file
Yes, absolutely agree. I have in mind to expand the descriptions and make some little video _Tutorials_ (_Tours_? 😂). Also help/PR wanted!

Regarding to `update` is a property that accepts a `String`, then the _Component_ when detect a change in this `prop` will force an update. In my case I am passing the `location.pathname` property from `react-router` so, when the _App_ location changes, the _Tour_ update with some filters in the `steps` array.

Let me know if you have a little repro where we can use as _playground_ to show you what I mean.
Otherwise, when I have time will create something like a _playground_ to test these features.

**Comment by jovstern** [comment]
Sounds good, for now i'm using basic eventListener JS and it's work well but, i prefer more clean and react way.
after a deep research (also payment library were checked) we are going to use your library, so continue the good work!

**Comment by elrumordelaluz** [comment]
Thanks @jovstern ! 
I'd love to see the _Component_ in your _Application_ live if you can.

Will close this issue to create separate ones for the topics we discussed here.
Feel free to re-open or open new ones.

Thanks again,

**Comment by jovstern** [comment]
I'll let you know when we deploy it, you most welcome!
