### ISSUE TITLE
Programatically Go to Next

### ISSUE THREAD

**Issue by developdeez** [elrumordelaluz/reactour#110]
Im almost the end of my tour and Im opening a menu. The trouble is I want the next step to show when the menu shows. 
I would assume there is a call but didn't see any. The user is clicking a button that changes state to open the window btw.

**Comment by elrumordelaluz** [comment]
Hi @developdeez could you make a little repro in a [codesandbox](https://codesandbox.io/) or similar? 

Could help you [gotostep](https://github.com/elrumordelaluz/reactour#gotostep) prop?

**Comment by developdeez** [comment]
I'll give it a try. I've never used codesandbox :D
I'll try see how to use gotostep as a prop. I haven't seen it in the examples. 

Basically what I have is a page that shows a tab. The tab shows when the user clicks the tab by changing the state of it to visible. 

The Tour lives on this page and shows properly ob the first tab. But when I click the second page the first tabs tourbox is still showing. 

Id like to trigger go next when changing tabs if possible.

**Comment by developdeez** [comment]
How exactly do we get the gotostep prop in the component

**Comment by elrumordelaluz** [comment]
Don't know if match your specific _use-case_, but maybe could be helpful this [example](https://codesandbox.io/s/pw9l4w4olj) where there are two tabs, and when clicking (or changing it with keyboard), the step will match the same `index`.

![codesandbox](https://user-images.githubusercontent.com/784056/52377405-14c48e00-2a65-11e9-9778-ae7404cc49c9.gif)

**Comment by jasan-s** [comment]
@developdeez did you find a good way to goToNext . for my use case i need to go to next step if user click on an element on the page. however I don't have access to goTo outside of content ?

**Comment by darklightblue** [comment]
I'm having the same issue - I tried using `goToStep` and programatically do it but it seems that it doesn't get called (I tried debugging the code and `componentWillReceiveProps` seems to be not working on my end tho (?)). 

@jasan-s you can try using `goToStep` and store a copy of "current step" on your local state.

**Comment by volkandkaya** [comment]
@darklightblue did you get this working?

Trying to do something similar. When a user clicks a button want to move to next step. I have the step and try to set goToStep on the <Tour> and it doesn't do anything.

**Comment by volkandkaya** [comment]
@elrumordelaluz is this possible to do? Once fixed I can implement it into my project, users will be so happy.

**Comment by volkandkaya** [comment]
@elrumordelaluz Any updates on this?

It seems like a big problem as most apps will have modals etc that need this.

**Comment by FrederikStenberg** [comment]
> @elrumordelaluz Any updates on this?
> 
> It seems like a big problem as most apps will have modals etc that need this.

I managed to do this by initializing the Tour component with the 'goToStep' prop: 
```
<Tour
	steps={steps}
	isOpen={this.state.isTourOpen}
	onRequestClose={this.closeTour}
	className="tour__helper"
	rounded={5}
	onAfterOpen={this.disableBody}
	onBeforeClose={this.enableBody}
	showNumber={false}
	goToStep={this.state.currentStep}
/>
```

Then I just change my currentStep state as I go and it updates accordingly.

**Comment by cherishh** [comment]
I found a hack on this, see https://github.com/elrumordelaluz/reactour/issues/74#issuecomment-678971520

**Comment by volkandkaya** [comment]
> I found a hack on this, see [#74 (comment)](https://github.com/elrumordelaluz/reactour/issues/74#issuecomment-678971520)

Yep already use goToStep, problem is with modals.

**Comment by eric-willits** [comment]
@volkandkaya did you end up finding a fix for that?  im trying to do the same thing in my app...

**Comment by developdeez** [comment]
No I stopped using the package
