### ISSUE TITLE
stepInteraction behavior is unclear

### ISSUE THREAD

**Issue by kwayebopp** [elrumordelaluz/reactour#112]
First, this is a great library and it's super easy and fun to use. The only thing that I found confusing was the behavior of the `stepInteraction` prop. 

This code **will not disable** the step's selected element:
```
<Tour steps={[
    {
      stepInteraction: false
      selector: "#restart-tour",
      content: (
          <div>
              <p>Click here to restart any of your tours.</p>
          </div>
      ),
       position: "right"
    },...]} 
/>
```

But this code **will enable** the step's selected element if the tour has the `disableInteraction` prop:

```
<Tour
  disableInteraction 
  steps={[
    {
      stepInteraction: true
      selector: "#restart-tour",
      content: (
          <div>
              <p>Click here to restart any of your tours.</p>
          </div>
      ),
       position: "right"
    },...]} 
/>
```

I couldn't figure out that `stepInteraction` was meant to be used in conjunction with `disableInteraction` until I decided to inspect [some of the source code here](https://github.com/elrumordelaluz/reactour/blob/5f3ee03f5603f008a719fe840710852dc39d2756/src/Tour.js#L464).

If would be great if this behavior were noted in the README or if the `stepInteraction` prop could work on its own.

**Comment by elrumordelaluz** [comment]
Hi @kwayebopp you are absolutely right. Will be solved in the next release. Thanks for the input!
