### ISSUE TITLE
Selecting multiple elements

### ISSUE THREAD

**Issue by daniel-barnett** [elrumordelaluz/reactour#113]
I was wondering if it was possible to select multiple elements for a step; I couldn't see any options for it nor did using an array as the selector. 

My use-case is selecting a subset of `<td>` within a `<tr>`, i.e. something like this where the `x`'s denote the cells that are highlighted. 

| 1 | 2 | 3 | 4 | 5 |
| --- | --- | --- | --- | --- |
|   |   | x | x | x |

**Comment by elrumordelaluz** [comment]
Hi @daniel-barnett, thanks for the _Issue_. Since you couldn't add extra markup between columns/rows in html `table` you have two options: not use `<table>` 😆 or solve using `colgroup` like in [this example](https://codesandbox.io/s/0qpx4rjn9v).

For now `reactour` generate one single _Mask_ calculating the bounding of a specific element un the markup. In case you need more that one you could group using html/css but the `table` case is a bit specific.

Let me know

**Comment by t3chguy** [comment]
I have the same use-case and the `colgroup` example you have provided does not work for me, it just selects a 0x0 in the top left corner:
![image](https://user-images.githubusercontent.com/2403652/55876580-df850b00-5b8f-11e9-991d-47d187ae9ab6.png)

**Comment by elrumordelaluz** [comment]
do you have a _sandbox_ to give an eye @t3chguy ?

**Comment by t3chguy** [comment]
That screenshot was from the sandbox you linked above: https://codesandbox.io/s/0qpx4rjn9v

**Comment by elrumordelaluz** [comment]
mine here: <img width="1479" alt="Screenshot 2019-04-10 at 17 08 52" src="https://user-images.githubusercontent.com/784056/55890624-567fcb00-5bb3-11e9-816a-1867f479254d.png">

which browser?

**Comment by t3chguy** [comment]
Windows 10 Chrome Version 73.0.3683.103 (Official Build) (64-bit)

also it doesn't allow for just a group columns in a single row even if it were to work

**Comment by designbyadrian** [comment]
I'm trying to achieve something like this:

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/2064558/57321195-bd33ce00-70f8-11e9-83be-4b7bf8936743.png">

and it'd be great if I could just use css class selector to find all items I wish to highlight.

**Comment by elrumordelaluz** [comment]
hey @designbyadrian, thanks for your example. It would be very interesting to allow something like this. It's not related on `css` selectors, but more a _layout_ stuff, since the mask need to make more calculations and have more layers to leave visible more that one _highlighted_ element.

**Comment by darklightblue** [comment]
I am trying to achieve the same thing - In my case I have a list of divs and on the end of that list is a button (the same size as the divs before it) I want to highlight list without highlighting the button, unfortunately I can't wrap them in one container without destroying the layout

**Comment by woutvanneste99** [comment]
Hello, is there any news on this? Or any alternative to be able to have multiple element in the same step?

thx

**Comment by GiancarlosIO** [comment]
👀

**Comment by jcoelh0** [comment]
👀

**Comment by elrumordelaluz** [comment]
Plase try [highlightedSelectors](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#highlightedselectors-string) step prop in **new v2 version** released under scoped `@rectour` package name, please try `npm i @reactour/tour`. Every feedback super welcome, thanks!

**Comment by fostimus** [comment]
@elrumordelaluz is there a way to use `highlightedSelectors` in a class based component? v2 seems to favor hooks, which I can't use.

**Comment by elrumordelaluz** [comment]
hi @fostimus, you mean something like the following code?

```js
{
  // ...
  highlightedSelectors: ['.my-component']?
}
```

**Comment by fostimus** [comment]
hi @elrumordelaluz, that does work - realized after I asked that `highlightedSelectors` is in 1.18.0 so I'm using that version. Our codebase still relies heavily on class based components, so 2.0.0 won't work for us.

**Comment by fostimus** [comment]
One question on `highlightedSelectors`, does it only highlight by union? Is it possible to highlight separately, so 2 different/disjoint areas are highlighted?

**Comment by elrumordelaluz** [comment]
> Our codebase still relies heavily on class based components, so 2.0.0 won't work for us.

I'm sorry, but happy that v1.x works for you!

> Is it possible to highlight separately

Not now, it should be making more calculations to customize the _Mask_ with more complexity.

Leaving here as *feature request*: custom _Mask_ with multiple "holes" for different ´elements´.

**Comment by JCLimpide** [comment]
Just leaving a comment for @fostimus or others who are using class component.

I didn't test the highlighting itself, but I wrote a small workaround:  a Higher-order-component, allowing to use all the tour hooks in class components.
The code is fairly simple:


```
import { useTour } from '@reactour/tour'

const withTour = (Component) => (props) => {
  const /*{ isOpen, currentStep, steps, setIsOpen, setCurrentStep }*/ propsTour = useTour();

  return <Component { ...props } { ...propsTour } />
}
export default withTour;
```

**Comment by elrumordelaluz** [comment]
@JCLimpide cool! mind make a PR exporting also `withTour` from the lib?

**Comment by INNOVATIVEGAMER** [comment]
> Leaving here as _feature request_: custom _Mask_ with multiple "holes" for different ´elements´.

@elrumordelaluz Has anyone worked on this till date ?

**Comment by elrumordelaluz** [comment]
> > Leaving here as _feature request_: custom _Mask_ with multiple "holes" for different ´elements´.
> 
> [@elrumordelaluz](https://github.com/elrumordelaluz) Has anyone worked on this till date ?

nope till now
