### ISSUE TITLE
Disable controls while performing an action

### ISSUE THREAD

**Issue by frassinier** [elrumordelaluz/reactour#115]
Hello there 👋

I'm wondering if you know any good solution to temporary disable controls for a step?
I would like to profit of displaying the tour to suggest to the user to import samples.
I think about retrieving controls using `action` callback in my step and then manipulate them via `content` function, but it is not really sexy.

Any advice?

**Comment by elrumordelaluz** [comment]
Hi @frassinier , thanks for open the _Issue_.
Let me know if I understand well, you need to _disable_ controls (next, close, etc) when you are in a specific `step`, so the user must do _that_ action? how change the to the next/prev `step`? I think I am missing something.

However pretty interested in your _Issue_ that seems a potentially _feature_ to implement.

**Comment by frassinier** [comment]
Thank you, that's exactly what I want to do, but just for a quick period, while loading stuff.

Let me show you what I want to achieve:

Here is the demo, please check step 2 and click on the button to trigger a sample.
http://2085.talend.surge.sh/components/?selectedKind=GuidedTour&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Here is the piece of code for now
https://github.com/Talend/ui/pull/2085/files#diff-b6c88a459ae164037a1669b61dca3775R108

**Comment by elrumordelaluz** [comment]
Hey @frassinier, thank you for sharing your code, it's super clear the idea.

Available now you have two options. [Here](https://codesandbox.io/s/7m7p82o5zx?fontsize=14) is one using `showNavigation`, `showButtons` and `showNumber` _Tour_ props (you could also add `disableKeyboardNavigation` and so on). The second one is to make the same approach but changing the _Helper_, customizing on your needs like in the [demo](https://reactour.js.org/) when you press `enter`, [here the code](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L54) (this _feature_ is not documented yet but available).

Let me know,

**Comment by frassinier** [comment]
Thank you Lionel, I will try today.

**Comment by frassinier** [comment]
Thank you for demo, 🎉 
I've just copied (and adapted) your code from codesandbox.io and it works like a charm! 👌 
I close this issue.
