### ISSUE TITLE
Can I highlight the circle, not a square?

### ISSUE THREAD

**Issue by clicktronix** [elrumordelaluz/reactour#116]
Hello, there is a case where I need to highlight a round button. For example, as in the demo it would be possible to highlight the picture of the bus around. Is it possible?

**Comment by elrumordelaluz** [comment]
Hi @clicktronix, thanks for open the _Issue_. This sounds an interesting thing. Let's give it an eye on possibles way to do something related.

**Comment by elrumordelaluz** [comment]
pinging @qboot in case have any insight

**Comment by clicktronix** [comment]
@elrumordelaluz  We decided this case differently, but if there is still a similar one, then we will try to implement it. Now there is not enough time. Thank you for responding

**Comment by elrumordelaluz** [comment]
Cool, I am closing the _issue_. Please feel free to re-open or open another one in case of further needs.
