### ISSUE TITLE
How to switch between multiple url

### ISSUE THREAD

**Issue by praveenkutty** [elrumordelaluz/reactour#117]
As i want my tour to work on multiple url,
Through my "action" method iam redirecting to another page but reactour is not displayed there.
Kindly help me out with some examples
Thanks in advance

**Comment by elrumordelaluz** [comment]
Hi @praveenkutty, thanks for open the _Issue_.
Should be possible using `update` prop, however you could find some examples and thread on #68. 
Something like [this](https://codesandbox.io/s/myry48155p).

Let me know if it's useful, otherwise we'll try to find alternatives.

**Comment by praveenkutty** [comment]
This example is not clear so please help me out with some other examples for switching between multiple pages 
through my action iam able to change url but i was not able to display the tour in new page
continuity is missing

**Comment by elrumordelaluz** [comment]
hey @praveenkutty, [here](https://myry48155p.codesandbox.io/topics) is a full page view of the same _codesandbox_. Did you noted on second `step`, the `action` fires a url change (line 71 [here](https://codesandbox.io/s/myry48155p))

```js
action: () => history.push("/topics")
```
Until there, I think is clear, but this behavior works well because we are passing the `pathname` prop (in this case from `react-router-dom`) as `update` in the _Tour_ Component (line 102)

```diff
<Reactour
  steps={steps}
  isOpen={isOpen}
  onRequestClose={closeTour}
+ update={pathname}
/>
```

**Comment by praveenkutty** [comment]
This is my code
https://codesandbox.io/s/o5k956ovl5?fontsize=14
I cant able to execute tour in second page

**Comment by praveenkutty** [comment]
Hi @elrumordelaluz , I had checked that option and it works as expected to switch a URL, but one issue I noticed is I don't see (line 70) "This is the Home Content" displayed.

I wanted to traverse from home -> about -> topics 

I tried 
{ selector: ".home",
  content: "This is the Home Content }  , 
{action: () => history.push("/about")}

This does show "This is the Home Content" (Line 70) and moves to /about when I click the next button. But none of the steps in /about or /topics work, the tour exits here.. Any pointers to how I can achieve this flow home -> about -> topics

**Comment by elrumordelaluz** [comment]
Ok, so I think #102 is the _issue_ related

**Comment by praveenkutty** [comment]
Hi @elrumordelaluz thank you for the reference. 

Can you please suggest a workaround option to achieve the home -> about -> topics path flow including url change and all steps in forward as well as reverse direction.

**Comment by praveenkutty** [comment]
Hi @elrumordelaluz thank you for the reference.

Can you please suggest a workaround option to achieve the home -> about -> topics path flow including url change and all steps in forward as well as reverse direction.

**Comment by praveenkutty** [comment]
Hi @elrumordelaluz I tried the below code

...(pathname === "/"
        ? [
            {
              selector: ".home",
              content: "This is the Home Content"
            },
            **_{
              action: () => {
                if (pathname === "/") history.push("/about");
              }_**
            }
          ]

Now it works little bit as i wanted but i get an error as below

TourPortal.js:462 Uncaught TypeError: Cannot read property 'style' of undefined
    at TourPortal.render (TourPortal.js:462)
    at finishClassComponent (react-dom.development.js:8389)
    at updateClassComponent (react-dom.development.js:8357)
    at beginWork (react-dom.development.js:8982)...............

And the tour loses the continuity 
https://codesandbox.io/s/2wn6oq675r?fontsize=14

Please suggest how i can workaround this

**Comment by praveenkutty** [comment]
Hi @elrumordelaluz  
I got this working  home -> about -> topics and topics->about->home path flow with all steps and URL's
Here is my code
https://codesandbox.io/s/4r4rj0vv09

PS:Any suggestions welcome

**Comment by elrumordelaluz** [comment]
Awesome @praveenkutty. Will give it an eye.
