### ISSUE TITLE
Internet Explorer 11 support

### ISSUE THREAD

**Issue by frassinier** [elrumordelaluz/reactour#118]
Hello,

Is it a huge effort to support IE 11?
I can see the black mask on the half of my app and I can't interact with it.
Is there any blocker to support it?

Thanks!

**Comment by elrumordelaluz** [comment]
Hi @frassinier, thanks for open the _Issue_.

I don't have IE11 at the moment to test, however will give it a look asap.
In the meantime, should be useful if you could inspect what kind of element is creating the _issue_, like ie the `svg` mask, and so on…

**Comment by frassinier** [comment]
I start to investigate, keep in touch

**Comment by frassinier** [comment]
I suspect `@babel/polyfill` to be missing.

I would like to try,
How can I generate le lib that you used to publish on npm? 
I tried `yarn lib` and `yarn build`without any success?

**Comment by elrumordelaluz** [comment]
First I'll ask you to `pull` the last _commit_ where I [switched back](https://github.com/elrumordelaluz/reactour/commit/a7cd32f97e996c9abf3b10ecdc149e511133e245) to use regular _Tour_ component (where using one –incomplete– using `hooks` yen not published).

The command is `yarn lib`, what king of error you have?

**Comment by frassinier** [comment]
None actually I was just surprised by the Rollup output.

I will switch back on it soon.

**Comment by frassinier** [comment]
Ok, so, the good news is that it works out of the box with IE 11 (we've just to deal with the css variables like described in #6). Sorry.

The bad one is it does not work when I use it in my project and I don't know why. Styled Components puts an extra `<style>` in the head but it's empty, there is no CSS at all, except comments.

And the demo does not work with IE11 because it requires an `import '@babel/polyfill` at the beginning of the file.

**Comment by elrumordelaluz** [comment]
No problem!

>  Styled Components puts an extra <style> in the head but it's empty, there is no CSS at all, except comments.

Sound weird. What version of `sc` are you using?

> And the demo does not work with IE11 because it requires an import '@babel/polyfill at the beginning of the file.

Mind make a PR to fix the demo for IE11? thanks!

**Comment by frassinier** [comment]
> Sound weird. What version of sc are you using?

**Comment by elrumordelaluz** [comment]
Ok, I'll close this _Issue_ since with your PR everythig seems solved, at least whet related to `reactour`. Feel free to re-open or open a new one in any case.

**Comment by frassinier** [comment]
FYI styled components were broken because of angularjs. 
https://github.com/styled-components/styled-components/issues/657
