### ISSUE TITLE
New version (39)

### ISSUE THREAD

**Issue by YavorskyiBohdan** [elrumordelaluz/reactour#122]
Could you deploy a new version? There is a couple of fixed bugs and ie11 styles in pull requests merged into master. Thank you.

**Comment by elrumordelaluz** [comment]
Hi @YavorskyiBohdan, thanks for open the _Issue_.

Absolutely! could you please tell me what changes you don't see in the last published version?

**Comment by YavorskyiBohdan** [comment]
npm version was last updated two month ago. Since then there were a few changes in master

**Comment by elrumordelaluz** [comment]
📦 `reactour@1.13.2`

**Comment by YavorskyiBohdan** [comment]
@elrumordelaluz thank you!

**Comment by elrumordelaluz** [comment]
Seems something is broken, let's investigate. Thanks for your patinence.

**Comment by elrumordelaluz** [comment]
📦 `reactour@1.13.3` works without _issues_
