### ISSUE TITLE
Calling the original function in overridden functions

### ISSUE THREAD

**Issue by noncom** [elrumordelaluz/reactour#123]
There is the possibility to override functions like `nextStep` to inject some custom behavior, but if you do so, how do you access any of the information from the Tour component to retain its original `nextStep` functionality? I would not like to break the original `nextStep` function, but rather add some custom code that should be happening when the user clicks the button.. for example, what if I want to check some condition and decide if I want to skip the step?

And as a followup: would it not be useful to add callbacks such as `onNextStep` ?

**Comment by elrumordelaluz** [comment]
Hi @noncom , thanks for open the _Issue_.

I think should work as what you expected. Probably there are some missing assignments to fix.

Thanks you for the input!
