### ISSUE TITLE
Step ignored if tour not open when setting (or about to close)

### ISSUE THREAD

**Issue by SacredSkull** [elrumordelaluz/reactour#124]
As far as I can tell, this is a bug, but it might've been an intentional design decision. The app I'm working on has a tutorial/tour, and they may want to restart the tour - so the tutorial should start at step 1 (or 0).

Setting the step when the tour is open works as expected; you can jump between steps, go backwards, etc.

However, when `isOpen=false` (also inside either `onRequestClose` or `onBeforeClose`) and you set `step`, it is ignored.

I have a very artificial example [here](https://codesandbox.io/s/1q4j57qmq3). Basically, if you open the tour and close it, with the X or by clicking on the mask, when you press `start tour again` it _should_ be on the other tab/tour step, but it remains on whatever last step.

**Comment by SacredSkull** [comment]
Unrelated - is there any way to override the movement behaviour of the popup/modal? For example, instead of having it follow each element, allowing the programmer to set an absolute/relative position for a step/group of steps?

**Comment by elrumordelaluz** [comment]
Hi @SacredSkull , thanks for open the _Issue_.

If I understand well the point, [startAt](https://github.com/elrumordelaluz/reactour#startat) prop is your friend. [here](https://codesandbox.io/s/zw5w5j2wnp?fontsize=14) is a fork of your example that always starts at `0`.

**Comment by elrumordelaluz** [comment]
> Unrelated - is there any way to override the movement behaviour of the popup/modal? For example, instead of having it follow each element, allowing the programmer to set an absolute/relative position for a step/group of steps?

Not for the moment but could be a valid _feature_, mind open a new _Issue_ to track this specific case?

**Comment by SacredSkull** [comment]
I swore I tried that before, but I must have been using it incorrectly somehow. 

Yes, this works as it should!
