### ISSUE TITLE
Observe not working correctly

### ISSUE THREAD

**Issue by pedrodorini** [elrumordelaluz/reactour#128]
Hi,
I'm having some problems with the observe in the tour, I have two popover filters that are using tour's observe, the first one works fine. I use some background logic to automatically go to the next step when a option in the filter is selected.
My problems is: when the user don't select anything, the popover closes and the focus should go back to the button that opens the popover. The first filter works fine, but on the second filter, which is structured in the same way as the first one (and the observe demo), the focus stay on the popover that's no longer on the screen, as shown in the gif below. The popover is conditionally rendered so it's not hidden

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26284548/55899510-5a075800-5b9b-11e9-9636-6407a54fab85.gif)

The steps:
```
[
    {
      selector: '[data-tut="step-one"]',
      content: () => (
        <div>
          Vamos começar! clique no filtro, selecione um tipo de negócio e clique
          em OK
        </div>
      ),
      position: 'right',
      observe: '[data-tut="step-one"]',
    },
    {
      selector: '[data-tut="step-two"]',
      content: () => (
        <div>
          Agora selecione os tipos de imóveis que voce deseja procurar e clique
          em OK
        </div>
      ),
      position: 'right',
      observe: '[data-tut="step-two"]',
    },
...
```

The first filter:
```
<div className={classes} data-tut="step-one">
  //Fuction that render the filter button
  {createFilterButton({
    icon: { size: 20 },
    error: error.businessType,
     label: privateBusiness
       ? `${businessType} Particular`
       : businessType || 'Tipo de Negócio',
     isOpen: this.state.active,
     onClick: this.toggleContainer,
   })}
   {active && (
     <div className="FilterContainer">...</div>
   )}
</div>
```

The second filter
```
<div className={classes} data-tut="step-two">
  {createFilter({
    label: 'Tipo',
    error: error.category,
    count: getCount(category),
    icon: { size: 20 },
    isOpen: this.state.active,
    onClick: this.toggleContainer,
  })}
  {active && (
    <div className="FilterContainer">...</div>
  )}
</div>
```

**Comment by elrumordelaluz** [comment]
Hi @pedrodorini, thanks for open the _Issue_.

Sounds pretty interesting to analyze some possible reasons. 

However I put some things that come in mind quickly.
Keep in mind that the _Observe_ functionality uses [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to catch changes inside the _DOM_ element assigned into `step.observe` prop.
Take a look at the _Demo_ where the [observe prop](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L240) point to a [parent element](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/Demo.js#L130-L133) of the _Button_ that fires those changes. 

Could you please try making some changes to _observe_ a parent element. It would be useful if you could make a simple repro in a codesandbox to play with.

**Comment by pedrodorini** [comment]
Thank so much for the reply @elrumordelaluz, I accidentally found a work around, the content of my filter is a form, so before submit it I call a function that set the goToStep value to undefined, I don't know exactly the logic behind it LOL, but once undefined is passed and the form is submitted(popover closes) the focus goes back to the filter button as it should be

**Comment by elrumordelaluz** [comment]
> …so before submit it I call a function that set the goToStep value to undefined

I can't find the `goToStep` in the code you share, why are you using [it](https://github.com/elrumordelaluz/reactour#gotostep)? 

The useful point of `observe` is that changes _target_ without change `step`, like in the last setp in the [demo](https://reactour.js.org/)

**Comment by pedrodorini** [comment]
I'm using the goToStep to go automatically to the next step after a option is selected on the filter, i have some validation that verify if this filter has some value, and if this condition is attended the step is incremented, I not using the goToStep to change between the elements, each filter is a step. The focus on the popover once the filter button is clicked is not a step.

**Comment by elrumordelaluz** [comment]
cool, so you are using `observe` the same way in the _Demo_.

> I accidentally found a work around…
So you found a solution? Could you share in case could be helpful for others? 
Is there anything that you think need to be implemented on the `reactour` side?

Thanks again,

**Comment by elrumordelaluz** [comment]
Closing this. Feel free to re-open or open a new one in any case.

**Comment by adamsoffer** [comment]
@elrumordelaluz observe doesn't work for me. Even when using a parent element. I'm on `v1.15.4`. Was there some sort of breaking change introduced. I noticed the demo is using `v1.12.0`

**Comment by samsiu2014** [comment]
> @elrumordelaluz observe doesn't work for me. Even when using a parent element. I'm on `v1.15.4`. Was there some sort of breaking change introduced? I noticed the demo is using `v1.12.0`

I got the same problem too!

**Comment by elrumordelaluz** [comment]
hey @adamsoffer @samsiu2014, could you please share a reduced repro? I updated _dependencies_ in the [sandbox demo](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js) and doesn't seems broken.
