### ISSUE TITLE
when entering text the focus of input is lost

### ISSUE THREAD

**Issue by TomerAlgrably** [elrumordelaluz/reactour#129]
Hi,
![clicking](https://user-images.githubusercontent.com/28543030/56365711-30cd7400-61fa-11e9-922d-cce5f49425a0.gif)
This is what I get.

My code is:

For the step:

```js
const steps = [
    {
      selector: '#campaign_step',
      content: ({ goTo }) => (
        <div>
            <p>{i18n.leaders['Welcome to Leaders Market, start by entering the name of the campaign you\'ll be working on']}</p>
            <p>{i18n.leaders['For example: New sunglasses campaign']}</p>
            
          <button
            className="btn btn-adv-teal"
            onClick={() => goTo(1)} >
            {i18n.leaders['Next step']}
          </button>
        </div>
      ),
    //   stepInteraction:true,
      position:'right',
      action: node => {
        // by using this, focus trap is temporary disabled
        node.children[1].focus()
        console.log(node)
      },
    },
]
```

The Tour:
```js
<div className="rtl">
    <Tour
            // closeWithMask={true}
            disableKeyboardNavigation={true}
            // disableInteraction={false}
            onAfterOpen={this.disableBody}
            onBeforeClose={this.enableBody}
            steps={steps}
            rounded={5}
            showNavigation={false}
            showButtons={false}
            isOpen={this.state.tourOpen}
            onRequestClose={this.closeTour} 
            />
</div>
```
For the input:
```jsx
<div id="campaign_step">
      <h4
        className={this.state.errors.campaign_name && 'help-block-error-bold'}
      >
        {i18n.leaders['Campaign name']}
      </h4>
      <input
        id="campaign_name"
        type="text"
        tabIndex="1"
        onChange={value => {
          if (value) {
            document.getElementById('camp_name').textContent =
              value.target.value
          }
          this.setState({
            activityEdit: {
              ...this.state.activityEdit,
              name: value.target.value,
            },
          })
        }}
        onBlur={value => {
          let campaignError = value.target.value == '' ? true : false

          if (campaignError !== this.state.errors.campaign_name) {
            this.setState({
              errors: {
                ...this.state.errors,
                campaign_name: campaignError,
              },
            })
          }
        }}
        className="form-control form-control-adv adv-input-field"
        name="campaign_name"
        // placeholder={i18n.leaders['Campaign name']}
        value={this.state.activityEdit.name}
      />
    </div>
````

Thanks a lot!

**Comment by elrumordelaluz** [comment]
Hi @TomerAlgrably, thanks for open the _Issue_.

Seems something related on _FocusTrap_ added recently.

Could you please try using `reactour@1.13.3` to check if this doesn't happen?

**Comment by elrumordelaluz** [comment]
Trying something fast [here](https://codesandbox.io/s/xvlkx825w?fontsize=14&module=%2FApp.js) I see two things: the first is that seems that you don't need to make `node.children[x].focus()` but is enough to have the action declared. I need to investigate more deeply here to know what happens.

However in my case, writing in the `input` doesn't make lose `focus`.

![tour](https://user-images.githubusercontent.com/784056/56380557-c1b04980-6212-11e9-830e-440f82b73c2a.gif)

It's probably that your `input` is a controlled one, using internal `state`, but firing a re-render not wanted that make re-render the _Helper_. 

Please let me know.

**Comment by TomerAlgrably** [comment]
Thanks, I changed the onChange to onBlur, and I removed the value and made it defaultValue and now it's working!
@elrumordelaluz

**Comment by Alpa84** [comment]
Hi there,
I have a reactour step that highlights a component with a controlled input that is re-rendered on every change.
In this case re-rendering is intentional because I'm generating a live hint on what the input should be.  The problem is that the focus on the input is lost when entering text
[Here](https://codesandbox.io/s/reactour-controlled-input-1u3tt) is a short sandbox that shows the issue 
Is it possible to avoid this issue?

**Comment by elrumordelaluz** [comment]
Hi @Alpa84,
You are re-rendering the _Component_ where the _Tour_ is in, so with each `state` change, you are re-rendering an open _Tour_, and this is the reason why you are loosing `focus` on the `input`. 

Try separating components like [in this fork](https://codesandbox.io/s/reactour-controlled-input-y2jck?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Alpa84** [comment]
It works! Thanks much. Awesome work

**Comment by wsz7777** [comment]
I use some like context、redux to set state. then ,I can't controlled input?

**Comment by wsz7777** [comment]
I use disableFocusLock as true can fix this problem.
