### ISSUE TITLE
Server Side Rendering Support

### ISSUE THREAD

**Issue by mastepanoski** [elrumordelaluz/reactour#130]
If you use it along next.js, the server side compiling process fails because of a reference error: `
ReferenceError: document is not defined
    at new FocusOutlineManager (node_modules/focus-outline-manager/focus-outline-manager.js:34:5)
    at Object.<anonymous> (node_modules/focus-outline-manager/focus-outline-manager.js:84:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (node_modules/reactour/dist/reactour.cjs.js:7:1)
`
Using it with dynamic import works:

`
const Tour = dynamic(
  () => import('reactour'),
  {
    ssr: false
  }
)
`

But you can not test it in a storybook and separate the component from the SSR Framework (it should work on any SSR framework).

**Comment by elrumordelaluz** [comment]
Hi @mastepanoski, thanks for open the _Issue_.

I think what you are doing with [dynamic import](https://github.com/zeit/next.js#dynamic-import) telling `ssr: false` is the same as adding some condition like `if (typeof window !== 'undefined')`. So it's ok.

However, the point is that the _Tour_ needs to be client side, since checks and made calculations based on `bounding box` og target elements.

Let me know if you have any idea on how we can improve this. Thanks!

**Comment by mastepanoski** [comment]
Hi @elrumordelaluz, about:

> However, the point is that the Tour needs to be client side, since checks and made calculations based on bounding box og target elements.

That is right, and yes, adding the condition **if (typeof window !== 'undefined')** is enough, nevertheless there is other way is doing something like this:

`import React from 'react'

const DefaultOnSSR = () => (<span></span>)

export default class YourComponent extends React.Component {
  state = {
     canRender: false
  }

  componentDidMount() {
    // add the NoSSR (client side) stuff here.
    this.setState({ canRender: true })
  }

  render() {
    const { canRender } = this.state

    return canRender ? (
        // client side code
    ) : (
        <DefaultOnSSR />
    )
  }
}`

Or you can use this component: https://github.com/kadirahq/react-no-ssr
 
I hope this sample can help you to find a way.

**Comment by elrumordelaluz** [comment]
Thanks @mastepanoski for the inputs regarding SSR.
Since for now I think is up to the end user to make this checks, I'll close the _Issue_ but feel free to re-open (or open a new one) in any case.

Thanks again,

**Comment by thalseth** [comment]
I solved this issue using `react-loadable` in Gatsby SSR context. 
Example:
```jsx 
import Loadable from 'react-loadable';

const Tour = Loadable({
  loader: () => import('reactour'),
  loading: () => null,
});

```

Thanks for the awesome package @elrumordelaluz 💯

**Comment by elrumordelaluz** [comment]
Cool @thalseth, thanks for sharing the solution!

**Comment by andrewmclagan** [comment]
Also nor next js see https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr
