### ISSUE TITLE
Remove dependency to Styled Components.

### ISSUE THREAD

**Issue by designbyadrian** [elrumordelaluz/reactour#132]
Is it possible to remove the dependency to styled components? It's a bummer having to install it in a project just to use one library. Some use other libraries or proper CSS/SASS.

**Comment by elrumordelaluz** [comment]
Hi @designbyadrian, thanks for open the _Issue_.

This library is using at the moment SC to translate the calculations based on the contents of the _Helper_ and the _Highlighted_ element into styles to apply to the _Mask_ and _Helper_ fundamentally.

In #100 was asked something similar like, depend on a css-in-js library but not in a speceific one.

Again, for me sounds a legit request, but at the moment th _Tour_ needs a way to dynamically style its elements based on calculations.

Maybe is the opportunity to make an intermediate layer which output the calculations and the end-user applies as they want. Super open for proposals and PRs regarding this.
