### ISSUE TITLE
Programatically change step for a newly mounted component

### ISSUE THREAD

**Issue by d-ivashchuk** [elrumordelaluz/reactour#133]
First of all thanks for the great library, it's super smooth and easy to use! I am little bit stuck with a problem though.

I have a situation where in one of the steps I ask user to click a button which should in turn mount new component and highlight the dom element which wasn't present at the previous moment. I have already figured out that `goToStep` is a way to go for triggering the change but how to make it wait until the component with correct selector is already present in the DOM and highlight it once it's there? I would highly appreciate your advice and how you would handle it!

Thanks a lot!

**Comment by elrumordelaluz** [comment]
Hi @d-ivashchuk, thanks for open the _Issue_.

I think I understand, but could be super useful if you provide a simple reproduction of the situation in a [sandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js).

**Comment by d-ivashchuk** [comment]
The problem was project being quite complicated in terms of data loading on route changes so reproduction would take long. I've taken the road of just triggering next step when component mounts and all the data loads using `componentDidMount` and `componentDidUpdate` life cycle hooks so it works for now! Thanks!

Got stuck with other problem though, inputs are irresponsive when highlighted( step interaction is enabled) it seems like they lose focus immediately when you click them, so I can't type. If you have encountered this issue, would be cool to have your expert opinion, if no I will try to work on reproducing it, however spent some time already and struggled to reproduce in isolation from my project.

**Comment by elrumordelaluz** [comment]
A couple of versions back was added `focus-trap`. Is that issue happen also if you use `reactour@1.13.3`? 
However could be useful [this _Issue_](https://github.com/elrumordelaluz/reactour/issues/129#issuecomment-484611517) with a similar problem. 

Please check if your `inputs` are controlled and if doesn't fire unwanted re-renders.

Let me know,

**Comment by d-ivashchuk** [comment]
Thanks a lot, rolling back to `13.3` solved the issue. I was looking at this reproduction https://codesandbox.io/s/jpq5q6lly3 which just has plain html input without react state, and couldn't make even this simple case in my project. It was behaving the same way as react controlled inputs and lost focus on click.

 Just FYI in my case it wasn't like in the issue you pointed to. In that case smth was typed and focus was lost, in my case even clicking on input focused and then at once unfocused it so I couldn't even type one letter.

**Comment by elrumordelaluz** [comment]
Thanks @d-ivashchuk for test rolling back, so seems evident to be a _FocusTrap_ related issue.

Just to be sure, you mean in [this codesandbox](https://codesandbox.io/s/jpq5q6lly3) we have the same behavior as in your _App_?

You have a controlled `input` as target element (highlighted in specific `step`) and you are assigning `.focus()` throght `action`? so the is loosing? Could you please specify the way you are getting focus to the lose to let me analyse a little better?

**Comment by d-ivashchuk** [comment]
No, this codesandbox is working perfectly as far as I can see. I don't have any specific focus actions, the only thing is relevant is that I highlight the input which is plain <input type='text'> and can't type there at all, because when I click on it to get it in focus the focus is lost right away.

**Comment by elrumordelaluz** [comment]
Sounds something like an unwanted rerender. Your `input` is controlled, right? I'll try switching the example with a controlled one.

**Comment by elrumordelaluz** [comment]
[here](https://codesandbox.io/embed/rwj73y1pyq) is the same example with a controlled `input` and seems continue working.

**Comment by elrumordelaluz** [comment]
Closing this issue in favor of #137 to unify this specific situation. 

Feel free to re-open or open a new one in any case.
