### ISSUE TITLE
Background color 

### ISSUE THREAD

**Issue by rpashankar** [elrumordelaluz/reactour#134]
Hi team,
After modal popup come,background blur color need to be blue.
please suggest me so mething on it.

**Comment by elrumordelaluz** [comment]
Hi @rpashankar, thanks for open the _Issue_.

Now on `reactour@1.15.0` you can use the [maskClassname](https://github.com/elrumordelaluz/reactour#maskclassname) and assign a `color` property that will be inherited by the _SvgMask_.

Take a look at the [styles](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/styles.css#L24-L26) attached to the [maskClassName](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L59) at the _Demo_.
