### ISSUE TITLE
New helper layout

### ISSUE THREAD

**Issue by praveenkutty** [elrumordelaluz/reactour#135]
Hi @elrumordelaluz ,

I would like to change the helper as per the example below. 

![modified](https://user-images.githubusercontent.com/26202822/57844147-184a7c80-77ed-11e9-922b-069f50cd4d8a.png)

I tried the CustomHelper prop but could not get the desired results. Can you suggest the best way for this.

**Comment by elrumordelaluz** [comment]
Hi @praveenkutty, thanks for open the _Issue_.

Could you explain a little more what problem you encountered? 
What part of the _Layout_ you couldn't do with `CustomHelper`?
In order to know if is a _styling_ limit or lacking of exposed _elements_.

Thanks,

**Comment by praveenkutty** [comment]
Mine turns out like this

![helper1](https://user-images.githubusercontent.com/26202822/57849417-e17a6380-77f8-11e9-9515-2360ca97c3ce.png)

I wish to remove the extra paddings all around the helper box but unable to do so..

**Comment by elrumordelaluz** [comment]
Solved on `reactour@1.14.0`. Take a look at the [demo](https://reactour.js.org/), changing the _layout_ hitting _Enter_ key or the [source code](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L69-L126)

**Comment by praveenkutty** [comment]
hey @elrumordelaluz much appreciated thank you very much for the sample code.
