### ISSUE TITLE
Infinite componentDidUpdate() using action

### ISSUE THREAD

**Issue by lifzgreat** [elrumordelaluz/reactour#136]
Hi @elrumordelaluz, when using a step with `action` it causes `componentDidUpdate` to fire until the limit of nested updates is hit. Here is my situation, I may be doing it wrong:

Inside `componentDidMount` I use `setState` to update `steps` that differ depending on `location.pathname` and also set `isTourOpen` to true. That starts up the Tour. One of the steps has an `action` that sets the state to open a hidden side flyout panel to highlight some items inside of the panel (like a menu). When it does that, it opens fine and highlights the item fine but after a bit the <Tour> hits 25 nested updates and spits out this error.

![2019-05-17 15_15_52-SiteWalker](https://user-images.githubusercontent.com/5751658/57960759-9e8fbd00-78d8-11e9-9110-d886dd656b72.png)

**Comment by elrumordelaluz** [comment]
Hi @lifzgreat, thanks for open the _Issue_.

Could you please share a minimal reproduction, ideally in a [codesandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js)

**Comment by lifzgreat** [comment]
Hi @elrumordelaluz thanks for the response. This is close to what I'm trying to achieve: https://731yt.codesandbox.io/

**Comment by elrumordelaluz** [comment]
The problem is that the `state` change force a re-render and the `action` fires again and again.

Adding a condition works ok. 
```js
action: () => {
  if (!this.state.flyoutActive) {
    this.setFlyoutActive(true)
  }
}
```

Probably you'll want the action to fire before the _step_ change and something like this will arrive in the following releases.

**Comment by lifzgreat** [comment]
Aha, ok great. That fixes the error itself but now when the menu pops out, the highlight is not following it because of transition I guess (see picture). And yes, best would be to have the menu open before the step change which will be great if that comes in a future release :) Is there a way to make it highlight after the transition occurs? See this codesandbox for what I mean: https://codesandbox.io/s/731yt.

![2019-05-21 06_57_04-elated-haslett-731yt - CodeSandbox](https://user-images.githubusercontent.com/5751658/58090738-f7d84480-7b95-11e9-82fc-44dbf464bb1d.png)

Thanks for your help @elrumordelaluz!

**Comment by elrumordelaluz** [comment]
Try using the [update](https://github.com/elrumordelaluz/reactour#update) and [updateDelay](https://github.com/elrumordelaluz/reactour#updatedelay) props. Something like:

```js
<Tour 
  {...resProps}  
  update={this.state.flyoutActive}
  updateDelay={250}
/>
```

Pay attention that [this sandbox](https://codesandbox.io/s/731yt) doesn't have the `if` condition mentioned [before](https://github.com/elrumordelaluz/reactour/issues/136#issuecomment-494133807)

**Comment by lifzgreat** [comment]
Great that works for this step, thanks. Now what if you need more than 1 update value? For example, what if I need to pop out another menu on the left side of the screen and wait for that one as well? Since `update` seems to be a single property on `Tour` and not on a particular `step`, is that possible?

As for the sandbox, I had added the `if` condition before responding, I just didn't save it. It is saved now.

**Comment by elrumordelaluz** [comment]
`update` compares a _String_ to re-render if that value is changed, so you could try composing that _String_ with the `state` values you need.

**Comment by elrumordelaluz** [comment]
Sure, will be pretty useful. At the moment I have to solve some _layout_ issued related on this, but hope to release asap.
