### ISSUE TITLE
MultiPage

### ISSUE THREAD

**Issue by sjgmojica** [elrumordelaluz/reactour#138]
HI.

I need to create tour end to end to our app.It is possible to make it as multi page? I mean if I tour the user to 1st page and next to Second page. It is possible using this library?? If ever possible what I need to do to work?

Thanks

**Comment by elrumordelaluz** [comment]
Hi @sjgmojica, thanks for open the _Issue_.

It is possible using the [update](https://github.com/elrumordelaluz/reactour#update) prop that will fire a re-render when this value is changed. In case you use a `router`, you could pass `location.pathname` as the value, and render `steps` needed depending on where the _Application_ location is.

**Comment by sjgmojica** [comment]
Try to implement your recommendation.Thanks

**Comment by sjgmojica** [comment]
Ahm.can you provide me some pseudo code for the example of that???Thanks

**Comment by elrumordelaluz** [comment]
[Here](https://codesandbox.io/s/myry48155p) is an example where the `steps` changes base on the `location`.

**Comment by sjgmojica** [comment]
Oh nice.Thanks

**Comment by elrumordelaluz** [comment]
Closing to focus on _Issues_, please feel free to re-open or open a new one in any case.
