### ISSUE TITLE
Force pop up window to be in the center instead of moving to target

### ISSUE THREAD

**Issue by bgold0** [elrumordelaluz/reactour#139]
Is there a way to not have the pop up window go to whatever the selected element is? Can we just have the window be in the center of the screen?

**Comment by elrumordelaluz** [comment]
Sure @bgold0 you can add `position: 'center'` on each `step` you need this behaviour.

**Comment by elrumordelaluz** [comment]
I am closing this _Issue_ since seems solved, feel free to re-open or open a new one in any case.

**Comment by rdmclin2** [comment]
It still moves to target at first pop up.
