### ISSUE TITLE
Unable to close tour box

### ISSUE THREAD

**Issue by kiboone** [elrumordelaluz/reactour#140]
I am unable to close the tour box when I click the x, I was wondering what may be the cause of the problem. 

Thanks!

**Comment by elrumordelaluz** [comment]
Hi @kiboone, thanks for open the _Issue_.

Could you please share a peace of code or better a [codesandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js) trying to reproduce your problem?

Keep in mind that you have to pass at least these three `props` to the _Tour_: `steps`, `isOpen` and `onRequestClose`.

**Comment by kiboone** [comment]
The codesandbox link is
https://codesandbox.io/embed/hidden-butterfly-5b1mi?fontsize=14

**Comment by elrumordelaluz** [comment]
Seems broken the sandbox

<img width="1552" alt="Screenshot 2019-05-28 at 15 36 55" src="https://user-images.githubusercontent.com/784056/58482342-79177480-815e-11e9-93bb-5c418b884ab6.png">

**Comment by elrumordelaluz** [comment]
However on your _Tour_ component you have
```diff
      <Tour
          id="tour"
          steps={tourSteps}
          isOpen={isTourOpen}
--      onRequestClose={this.closeTour}
        />
```

but the `closeTour` method doesn't exists.

**Comment by kiboone** [comment]
Oh thank you, didn't realize that! That fixed it

**Comment by elrumordelaluz** [comment]
perfect!

**Comment by woodybooy** [comment]
![image](https://user-images.githubusercontent.com/56328199/141709262-f502fc17-ff63-45ba-aebc-4d38ce87c79d.png)
![image](https://user-images.githubusercontent.com/56328199/141709356-9901ceb9-396d-4298-a548-14c91d0a1b19.png)


hi how can i use  onRequestClose? i dont want to close the tour even i click the  shadow  background. when i remove  this onRequestClose the error triggered "Uncaught TypeError: onRequestClose is not a function...."

**Comment by elrumordelaluz** [comment]
@woodybooy try using [closewithmask: false](https://github.com/elrumordelaluz/reactour/tree/v1#closewithmask)
