### ISSUE TITLE
range mismatch of goTo input and step value returned

### ISSUE THREAD

**Issue by jasan-s** [elrumordelaluz/reactour#143]
the return step in content is returned with +1 to it so minimum value is 1 not 0. however the goTo takes value from 0...n  just seems the mismatch causes a bit confusion. one approach is to either remove the +1 from the returned step call so both the steps and goTo call takes values from 0 OR refactor code  handle goTo call with 1...n steps coming from User.

**Comment by elrumordelaluz** [comment]
Good point. Need to be checked all parts where `current` is needed.
