### ISSUE TITLE
Portal element defaults to body

### ISSUE THREAD

**Issue by pdparchitect** [elrumordelaluz/reactour#145]
There is no way to customise where the Portal will place the Tour element as no props are passed to it. This means that the element may get unstyled or styled differently if there are no default styles applied to the body but sub element.

The suggested fix is to pass `current` or any other prop name to `<Portal>`.

**Comment by elrumordelaluz** [comment]
Hi @pdparchitect, thanks for open the _Issue_.

Could you expand a little more the _Issue_? 
At the moment the `Portal` appends a `div#___reactour` to the `body`. Appreciate a lit if you expose your _use case_ where this behaviour doesn't work as expected.

Thanks!

**Comment by elrumordelaluz** [comment]
Closing to focus on _Issues_ with detailed info. Please re-open or open a new one in any case.
