### ISSUE TITLE
Position popup not correctly aligned when there are no navigation buttons

### ISSUE THREAD

**Issue by LuizzAugusto** [elrumordelaluz/reactour#146]
Hi. I found what I suspect is a bug when there are no navigation buttons. reactour is capable of adjusting the position automatically in every other configuration. I try 'position: center', but it doesn't work. If I readjust the size while tour is open it aligns.

**Comment by elrumordelaluz** [comment]
Hi @LuizzAugusto, thanks for open the _Issue_.

Are you referring when using `showNavigation={false}` and `showButtons={false}`.

[Here is a demo](https://v2l68.codesandbox.io/) using this `config` and setting `position: left|right|center` to prioritize positioning when space is available on the first 3 `steps`. [Here the editable version](https://codesandbox.io/embed/reactour-demo-template-live-v2l68)

In the following `.gif` you could see the _Helper_ without navigation buttons and positioning as each `step` declares: first `left`, second `right`, third `center.

![reactour](https://user-images.githubusercontent.com/784056/61279958-5fd29200-a7b7-11e9-806a-8d8df98134bf.gif)

Please let me know in any case,

**Comment by LuizzAugusto** [comment]
I tried 'position: left' and it has no effect. I forgot to mention, my test was simulating phone screens mainly.

**Comment by LuizzAugusto** [comment]
I tried 'position: left' and it has no effect. I forgot to mention, my test was simulating phone screens mainly and there is no navigation buttons because there is just one step.

**Comment by LuizzAugusto** [comment]
I tried 'position: left' and it has no effect. I forgot to mention, my test was simulating phone screens mainly and there is no navigation buttons because there is just one step.

**Comment by LuizzAugusto** [comment]
I tried 'position: left' and it has no effect. I forgot to mention, my test was simulating phone screens mainly and there is no navigation buttons because there is just one step.
![localhost_3000_(iPhone 6_7_8 Plus)](https://user-images.githubusercontent.com/22761133/61293714-b1c0eb00-a7aa-11e9-8120-d1560beb1f7c.png)

**Comment by elrumordelaluz** [comment]
@LuizzAugusto could you please share the _Tour_ config code or better create a reduced reproduction in a [codesandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js)?

**Comment by elrumordelaluz** [comment]
and keep in mind that the `position` prop on each `step` it isn't mandatory, that means that only will be positioned on the `left|righ` of the target element if there is available space enough to position it. The `center` and `[x,y]` values instead, put the _Helper_ in the middle or in s specific position of the _screen_.

**Comment by LuizzAugusto** [comment]
I tried to reproduce a minimal version of the code in codesandbox, but I can't reproduce the bug. Looking in chrome style, it doens't translate before screen update (it shows `transform: translate(161.96875px,436.6875px);` and when update shows `transform: translate(6px,343.8125px);`). Another condition for the bug it's the SignUp Button showing in the viewport (probably because the scroll). It happens in all screen sizes.

**Comment by LuizzAugusto** [comment]
The workaround is set root div to 1px width and then set a 25 miliseconds timeout to reset root width.

**Comment by atomoc** [comment]
Why is it marked completed?
