### ISSUE TITLE
Ability to export TourHooks?

### ISSUE THREAD

**Issue by darklightblue** [elrumordelaluz/reactour#147]
Hi, So I'm already using hooks on my end and I'm trying to update the steps externally by changing `goToStep` props -> However it seems that `componentWillReceiveProps` doesn't trigger on my end at all - I tried debugging it locally and it just doesn't seem to work.

So I want to use the TourHooks (coz it seems to work for the force change of step) without using it locally. 

Maybe something like 
```
import { TourHooks } from 'reactour';
```

Not sure if this is ok. Thank you. :)

**Comment by darklightblue** [comment]
As for my issue - I was able to fix it by using `startAt` and re-render the component (so it triggers componentDidMount` instead. 

So I guess I don't really need this anymore.

**Comment by elrumordelaluz** [comment]
no prob @darklightblue 
happy that you solved the _issue_.
However asap I want to move all the _Tour_ into `hooks`. Will let you know.
