### ISSUE TITLE
Class name for close button

### ISSUE THREAD

**Issue by thenathanjones** [elrumordelaluz/reactour#149]
Hi,

First off, thanks for this library. I have a small request, could there be a class added to the close button so I have a predictable way to find it? We have some automated tests and I currently dismiss it by finding the first button in the helper, but I'd like something that will be less susceptible to errors due to the content.

If you want, I'm happy to do a pull request for it, but I thought I'd ask first.

Cheers,
Nathan

**Comment by elrumordelaluz** [comment]
Hi @thenathanjones, thanks for open the _Issue_.

Absolutely valid request, and pretty happy to review your PR.

Thanks in adavnce!

**Comment by gdsrosa** [comment]
This issue is under development? Or can I attack her? 😉

**Comment by thenathanjones** [comment]
Hasn't gotten to the top of my list sadly. Have at it! ☺️
