### ISSUE TITLE
Is there a way to fix the tour pop up to the bottom of the screen?

### ISSUE THREAD

**Issue by RobertGary1** [elrumordelaluz/reactour#150]
Some are concerned that the popup with this buttons are moving all over the screen and users feel they have to chase it. The ask is that it just be fixed at the bottom of the screen at all time regardless of the location of the item highlighted. Have you seen this ask before? I assume this would be an enhancement.

**Comment by elrumordelaluz** [comment]
Hi @RobertGary1, thanks for open the _Issue_.

At the moment you have the `position` prop on each `step` that accept a non-mandatory position to prefer if there is available space: `left` or `right`. In case you preffer `center` would position the _Helper_ in the center of _viewport_. You could also pass `x,y` values (which you could also calculate to match your _bottom_ position.

However I think is an absolutely valid enhacement request to let the _Tour_ make the calculations in case you set a specific position like `fixed-bottom` or something like this.

Lets' leave that idea to start working on it. In the meantime you have the _string_ options (left, right, center) or the `x,y` fixed position.

**Comment by elrumordelaluz** [comment]
closing, since is doable in `v2`. [Docs](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour)

**Comment by dreamid27** [comment]
> closing, since is doable in `v2`. [Docs](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour)

@elrumordelaluz I'm sorry, i opened this. because this is not solved.

can you give example how to do that in v2 ? I can't get any documentation to do  fixed potition/

**Comment by elrumordelaluz** [comment]
You can do something like:


```js
 <TourProvider
   steps={steps}
   styles={{
     popover: (base) => ({
       ...base,
       bottom: "1rem",
       right: "1rem",
       left: "auto",
       top: "auto",
       transform: "none",
     }),
   }}
 />
```

[Here](https://codesandbox.io/p/sandbox/vibrant-goldberg-9s75hp?workspaceId=d48a09c0-267b-4a7c-9be6-4b62794d0f15) is a working example.

**Comment by dreamid27** [comment]
> Docs

Cool man, thank you
