### ISSUE TITLE
 Focus to the section

### ISSUE THREAD

**Issue by AngeelRdz** [elrumordelaluz/reactour#153]
Hello good afternoon .. I am having problems with the focus of a section that is at the bottom of the screen, it does not make me scroll to the section.

https://drive.google.com/open?id=1Vvvf-PKDq3ISKJ_R3Qiks55Y4W06prC4

**Comment by elrumordelaluz** [comment]
Hi @AngeelRdz, thanks for open the _Issue_.

I can't open what you are trying to share.

**Comment by AngeelRdz** [comment]
Hello @elrumordelaluz, Ready ... excuse me!!

**Comment by elrumordelaluz** [comment]
Should be useful if you could create a reduced reproduction in a [sandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js).

Seems similar to #141

**Comment by AngeelRdz** [comment]
Good day! @elrumordelaluz  
In fact, I already reviewed the similar case you told me and managed to make the displacement that was there. Thank you

**Comment by elrumordelaluz** [comment]
Cool, does that solved the _Issue_?

**Comment by AngeelRdz** [comment]
Hello, if it could be resolved ... really thank you very much!
