### ISSUE TITLE
EmotionJS with Reactour

### ISSUE THREAD

**Issue by aqarain** [elrumordelaluz/reactour#156]
How can I use EmotionJS with Reactour?

**Comment by elrumordelaluz** [comment]
Hi @aqarain, thanks for open the _Issue_.

Now `reactour` uses `styled-components` internally to compute _Helper_ and _Mask_ position values and related.

There are [two](#100) [issues](#132) where people asks the possibility to _inject_ a specific styled library, specially those that expose `styled` like _Emotion_, _Glamorous_ and so on…

At the moment I didn't go deeper in that way, however open to new ideas or PR!

**Comment by elrumordelaluz** [comment]
Emotion is now used by `v2`, try `npm i @reactour/tour` and refer to docs [here](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour)
