### ISSUE TITLE
Can we have two react tour steps in one? also is it possible to style the main component?

### ISSUE THREAD

**Issue by vinikatyal** [elrumordelaluz/reactour#157]

**Comment by elrumordelaluz** [comment]
Hi @vinikatyal, thanks for open the _Issue_.

> Can we have two react tour steps in one?

Can you elaborate a little to understand what you mean by _two steps in one_?

> also is it possible to style the main component?

Yup, you could pass a [`CustomHelper` prop](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L62). [Here](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L69-L124) is the example in the [Demo](https://reactour.js.org/) (try to switch _Components_ by pressing `enter`)

**Comment by vinikatyal** [comment]
<img width="352" alt="Screen Shot 2019-08-07 at 7 54 10 PM" src="https://user-images.githubusercontent.com/5568656/62630748-2c65cc00-b94d-11e9-99eb-93d992ce73b9.png">

**Comment by vinikatyal** [comment]
@elrumordelaluz some thing like above

**Comment by elrumordelaluz** [comment]
interesting, keeping it as a _fetured request_, thanks!
