### ISSUE TITLE
showButtons can't work in Typescript

### ISSUE THREAD

**Issue by PabloGracia** [elrumordelaluz/reactour#158]
Hi, 

I realized while trying to use the Tour with typescript that the 'showButtons' prop cannot be used, as it is defined in the declaration file as 'showButton' instead of 'showButtons' (it is missing the trailing "s"). I've fixed it and submit a merge request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37438

It's my first pull/merge request so please provide me with some feedback if I did something wrong that I can improve for the next time. 

Thanks for your great package!

**Comment by elrumordelaluz** [comment]
Thank you @PabloGracia!
