### ISSUE TITLE
Scroll in CoreUI admin template.

### ISSUE THREAD

**Issue by kid-three** [elrumordelaluz/reactour#160]
I am trying to get Reactour to work correctly withing [Core-UI React](https://github.com/coreui/coreui-free-react-admin-template) but I am having issues with scrolling.

I have set up a sandbox to show the issue: https://codesandbox.io/s/coreuicoreui-free-react-admin-template-r34qz

The start tour button at the topmost starts the reactour, you can navigate with arrow keys

The tour starts correctly, but when it goes to the next step that is outside of view, it draws the tour component out of the screen.

If you scroll a bit and navigate with the keys, you see that the tour actually works somewhat.

Im not sure if this is an issue with the overall structrue of Core-UI.

I've tried putting the 'Tour' components in the App.js file, as well as inside the 'Dashboard' components completely, but it has the same exact behaviour.

I have discovered that what actually scrolls is the body element, and not the individual divs inside.

Any help would be greatly appreciated

**Comment by elrumordelaluz** [comment]
Hi @kid-three, thanks for open the _Issue_.

I'm not able to access the sandbox. Can you give an eye so then I'll check again? thanks!

<img width="1552" alt="Screenshot 2019-08-08 at 22 18 24" src="https://user-images.githubusercontent.com/784056/62735000-85eff880-ba2a-11e9-92ef-ddd10745ebe7.png">

**Comment by kid-three** [comment]
@elrumordelaluz For some reason this sandbox does not work correctly in **Firefox** . It works correctly in Chrome or Chromium.  I think it has to do with the way that online VSCode works.

Tested in Mac and Ubutnu, only Chrome works :(

**Comment by elrumordelaluz** [comment]
hey @kid-three the problem is related on the container elements of those `steps` that the _Tour_ doesn't scroll to, which have declared `overflow-x: hidden`, property that creates a scrollable container. Look how it works disabling those two lines of `css`.

![coreUI](https://user-images.githubusercontent.com/784056/62761207-51aa2580-ba86-11e9-85e2-dea1a33c7f96.gif)

Let me know in any case,

**Comment by kid-three** [comment]
Wow man, you have no idea how many times I went over all the scroll-overflows. I had to set them to *unset* for it to work.

You go far beyond the usual to help people out. I will recommend your product many people.

Mil gracias por tu ayuda, te debo una chela desde Mexico!

**Comment by elrumordelaluz** [comment]
No hay problema @kid-three, gracias a vos por usar `reactour`!

**Comment by developdeez** [comment]
Can this be made to work on a page with html,body: overflow-x hidden?

**Comment by elrumordelaluz** [comment]
@developdeez can you create a minimal test in a [sandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js) to test what you are asking?

**Comment by sureshreddysolipuran** [comment]
dint find any overflow-x:hidden still i am facing same issue

**Comment by elrumordelaluz** [comment]
@sureshreddysolipuran do you have a _link_ or could you create a minimal reproduction of the _Issue_?
