### ISSUE TITLE
 Navigation between screens

### ISSUE THREAD

**Issue by AngeelRdz** [elrumordelaluz/reactour#161]
Hello again @elrumordelaluz 
A question regarding this topic: https://codesandbox.io/s/myry48155p is there any other way to do it ?? Is that my index occupy it in a different way (like the image that I attached)

https://drive.google.com/drive/folders/18ml0ntlUEqO6OR7zqkGHjygFKQrZrasM

**Comment by elrumordelaluz** [comment]
Hi @AngeelRdz, again I cant view what you are sharing.

**Comment by AngeelRdz** [comment]
Ready .. excuse me!!

**Comment by elrumordelaluz** [comment]
Stills private, asks me to log in to _Gmail_

**Comment by AngeelRdz** [comment]
Good afternoon @elrumordelaluz 
Let's see, try this league ... it shouldn't give you problems to visualize it, again an apology.

https://drive.google.com/file/d/1ZP_VABLuEDS2zJBUs-ff2OslqdhJSETZ/view?usp=sharing

**Comment by elrumordelaluz** [comment]
Sorry @AngeelRdz, could you expand a little what is the issue? thanks!

**Comment by elrumordelaluz** [comment]
Look that in the example we are using the `withRouter` HoC, I think is not necessary to have all the stuff in `index.js` is just for the example demo.
