### ISSUE TITLE
Rounded "Mask hole"/"Target"

### ISSUE THREAD

**Issue by darklightblue** [elrumordelaluz/reactour#162]
Hi, So I was trying to have a rounded clip mask and not square.

I tried adding `rounded` property but it seems that its not what I'm expecting (it actually doesn't make the target component mask round but only the half of it) - I tried changing the `rounded` prop on the demo code into `50` and this is what happens:

![image](https://user-images.githubusercontent.com/9190133/62946442-47d04b80-be13-11e9-82ea-75a8c96e9611.png)

(also found this issue: https://github.com/elrumordelaluz/reactour/issues/116). 

Is there any other way to achieve this? Thank you for this great library btw!

**Comment by anevaude** [comment]
Also would love to know if I can add a colored 1px border to the target area.

**Comment by krishna-fenixwork** [comment]
Hey, @elrumordelaluz @darklightblue Are you guys able to add the border around the mask area? Actually, I just started with this, and I would love to know is there any possibility to add the border around the mast area. 

![image](https://user-images.githubusercontent.com/78067517/236496624-c2f70d8b-6a91-4d2f-aa06-71bbfd76229f.png)

**Comment by elrumordelaluz** [comment]
@krishna-fenixwork please play with [this sandbox](https://codesandbox.io/s/naughty-sea-51vsuz?file=/App.js), you can control all the styling through [styles prop](https://github.com/elrumordelaluz/reactour/tree/main/packages/tour#styles-stylesobj--popoverstylesobj--maskstylesobj-1), doing something like this:

```js
 <TourProvider
  steps={steps}
  styles={{
    maskArea: (base) => ({ ...base, rx: 5 }),
    highlightedArea: (base, { x, y, width, height }) => ({
      ...base,
      display: "block",
      stroke: "#f00",
      strokeWidth: 4,
      width: width + 14,
      height: height + 14,
      rx: 10,
      x: x - 7,
      y: y - 7,
      pointerEvents: "none"
    })
  }}
/>
```

**Comment by krishna-fenixwork** [comment]
@elrumordelaluz Thanks for the response! It worked as I expected. Thanks

**Comment by elrumordelaluz** [comment]
Try using [onClickMask](https://github.com/elrumordelaluz/reactour/tree/main/packages/tour#onclickmask-clickprops-clickprops--void), something like [this](https://codesandbox.io/s/youthful-river-x2nq5b):

```js
<TourProvider steps={steps} onClickMask={() => {}} />
```
