### ISSUE TITLE
skip Step if node not found instead of rendering at center

### ISSUE THREAD

**Issue by jasan-s** [elrumordelaluz/reactour#163]
currently default behavior is to render step vertically & horizontally center if node is not found. I'm curious to why this was chosen as default behavior. I feel if element node cant be found the step would generally have no value. I was thinking of making some change like below if certain prop(i.e `skipStepsIfNotFound` or step level prop `skipIfNotFound`) is passed down
```
...
    const {skipStepsIfNotFound} = this.props
    const skipIfNotFound =
      typeof step.skipIfNotFound === 'boolean'
        ? step.skipIfNotFound
        : typeof skipStepsIfNotFound === 'boolean'
        ? skipStepsIfNotFound
        : false

    const missingNodeWarning = () => {
      step.selector &&
        process.env.NODE_ENV === 'development' &&
        console.warn(
          `Can't find the DOM node '${step.selector}'. Please check the 'steps' Tour prop Array at position ${current}.`
        )
    }

    if (node) {
      const cb = () => stepCallback(node)
      this.calculateNode(node, step.position, cb)
    } else if (!node && skipIfNotFound) {
      missingNodeWarning()
      const { steps, onRequestClose } = this.props
      const nextStep = current + 1
      if (nextStep > steps.length - 1) {
        onRequestClose()
      } else {
        this.gotoStep(nextStep)
      }
    } else {
      this.setState(
        setNodeState(null, this.helper.current, step.position),
        stepCallback
      )
      missingNodeWarning()
    }
...

```

**Comment by JonathanFu** [comment]
I think this is a good suggestion.

**Comment by Param-Harrison** [comment]
This should be the default behaviour

**Comment by ps1223** [comment]
Can this be made as the default behavior?

**Comment by geekyogurt** [comment]
Is there a version where this is the default behaviour?

**Comment by yairEO** [comment]
Autho - please fix this ASAP as complex media queries can hide some elements or completely remove elements and all this is for responsive design where different viewport sizes show different elements, which is something very basic in the web

**Comment by yairEO** [comment]
Ok people, I've created a filter myself for non-existing selectors (only for steps' `selector` properties which aren't empty)

```js
const onScreenSteps = steps.filter(({ selector }) => {
    const isMounted = selector === ''
      ? true
      : document.querySelector(selector)
        ? !!document.querySelector(selector).clientWidth
        : false

    return isMounted
})
```

**Comment by s-pcode** [comment]
> Ok people, I've created a filter myself for non-existing selectors (only for steps' `selector` properties which aren't empty)
> 
> ```js
> const onScreenSteps = steps.filter(({ selector }) => 
>     selector === ''
>       ? true
>       : document.querySelector(selector)
>         ? !!document.querySelector(selector).clientWidth
>         : false
> )
> ```

I'm looking for this same feature. I'm confused how to use this solution @yairEO ?

Is there any better approach to solve this in v2 @elrumordelaluz ?

Any kind of help is welcome, I'm stuck since long to implement this.
Thanks 👍

**Comment by elrumordelaluz** [comment]
@s-pcode you can use the same snippet using `v2` using [setSteps](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#setsteps-dispatchreactsetstateactionsteptype).

[Here](https://codesandbox.io/s/reactour-tour-demo-using-react-router-dom-forked-k2ms16?file=/components/Main.js) is a working example.
