### ISSUE TITLE
Focus Fighting with Material-UI

### ISSUE THREAD

**Issue by denchp** [elrumordelaluz/reactour#165]
I'm not using any of the Material-UI Modal components.  However, when running the tour - I end up with some focus fighting error messages:

FocusLock: focus-fighting detected. Only one focus management system could be active. See https://github.com/theKashey/focus-lock/#focus-fighting

**Comment by hmehta051** [comment]
i am using Mui Modal and facing same error message FocusLock: focus-fighting detected. Only one focus management system could be active. how to solve

**Comment by elrumordelaluz** [comment]
> i am using Mui Modal and facing same error message FocusLock: focus-fighting detected. Only one focus management system could be active. how to solve

what version of Reactour are you using?

**Comment by hmehta051** [comment]
"react": "^18.2.0",

**Comment by elrumordelaluz** [comment]
> "react": "^18.2.0",

and what `@reactour/tour` version?

**Comment by hmehta051** [comment]
i am not using this

**Comment by andresmv94** [comment]
> > "react": "^18.2.0",
> 
> and what `@reactour/tour` version?

same for me in "reactour": "^1.19.0"

**Comment by marouanechoukri31** [comment]
@elrumordelaluz Hi ! I have the same probleme, I'm using "reactour": "^1.19.1".
