### ISSUE TITLE
Assigning different steps to dynamic Elements

### ISSUE THREAD

**Issue by aqarain** [elrumordelaluz/reactour#166]
We can easily assign a selector to a div like in the example below:

```
let steps = [{ selector: ".header", content: "This is the Header" },
			 { selector: ".footer", content: "This is the Footer" }
			];

<div className="header"> Header </div>
<div className="footer"> Footer </div>
```

BUT, for the same steps, if the divs are being generated dynamically, how can we assign a selector to each <div>. For e.g.

```
let arr = ['Header', 'Footer'];
arr.map(name => (<div> name </div>))
```

In this scenario, how will we assign two selectors to divs?

**Comment by elrumordelaluz** [comment]
You must generate the `steps` also dinamically.

**Comment by aqarain** [comment]
@elrumordelaluz this was just an example. I solved it btw :)

**Comment by elrumordelaluz** [comment]
Awesome! Mind share some words to be helpful for others in similar situations?

**Comment by aqarain** [comment]
Simply use ternary operator. As in my case there are 2 steps only so:

`<div className={name === 'Header' ? '.header' : '.footer'}> name </div>`
