### ISSUE TITLE
Reactour closes on route change

### ISSUE THREAD

**Issue by aqarain** [elrumordelaluz/reactour#168]
Reactour closes on route change. What could be the possible reason? Is it good to have separate reactours for separate route in continuation? For e.g. One tour starts at Component A and when user click Next, the route changes to Component B. When user is on Component B, another reactour should start.

**Comment by elrumordelaluz** [comment]
The _Tour_ closes probably because is unmounted when switching _Component_. 
In [this example](https://codesandbox.io/s/myry48155p) the _Tour_ persists even when routes changes. Keep an eye and let me know.
