### ISSUE TITLE
Add delay in showing the guided tour card after 

### ISSUE THREAD

**Issue by aqarain** [elrumordelaluz/reactour#169]
My scenario is when I go from route A to route B, an API gets called and the rendering of data takes a little time on that "view B" but the guided tour card shows up instantly and it shows up at the wrong place.
Can you please suggest how to overcome that problem?

I have tried the below:
```
update=currentPath
updateDelay=1000
```

where currentPath is an observable which changes when user switches from route A to route B

**Comment by elrumordelaluz** [comment]
keep in mind to `update` also when the rendering data come, not only the `path`.

**Comment by aqarain** [comment]
Please correct me if I am wrong. Lets say I am fetching data from api and storing it in a mobx observable, apiResponse, which is getting rendered. I should do something like this:

`update={apiResponse}`

Right?

**Comment by elrumordelaluz** [comment]
right!

**Comment by RobertGary1** [comment]
How do you change the update value for each step?

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
