### ISSUE TITLE
Module not found: Can't resolve 'styled-components'

### ISSUE THREAD

**Issue by Baspa** [elrumordelaluz/reactour#175]
When installing the package and trying to compile it returns the following error:

> ./node_modules/reactour/dist/reactour.esm.js
> Module not found: Can't resolve 'styled-components'

**Comment by ehdwns980416** [comment]
How did you solve it?

**Comment by Ehsan-Home** [comment]
I am getting the same error. Anyone has any idea how to resolve it? 
Thanks.

**Comment by elrumordelaluz** [comment]
weird, is `styled-components` installed?

```
npm ls styled-components
```

**Comment by Ehsan-Home** [comment]
No its not installed. 
I know by installing styled-component, the issue gets resolved. However, my question is why we need to install styled-components? 

Thanks in advanced 👍🏻

**Comment by elrumordelaluz** [comment]
`styled-components` is a [peerDependency](https://github.com/elrumordelaluz/reactour/blob/master/package.json#L81) of this project, having the role of make all the css calculations and styling.
