### ISSUE TITLE
Can't edit form fields while disableInteraction is set to 'false'

### ISSUE THREAD

**Issue by Baspa** [elrumordelaluz/reactour#176]
I would like to be able to fill in a form while I am doing the tour. Currently the prop `disableInteraction` is set to `false`. I am able to click on a checkbox but I can't fill in textboxes. Any idea on how I might fix this?

**Comment by CharlotteArai** [comment]
@Baspa Hi! Did you find a solution to this problem? I am struggling with the same issue :)

**Comment by Baspa** [comment]
> @Baspa Hi! Did you find a solution to this problem? I am struggling with the same issue :)

No sorry I didn't manage to find a solution yet. I'll post it here if I might find a solution.

**Comment by Riley-Brown** [comment]
I had a similar issue for a modal popup, I fixed it by adding this to the form step
 `action: node => node.focus()`

**Comment by Baspa** [comment]
@Riley-Brown Your solution worked for me, thank you!
