### ISSUE TITLE
This is an amazing project!

### ISSUE THREAD

**Issue by imbhargav5** [elrumordelaluz/reactour#178]
Hi reactour team, just wanted to drop by and congratulate you on a project that is shaping up so well. I was checking through the dependents of `@rooks/use-mutation-observer` (a package that I made and maintain) and stumbled upon this project and it just caught my eye as very beautiful and well made project.

Good luck!
:)

**Comment by elrumordelaluz** [comment]
Hey @imbhargav5 thanks for the kind words, and for the amazing `use-mutation-observer`. At the moment is only used in _development_ but in the next days (maybe also today) will be published as a `major` new version where all `reactour` uses `hook` and requires a _React_ version bump.
