### ISSUE TITLE
TourPortal crashes the app after being unmounted while open

### ISSUE THREAD

**Issue by hon2a** [elrumordelaluz/reactour#18]
### Scenario

* Use `Tour` by conditionally rendering it rather than using `isOpen`. I.e. switch between rendering it with `isOpen={true}` and not rendering it at all. _(Rationale: This is the default way to use React components, so it should be supported.)_
* Open the tour and close it.
* Remove one of the elements highlighted by the tour from the DOM.

### Expected

It works :)

### Actual

App crashes with `TypeError: Can't get 'getBoundingClientRect' of undefined.` or some such.

**Comment by elrumordelaluz** [comment]
Thanks @hon2a!
