### ISSUE TITLE
Include tabindex="-1" in all components

### ISSUE THREAD

**Issue by brunomonteirosud** [elrumordelaluz/reactour#185]
Hi there!

I noticed that the `<Tour />` component has a `tabindex="-1"` attribute, but not the buttons and other control components. The issue this is creating for me is: if I updated the state in a parent component and that causes a re-render in the child component, then the `tabindex` behavior in the child component get messed up.

I created a reproducible scenario [here](https://codesandbox.io/s/xenodochial-golick-wpy3r) and I even opened a StackOverflow [question ](https://stackoverflow.com/questions/58020159/reactour-and-focus-issues-on-re-render)about it, before realizing what the issue was.

Right now, my solution was to include this piece of code when the Tour opens:

```javascript
setTimeout(() => {
    const elements = document.querySelectorAll("div[data-focus-lock-disabled] button");
    elements.forEach(el => el.tabIndex = "-1")
}, 100);
```

But it would be nice if the Tour components already had `tabindex="-1"` as default.

I am happy to go over the code and open a Pull Request for that, if necessary.

Thank you and congrats on the amazing library!

**Comment by elrumordelaluz** [comment]
Hi @brunomonteirosud, thanks for open the _Issue_.

Seems to be an _issue_ with `focuslock` which is used to retain _focus_ inside the _Helper_ Component. Related #165 

A possible solution is to have a `flag` to disable `focuslock`. Let me investigate.

**Comment by bellsml** [comment]
@elrumordelaluz 
> A possible solution is to have a flag to disable focuslock. Let me investigate and feel absolutely free to open a PR.

has there been progress in implementing the flag to disable focuslock?

**Comment by seschwartz8** [comment]
@elrumordelaluz

A possible solution is to have a flag to disable focuslock. Let me investigate and feel absolutely free to open a PR.

#234
