### ISSUE TITLE
Elements are fully not brought into view on certain screen sizes.

### ISSUE THREAD

**Issue by kid-three** [elrumordelaluz/reactour#186]
I found this issue on my app, and as well on the demo.

On certain screen sizes, smaller than 1080 pixels in height, elements that are bigger then half the screen height are not brought completely into view, a small part of the bottom is left outside of the view.

Example **Step # **5**** in the demo page [https://reactour.js.org/](url)
![image](https://user-images.githubusercontent.com/32473931/65360373-50136780-dbc5-11e9-8a27-85bc1177bf43.png)
**Screen size 1366 x 768**

Same step, same browser bigger screen size 1920x1080
![image](https://user-images.githubusercontent.com/32473931/65360418-7e914280-dbc5-11e9-80e8-5d226236f059.png)

These screenshots were taken by going through the tour step by step, starting from the first one at the top of the page.

Same behavior on Chrome and Firefox.

I found this out while testing on a laptop that is not 1080p, but 1366 x 768. It can be replicated by simply resizing the window in a 1080p screen to something smaller.

On my app its a graph inside a card where the entire bottom is cut off. 
![image](https://user-images.githubusercontent.com/32473931/65361147-1abc4900-dbc8-11e9-9c4a-87d997eb1381.png)

If I move to the next few steps and then move back, the whole component is now in view completely
![image](https://user-images.githubusercontent.com/32473931/65361173-34f62700-dbc8-11e9-898d-6f08522a86b2.png)

As you can see, its the same behavior as in the demo page. 

The screen sizes are from budget laptops and WXGA projectors used in a lot of businesses. 

Not sure what can be done here to mitigate this issue.

Thanks in advance for your time,

Kid-three

**Comment by elrumordelaluz** [comment]
Hi @kid-three, thanks for open the _Issue_.

Solved in `reactour@1.15.2`

**Comment by rdmclin2** [comment]
+1
