### ISSUE TITLE
How can I detect the direction of card to highlighted element?

### ISSUE THREAD

**Issue by aqarain** [elrumordelaluz/reactour#187]
How can I detect the position of card relative to the highlighted element? For e.g. in the image below, the position of card is at **"TOP"** relative to highlighted element. How can I detect that position?

![Screenshot from 2019-09-25 17-46-40](https://user-images.githubusercontent.com/20900424/65602192-e75d2e00-dfbc-11e9-9322-100f2560301b.png)

**Comment by elrumordelaluz** [comment]
Hi @aqarain, I missed your _Issue_, I'm sorry. Re opening since is an interesting thing to consider to return the end-user. 

The calculation checks if there is enough space available to put the _Helper_. Let me check if it's easy to return that calculation result.

**Comment by elrumordelaluz** [comment]
Solve in `v2`. I am closing this _issue_, but feel free to re-open or create a new one in any case.
