### ISSUE TITLE
TypeError: Cannot read property 'stepInteraction' of undefined

### ISSUE THREAD

**Issue by LuizzAugusto** [elrumordelaluz/reactour#189]
Hi,  I'm just using reactour 1.15.0, and in a specific situation It's generating this error: "TypeError: Cannot read property 'stepInteraction' of undefined". I tried to update to 1.15.2, but the error occurs in places it doesnt' happen before.

**Comment by elrumordelaluz** [comment]
Hi @LuizzAugusto, thanks for open the _Issue_. 

Could you please share a little more information? Did you tried in a [codesandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js).

Waiting for any update.

**Comment by LuizzAugusto** [comment]
The error is in file reactour.esm.js, line 1128, (v1.15.0):
`1128 | }, _defineProperty(_React$createElement, "className", maskClassName), _defineProperty(_React$createElement, "disableInteraction", steps[current].stepInteraction === false || disableInteraction ? !steps[current].stepInteraction : disableInteraction), _defineProperty(_React$createElement, "disableInteractionClassName", "".concat(CN.mask.disableInteraction, " ").concat(highlightedMaskClassName)), _React$createElement)), React.createElement(FocusLock, {`
It seems like it doesn't found the step.

**Comment by LuizzAugusto** [comment]
I not attached my code with a url.
