### ISSUE TITLE
not centering on first popup 

### ISSUE THREAD

**Issue by mx2323** [elrumordelaluz/reactour#191]
im running reactour in my electron app and on first pop-up the position appears to be incorrectly calculated. 

![image](https://user-images.githubusercontent.com/528124/66428061-538b5900-e9e3-11e9-8cbf-521ca58c87b3.png)

it appears to fix itself when i resize the window, or toggle steps. 

running reactour 1.15.2

**Comment by mx2323** [comment]
interestingly, it appears to work if the tour is open when the page was first loaded. 

but if i change the tour to start closed and toggle it open later it is not correctly positioned.

**Comment by mx2323** [comment]
downgraded to 1.15.0 and it seems to be working correctly again.

**Comment by elrumordelaluz** [comment]
Should be solved in `reactour@1.15.3`

**Comment by mehdichitforoosh** [comment]
Hi,
I have this problem in 1.18.0 version.
![Screenshot from 2021-01-12 21-31-35](https://user-images.githubusercontent.com/9556642/104354053-e471ae00-551d-11eb-908a-06747c1acad5.jpg)
