### ISSUE TITLE
Not scrolling into view

### ISSUE THREAD

**Issue by nvoisin** [elrumordelaluz/reactour#192]
Hi,

We just added reactour to our website and we seem to get a problem some users have been experiencing here: when out of view, scrolling won't work. I've looked at issue #26 but the answer is quite vague (concerns an overflow on the body). We've tried to remove as many overflow properties, to no avail.
I've also seen this issue on stackoverflow [here](https://stackoverflow.com/questions/57417050/getting-reactour-to-scroll-within-coreui) where there's the exact same problem.

Help ?

Thanks

**Comment by elrumordelaluz** [comment]
Hi @nvoisin, thanks for open the _Issue_.

Could you please share a reduced reproduction in a [codesandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js), otherwise if you have a public link to share and try to analyse what could be happen.

**Comment by nvoisin** [comment]
Hi,

There's one in the stackoverflow link : https://codesandbox.io/s/coreuicoreui-free-react-admin-template-r34qz.

Otherwise you can head over to our website : https://app.financialnode.com. Click on "Try The Demo" if you don't want to create an account and see for yourself.

**Comment by elrumordelaluz** [comment]
hey @nvoisin, thanks for share the _demo_.

On my end, _disabling_ the `overflow-x: hidden` on `div.utils__content` works as expected.

![github](https://user-images.githubusercontent.com/784056/66582267-c7636800-eb81-11e9-8eb0-c2bd93f11e68.gif)

**Comment by nvoisin** [comment]
Thanks @elrumordelaluz ! I owe you a cup of coffee !

**Comment by elrumordelaluz** [comment]
Cool @nvoisin, closing the _Issue_. Feel free to re-open in case you need.
