### ISSUE TITLE
Mobile Tour

### ISSUE THREAD

**Issue by developdeez** [elrumordelaluz/reactour#193]
Hi. Is there a way to change the style for mobile? It's very hard to click the small arrows on a mobile phone. All sites are more likely to be visited on mobile so there should be something to compensate IMO.

**Comment by kylesierens** [comment]
I also find that there could be some better calculations on where to place the card for mobile scenarios. It often seems to default to center, and entirely covers the showcased element. I'd be willing to try and help with this.

**Comment by elrumordelaluz** [comment]
Mind testing with `v2` where all components and styles are pretty customizable. 
I am closing this _issue_, but feel free to re-open or create a new one in any case.
