### ISSUE TITLE
Using expired functions ：componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by cxy-coder** [elrumordelaluz/reactour#195]
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Tour

**Comment by elrumordelaluz** [comment]
Hi @cxy-coder, thanks for open the _Issue_.

Closing since will be solved in next major version (see `master`) which will use `hooks`.

**Comment by vhflat** [comment]
@elrumordelaluz when will this be released?

**Comment by thomassiew** [comment]
Looking forward to the release too. any date of release?

**Comment by bogdancss** [comment]
has this been released? still getting the warning

**Comment by eduqg** [comment]
@elrumordelaluz Some news about this issue?

**Comment by wonjun27** [comment]
I also noticed this isn't fixed in v1.16.0 release.

**Comment by elrumordelaluz** [comment]
`reactour@1.16.1` should be landed without those _warnings_ using `UNSAFE_*` until the next major release.

**Comment by danielpox** [comment]
> `reactour@1.16.1` should be landed without those _warnings_ using `UNSAFE_*` until the next major release.

I'm using `react@17.0.1` and seeing errors regarding the usage of `UNSAFE_*`. We're in `reactour@1.18.0` now and it still isn't fixed. When will it shift to hooks?

**Comment by DavidQuartz** [comment]
This issue is still not fixed in ```reactour@1.18.4```
