### ISSUE TITLE
es-abstract-1.14.0.tgz: Request failed "404 Not Found"

### ISSUE THREAD

**Issue by nelsonwong1012** [elrumordelaluz/reactour#196]
Getting this when doing `yarn install`:
```
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/es-abstract/-/es-abstract-1.14.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/nwong/dev/reactour/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The "Versions" tab in https://www.npmjs.com/package/es-abstract does not have `1.14.0`. Can we get this upgraded to `1.16.0` (latest) or at least a version that exists on NPM?

**Comment by elrumordelaluz** [comment]
Hey @nelsonwong1012, could you please try using `reactour@1.15.4`?

**Comment by nelsonwong1012** [comment]
@elrumordelaluz Still getting the same error after updating.

**Comment by elrumordelaluz** [comment]
Could you please share the _steps_ to reproduce the _issue_?
I am not having issues installing `reactour` in an _App_ on my end.

**Comment by nelsonwong1012** [comment]
I'm gettin this error while doing `yarn install` (or `yarn`) in the reactour directory/project itself. Hopefully, the steps are clear from the following:
```
➜  reactour git:(master) git pull
Already up-to-date.
➜  reactour git:(master) yarn install
yarn install v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/es-abstract/-/es-abstract-1.14.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/nwong/dev/reactour/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
➜  reactour git:(master) ✗
```

**Comment by elrumordelaluz** [comment]
could you try removing `node_modules` and `yarn.lock` and launch `yarn` again?

**Comment by nelsonwong1012** [comment]
I had removed `node_modules` previously and it didn't work. Removing both `node_modules` and `yarn.lock` did the trick. But now I have diffs with the master branch.

**Comment by elrumordelaluz** [comment]
oh, got it. you have to base on `v1` branch


On 23 Oct 2019, at 22:22, Nelson Wong <notifications@github.com<mailto:notifications@github.com>> wrote:


I had removed node_modules previously and it didn't work. Removing both node_modules and yarn.lock did the trick. But now I have diffs with the master branch.

**Comment by elrumordelaluz** [comment]
Closing, feel free to re-open  or open a new _issue_ in any case.
