### ISSUE TITLE
Prev and next button text should be customizable

### ISSUE THREAD

**Issue by belgac** [elrumordelaluz/reactour#2]
Hello,

if the user language is not english the text of the prev and next navigation buttons should be customizable.

I already prepared a pull request ;)

Thank you for this awesome library.

**Comment by elrumordelaluz** [comment]
yup! yes absolutely agree, thanks for the catch up.

**Comment by elrumordelaluz** [comment]
Published [here](https://github.com/elrumordelaluz/reactour/releases/tag/v1.2.0), thanks for the contrib!
