### ISSUE TITLE
Running this library I get `TypeError: node is undefined`

### ISSUE THREAD

**Issue by rootux** [elrumordelaluz/reactour#200]
TypeError: node is undefined
getNodeRect
node_modules/reactour/dist/helpers.js:17

  14 | }

  15 | 
  16 | var getNodeRect = function getNodeRect(node) {
> 17 |   return (0, _lodash.default)(node.getBoundingClientRect(), ['top', 'right', 'bottom', 'left', 'width', 'height']);
  18 | };
  19 | 
  20 | exports.getNodeRect = getNodeRect;

Here is my full component - 
```
class TourDoocrate extends Component {
  constructor(props) {
    super(props);

    this.steps = [
    {
      selector: '[data-tour="first"]',
      content: "testing",
    }];
  }

  render() {
  return(
      <Tour
        steps={this.steps}
        isOpen={this.props.isTourOpen}
        onRequestClose={this.props.onCloseTour}/>
    );
  }
}
```

I'm on `React 16`

**Comment by rootux** [comment]
Apperantly it's really important to set the helper `className` 
Such as:
```
<Tour
        steps={this.steps}
        isOpen={true}
        className={"tour-doocrate-helper"}
        onRequestClose={this.props.onCloseTour}/>
```

**Comment by elrumordelaluz** [comment]
Hi @rootux, thanks for open the _Issue_. 
Since you already closed the _issue_, I think you solved.
I that case, could you share the solution and if possible a sandbox with the error, I can't reproduce to help others having similar _issues_ in case.

Thanks in advance,
