### ISSUE TITLE
Position prop is being ignored

### ISSUE THREAD

**Issue by adamsoffer** [elrumordelaluz/reactour#205]
Using `position: 'bottom'` or any of the other position strings doesn't seem to do anything.

**Comment by ankmathur96** [comment]
+1 @elrumordelaluz do you have any suggestions for this? The tour element seems to be ignoring my position argument when it's in the form "bottom"/"top", etc. The array works, but I'd rather not compute the viewport size

**Comment by clarkd** [comment]
Seeing the same here

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
If still relevant, please consider create a minimal reproduction in a sandbox, thanks!
