### ISSUE TITLE
Master branch fixes

### ISSUE THREAD

**Issue by tarqu1n** [elrumordelaluz/reactour#206]
There was some functionality that I wanted to use, primarily the ability to delay the execution of a step and trigger functionality prior to a step. This lead me to your master branch, I appreciate it is a work in progress but i wanted to feed back the few minor updates I needed to make to get it suitable for my use.

Fork and branch can be found here:
https://github.com/tarqu1n/reactour/tree/temp-bug-fixes

Changes
* Fixed functionality that starts the tour at a specific step - [6deb977e0145c5c10cbff5bc99fa7a02fdb636d3](https://github.com/tarqu1n/reactour/commit/6deb977e0145c5c10cbff5bc99fa7a02fdb636d3)
* Ensure tour step dialog starts centered when the tour starts but does not attempt to center between other steps when the 'actionBefore' function is used to pause step execution. [2d04fc04d8effc72d78868891ac9408f6f76b1fc](https://github.com/tarqu1n/reactour/commit/2d04fc04d8effc72d78868891ac9408f6f76b1fc)
* Remove use of `checkFnAndRun` helper script as there were scoping issues with its execution. [9e374360fff679cd619ea8f7b131f0617484a860](https://github.com/tarqu1n/reactour/commit/9e374360fff679cd619ea8f7b131f0617484a860)

Looking forward to the master branch being finished.

**Comment by elrumordelaluz** [comment]
wow @tarqu1n thank you! I'll give an eye and merge it. Thanks again!

**Comment by tarqu1n** [comment]
@elrumordelaluz I have put these changes into a PR along with another minor IE11 bugfix.
#210

**Comment by elrumordelaluz** [comment]
I'm sorry I didn't get back to you the other day. I tried your changes in `local` and had some _issues_. Let me try the PR and show you if there are still there.

Thanks!

**Comment by elrumordelaluz** [comment]
Here is the _issue_:
```
TypeError: steps[current] is undefined
```

![pr](https://user-images.githubusercontent.com/784056/69430550-2ba74900-0d36-11ea-9ae9-2a62914f41be.gif)

**Comment by tarqu1n** [comment]
I didn't set a default `startStep`, have now updated this:

https://github.com/elrumordelaluz/reactour/pull/210/commits/bd164efceaae3d79cb01467665a7acbb110a1183

**Comment by elrumordelaluz** [comment]
yup! thanks @tarqu1n 

Now I have to found time to work and close the _issues_ related on `actionBefore` (how to cancel `async` stuff, etc.) and update `readme` to let know people that `master` branch is not published yet.

Thanks again!
