### ISSUE TITLE
Reactour does not work with styled components 4.4.1

### ISSUE THREAD

**Issue by subham-iihglobal** [elrumordelaluz/reactour#208]
I had used this library on one of my pages with react 16.11.0 and styled components 4.4.1, it was working completely fine if I went on the tour page from another page by clicking on `<Link/>` (it is SPA using react-router). But if I reload the page which uses reactour then the in-built classes which are generated by this package do not get added to the `<head>` section. Hence, everything would break and the page would not work as desired.

I was suggested to use styled components 4.0.0 and it worked completely fine.

So I guess there are some new changes introduced in styled components 4.4.1 which are not supported completely in reactour.

**Comment by elrumordelaluz** [comment]
Hi @subham-iihglobal, thanks for open the _Issue_.

Is interesting what you are exposing. Do you have a reproduction or a sandbox?

**Comment by subham-iihglobal** [comment]
Sure, I've added a link to the video below.

You may see that when I go to the tour page from another page, the tour works alright. But when I reload the tour page or if I enter the URL to the tour page in url field then the tour breaks. This happens with styled-components@4.4.1. It works completely fine with 4.0.0.

[https://www.loom.com/share/c8db8a1a47b845efb503316cd182dc13](url)

Thanks for the response!

**Comment by subham-iihglobal** [comment]
Mind you that this happens only on Chrome on select machines at my work place. It works completely fine in Firefox.

**Comment by elrumordelaluz** [comment]
> Mind you that this happens only on Chrome on select machines at my work place. It works completely fine in Firefox.

😆 that last comment broke ways to debug hahah

anyway  I see the _screencast_ but it's really difficult to know what is happening. Mind create a reduced reproduction in a _sandbox_? Could you share error `logs` in case there are?

**Comment by subham-iihglobal** [comment]
I'm really SORRY, but that would not be possible!
Anyway, Thanks a lot for your response, I'm closing this issue.
