### ISSUE TITLE
error in finding selector when tour starts first

### ISSUE THREAD

**Issue by HarithaKR** [elrumordelaluz/reactour#213]
In reacttour, if I start the tour, for the first step it opens it is not finding the selector. It show the element is not there. 
If I close the tour by some step and again click on the start tour, it opens the content but it couldn't find the element
I don't find that issue with the demo. But when I implemented in my project, I am facing this issue.
As of now I could fix it by setting startAt as 0

**Comment by elrumordelaluz** [comment]
Hi @HarithaKR, thanks for open the _Issue_.

Could you please share the _Tour_ configuration or even better a [sandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js) with a reduced example?

Thanks,

**Comment by HarithaKR** [comment]
Hi. Finding the node is working fine. The problem was each time when I start tour, as state changes it re-renders the Dom elements. Hence it couldn't find. When moved the touropen state to another parent component, it works fine. 
Thank you.

**Comment by elrumordelaluz** [comment]
Hey @HarithaKR, it's really difficult to _debug_ or try to understand what could happen without a peace of `code`. Please try to share a reproduction of the issue. Thanks!

**Comment by HarithaKR** [comment]
hi. @elrumordelaluz, the issue I faced was resolved. It was some error in implementation. Thank you
