### ISSUE TITLE
Scroll to focus issue (html,body overflow-x disabled)

### ISSUE THREAD

**Issue by developdeez** [elrumordelaluz/reactour#214]
Hi I know the fix for the browser is to make the html not hide overflow:X

But why is that the case and is there another way?

We need to hide x overflow for iphones to prevent sliding.

**Comment by elrumordelaluz** [comment]
Hi @developdeez, thanks for open the _Issue_.

Sorry, commented [here](https://github.com/elrumordelaluz/reactour/issues/160#issuecomment-560126715)

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
