### ISSUE TITLE
Demo website: left (prev) causes tour to go to next step instead

### ISSUE THREAD

**Issue by trysenga** [elrumordelaluz/reactour#215]
I was evaluating options and looked at the demo and noticed this. Perhaps its fixed in latest code and just isn't on the demo site yet but I didn't see it in open issues.

**Comment by elrumordelaluz** [comment]
Hi @trysenga, thanks for open the _Issue_.

Are you looking at [this demo](https://reactour.js.org/). In which `step` is happening this? Is working as expected on my end.

**Comment by trysenga** [comment]
Ah you are correct. It seems that it only happens if you press enter to get the more styled version. At that point previous always advances. Hitting enter again to see the simpler form functions correctly.

**Comment by elrumordelaluz** [comment]
Good catch @trysenga !
