### ISSUE TITLE
how to Stop event bubbling and capture ,please

### ISSUE THREAD

**Issue by aloehh** [elrumordelaluz/reactour#217]

**Comment by elrumordelaluz** [comment]
Hi @aloehh, thanks for open the _Issue_.

Could you please provide an example of where you need this? 

Thanks

**Comment by burnhamrobertp** [comment]
@aloehh this may help you: https://github.com/elrumordelaluz/reactour/issues/209#issuecomment-569745313

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
