### ISSUE TITLE
Horizontal scrolling does not work

### ISSUE THREAD

**Issue by burnhamrobertp** [elrumordelaluz/reactour#218]
I tweaked the demo app slightly and was able to quickly reproduce it. It  seems like the scrolling detection simply ignores horizontal scrolling.

https://codesandbox.io/s/reactour-demo-template-live-jl8m9

**Comment by elrumordelaluz** [comment]
Hi @burnhamrobertp, thanks for open the _Issue_.

Absolutely! Need to be tweaked, but is a super valid _feature_.

**Comment by burnhamrobertp** [comment]
Its definitely a bug, not a feature. We are unable to use Reactour presently because tours simply break if - in the scene in question - there is a tour step whose helper and selected node is entirely off screen. While horizontal scrolling isn't common, there are a number of applications in which its use is kind of necessary.

**Comment by elrumordelaluz** [comment]
Now should work in `v2`(`npm i @reactour/tour`) which uses native scrolling behavior) [demo](https://codesandbox.io/s/reactour-demo-template-live-forked-gql0i?file=/steps.js)
