### ISSUE TITLE
The onRequestClose event is not called when clicking on the highlighted element.

### ISSUE THREAD

**Issue by darekkwiatkowski** [elrumordelaluz/reactour#219]
It seems that the onRequestClose is firing properly when clicking "X" button or clicking on the "gray" background.

However it is not called when clicking on the highlighted rectangle  even though the tour is closing properly.

**Comment by elrumordelaluz** [comment]
Hi @darekkwiatkowski, thanks for open the _Issue_.

> However it is not called when clicking on the highlighted rectangle even though the tour is closing properly.

If I understand ok what you mean, it is the expected behaviour to only closes the _Tour_ through the `x` Icon or the gray _Overlay_.
