### ISSUE TITLE
show all the steps together 

### ISSUE THREAD

**Issue by fereshtehaboohamzeh** [elrumordelaluz/reactour#22]
is there any property to show  the guide steps all together? like an screenshot?
something like this => https://tracelytics.github.io/pageguide
![screenshot from 2017-11-07 17-30-50](https://user-images.githubusercontent.com/12994555/32497482-eea0ddd6-c3e1-11e7-9a4c-ee45be507e1c.png)

**Comment by elrumordelaluz** [comment]
Hi @fereshtehaboohamzeh, there isn't this `prop` but is a perfect `feature request`!
