### ISSUE TITLE
Not able to specify parent element of TourPortal

### ISSUE THREAD

**Issue by worteldief** [elrumordelaluz/reactour#221]
Similar to #145 

I would like to be able to use _reactour_ in the case where fullscreen mode has been requested for an element ([Element.requestFullscreen](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen)).

Due to the portal appending the `div#___reactour` element to the _body_ element it is not visible when a different element is in fullscreen mode.

In older versions of _reactour_ it was possible to pass a _parentSelector_ prop to the _Tour_ element.

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
If this issue is still relevant, consider upgrade into `v2` and please share a sandbox with a reduced reproduction.
