### ISSUE TITLE
Resize highlight boundaries on a changing element

### ISSUE THREAD

**Issue by baohouse** [elrumordelaluz/reactour#224]
So in my scenario:

1. From previous step, click next step
2. Tour renders card but the target element doesn't exist yet
3. Step's `action` triggers a component state change to render element into DOM. This state value is passed into Tour's `update` prop. The element renders in a "loading" state.
4. Tour highlights the target element in its loading state
3. Target element is rerendered with data from the backend. This could take anywhere between 500 ms to 5000 ms. The element is now taller.

`update` and `updateDelay` aren't helpful since 500 to 5000 ms is a big range, so if the updateDelay value is too small, it will not resize the highlight boundaries on the target element.  Too large, and the boundary update could happen way too late after the change finishes.

I was reading the discussion at #32 about possibly using `observe`, but it looks like the boundaries are determined once the target element is seen in the DOM, but isn't updated if there are subsequent changes to that target element.

So I think for updating highlight boundaries, we need to track three things:
1. Changes in element's DOM subtree (MutationObserver on the target element)
2. Changes in element position
3. Changes in element size; and not just from styles attribute on the element itself, but this can occur through CSS classes that are defined outside of the target element (in the &lt;head&gt; for example)

I was able to get the demo in a rare state where this happened:

<img width="1083" alt="TourDemoWithObservedElement" src="https://user-images.githubusercontent.com/4228012/72500232-ea3c9280-37e8-11ea-9ecf-56e7f70b3843.png">

**Comment by elrumordelaluz** [comment]
Hi @baohouse, thanks for open the _Issue_.

Let me ask you a few things to understand well the scenario.

Since you are passing a value to `update` prop, does this value change between first state, loading and final state? In that case, isn't your _highlighted_ are updated?

In the case of using `observe`, are you pointing the `observer` into a _parent_ element? (yes, that one already in the DOM but ideally where the changes happens).

Should be ideal to have a reduced repro of the _Issue_ in a sandbox.

**Comment by baohouse** [comment]
@elrumordelaluz Oh, good point. I think what I can do is create a composite `update` value, something like this. It should work for my use case. For animating elements, I can still use a sufficient updateDelay.

```javascript
class MyApp extends React.Component {
  state = {
    element: null,
    elementLoaded: false,
  };
  handleOnLoad = () => {
    this.setState({ elementLoaded: true });
  }
  render() {
    const { element, elementLoaded } = this.state;
    const updateHash = JSON.stringify({
      element,
      elementLoaded,
      url: window.location.href,
    });
    return (
      <div>
        {element === 'ABC' && <WidgetABC onLoad={this.handleOnLoad} />}
        <Tour update={updateHash} /* ...and other required props */ />
      </div>
    );
  }
}
```
