### ISSUE TITLE
action sometimes disables focus lock

### ISSUE THREAD

**Issue by nelsonwong1012** [elrumordelaluz/reactour#227]
I've been stumped on this one. When I assign a value to `action` for a step, focus lock becomes disabled. In the demo, this does not happen.

Here is the markup generated on my app (with some code removed for readability):
```
<div data-focus-guard="true" tabindex="-1" ></div>
<div data-focus-guard="true" tabindex="-1" ></div>
<div data-focus-lock-disabled="disabled">
    ...
</div>
<div data-focus-guard="true" tabindex="-1"></div>
```

Compared to the markup from the demo:
```
<div data-focus-guard="true" tabindex="0"></div>
<div data-focus-guard="true" tabindex="1"></div>
<div data-focus-lock-disabled="false">
    ...
</div>
<div data-focus-guard="true" tabindex="0"></div>
```

Notice the `tabindex` values on the `<div>`s with `data-focus-guard="true"` as well as the value on `data-focus-lock-disabled`. It seems as `react-focus-lock` is disabling it. Any thoughts?

**Comment by nelsonwong1012** [comment]
Ok, seems like this issue is not specific to my app as I was able to reproduce it on the demo as well. It happens on `v1` but not on `master`. @elrumordelaluz Any chance a new version can be released soon? I'll get the other a11y fixes in.

**Comment by elrumordelaluz** [comment]
> Any chance a new version can be released soon? I'll get the other a11y fixes in.

Hope to have a peace of time to focus on `async actions` to release a `v2`
