### ISSUE TITLE
Possible to have multiple Tours within one application ?

### ISSUE THREAD

**Issue by alxmorgan** [elrumordelaluz/reactour#23]
Hi,

So in my scenario I am trying to have a tour per page if you will. 
I was attempting to do this by creating a separate Tour component and passing steps to it as props when I triggered it to display depending on what page was showing. I get the following error:

TourPortal.js:415 Uncaught TypeError: Cannot read property 'style' of undefined
    at TourPortal.render (TourPortal.js:415)

It seems to me that if tour 1 has 3 steps and tour 2 only 2 then this occurs so it seems the steps array size is the issue even though I can see the steps being passed to the Tour as I am creating it the second time. 

Any help greatly appreciated

thanks,
alx

**Comment by alxmorgan** [comment]
Looks like passing an id to Tour for each different occurrence solves the issue

thanks !!

**Comment by elrumordelaluz** [comment]
Cool @alxmorgan, let me know if you found another related issue.
Anyway I want to put some examples and one of those is a _Multiple Tours_ one.

Thanks again!

**Comment by alxmorgan** [comment]
Will do. Well done, great piece of work by the way
