### ISSUE TITLE
how to define an action when step out

### ISSUE THREAD

**Issue by HarithaKR** [elrumordelaluz/reactour#232]
Hi, In tour implementation, I have a requirement like below
  When I go to a certain step, before showing the guide, i define some style. Eg. That element is hidden (opacity: 0) by default. When I go to the step, I have to show that element (opacity: 1) and then show the guide tour. This one I did by defining action property.
  But then If move away from this step (next or prev), I want to do an action - again hiding the element (opacity: 0). How can I implement is behavior?
Is there any event for that?

**Comment by elrumordelaluz** [comment]
Hi @HarithaKR, thanks for open the _Issue_.

This is the idea for the next `major` version, to have an `actionBefore` and `actionAfter`, right now you have to handle this with the `action`'s from other `steps` (not the ideal situation).

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.

**Comment by krunalinfynno** [comment]
Is there any update on this?
