### ISSUE TITLE
Can react tour work if we have modals that open on click.

### ISSUE THREAD

**Issue by ashwin-nutanix** [elrumordelaluz/reactour#233]
Use case for the tour: 

1.  Have a landing page which has a button B1.
2. On clicking the button B1 a modal appears on top of the landing page. This modal has one more button B2
3. On clicking B2 another smaller model appears on top of the big modal.

Case to be thought of:

-   If one of the steps on the tour is to click B1,  then we must go to the next step if we click on B1. Also we should programatically click B1 is next is pressed.

- When a new modal appears will the Tour component wait for it to load before searching for the selector ? Is there a way to make sure of this ?

**Comment by JakeGreer** [comment]
I would love to make use of this functionality as well. Is there any update on this?

**Comment by elrumordelaluz** [comment]
_Modals_ and other situations are finally handled on **new v2 version** released under scoped `@reactour` package name, please try `npm i @reactour/tour`. Here are some examples:

- [Using React Modal](https://codesandbox.io/s/reactour-tour-demo-using-react-modal-8v0eo)
- [Using Semantic UI Modal](https://codesandbox.io/s/reactour-tour-demo-using-semantic-ui-modal-xmqee)
- [Using React Bootstrap Modal](https://codesandbox.io/s/reactour-tour-demo-using-react-bootstrap-modal-qjws4)

 Every feedback super welcome, thanks!
