### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by halim-paracki** [elrumordelaluz/reactour#235]
Hi, the 'update' parameter which is documented here in the Readme.md does not have any corresponding code in the source code. I've been trying to get it to work in a similar way like some other parameters, and just after having made the effort of cloning the Reactour repository (instead of just installing) and having a closer look at the source code, I realized the update prop never really gets used anywhere... How is it supposed to work?

In any case it's counterintuitive to document something, which in reallity is not implemented...

**Comment by ketewan** [comment]
@halim-paracki, hello! There is a disclaimer in README, that the master branch is currently in development, and I guess there is really no update parameter in new version. The documentation corresponds to the currently published version, which is about v1 branch, where update parameter exists. I personally used it, and it worked as expected. If you have problems with currently published version, could you please provide code, where update parameter does not work?

**Comment by elrumordelaluz** [comment]
As @ketewan, the `update` prop is working in the already published versions, in case you want to deep dive get the `v1` branch.

**Comment by elrumordelaluz** [comment]
Closing for now.

However as @ketewan also mentioned
>  If you have problems with currently published version, could you please provide code, where update parameter does not work?

Please open a new _Issue_ to focus on your specific _use-case_
