### ISSUE TITLE
onBeforeClose does not work on unmunt

### ISSUE THREAD

**Issue by dartess** [elrumordelaluz/reactour#236]
demo: https://codesandbox.io/s/reactour-demo-template-live-l92og

after closing, the body is still locked

**Comment by elrumordelaluz** [comment]
Hi @dartess, thanks for open the _Issue_.

Since you are mounting the _Tour_ Component conditionally, as soon as `isTourOpen` is `false`, the _Tour_ is removed without lifecycles.

Try using instead of

```js
{ isTourOpen && (
<Tour />

**Comment by elrumordelaluz** [comment]
Closing. Feel free to re-open or create a new _Issue_ in any case.

**Comment by dartess** [comment]
This does not fit in my case. My page shows either real data, or demo data and a guide, and this is controlled from the outside. If you think about it, you can find other cases where this can cause problems.

Don't you agree that the current behavior is a bit unexpected? From your answer I did not find out if there is a real reason for this behavior.

**Comment by elrumordelaluz** [comment]
I mean, since you are rendering the _Tour_ conditionally by `isTourOpen` or another prop in your _App_, couldn't you pass that value into the `isOpen` prop of the _Tour_, instead of pass a fixed `true`?

Since you are passing `true` to `isOpen` and simply unmounting the Component, you aren't [closing](https://github.com/elrumordelaluz/reactour/blob/v1/src/Tour.js#L232-L241) the _Tour_ using the callback.

**Comment by dartess** [comment]
Yes, with a little thought, I completely refactored all the supporting code.

However, I still think this behavior is incorrect. I can’t say for sure where else it does not live up to expectations. The component after unmounting should not leave traces of its work. If for this you need to make some effort, this should be written in big red letters.

I can give another example where this will play a trick:

A link may appear in the Tour area. Then, when you click on it in a SPA, a routing will work, which will unmount the current page (including the tour), and draw a new one. The scroll will remain blocked and the application will also be broken.

**Comment by elrumordelaluz** [comment]
Thanks for the example @dartess. In the early versions of `reactour`, the `body-scroll-lock` behaviour was handled by the internals of the _Tour_, for situations like your example and others, now the scroll-lock is outside letting the developer handle in the better way for each _App_ and use cases. The way you are approaching, like in the _Example App_ is a possible way.

Regarding the specific example you describe, you could mount the _Tour_ outside the _Routes_ to avoid unmonting when `pathname` changes and make use of the `update` prop to change _Tour_ content based on `location`, like [this example](https://codesandbox.io/s/myry48155p). However this is just one.
