### ISSUE TITLE
Generated bundle from npm has wrong lifecycle method

### ISSUE THREAD

**Issue by Nikki1993** [elrumordelaluz/reactour#237]
Had an issue where we would be bombarded with 
`Cannot read property getBoundingClientRect of null` 
from reactour. So I checked the pre-generated esm file that `yarn install` installed and noticed that the lifecycle method was wrong. 

```javascript
{
    key: "UNSAFE_componentWillUnmount",
    value: function UNSAFE_componentWillUnmount() {
      var isOpen = this.props.isOpen;

      if (isOpen) {
        this.close();
      }

      if (this.state.observer) {
        this.state.observer.disconnect();
      }
    }
  }
```

componentWillUnmount is **not** an UNSAFE method [React Docs](https://reactjs.org/docs/react-component.html#componentwillunmount) so what happens is when parent component dismounts, reactour does not execute UNSAFE_componentWillUnmount as there is no such lifecycle method and keeps the listeners active, which in turn prompts them to error out on null values when certain conditions are met, like in our case when we present File Save dialog for our CSV export function.
 
![image](https://user-images.githubusercontent.com/1446529/76303822-04678e00-62cb-11ea-9dd0-79a30747dead.png)

**Comment by Nikki1993** [comment]
This is the commit that causes this https://github.com/elrumordelaluz/reactour/commit/0a05b9304d77041f30d6665f29ed27fd18d28ccb componentWillReceiveProps should be UNSAFE, while componentWillUnmount should not be.

**Comment by Nikki1993** [comment]
@elrumordelaluz here is a PR that fixes it https://github.com/elrumordelaluz/reactour/pull/238

**Comment by elrumordelaluz** [comment]
`reactour@1.16.2` published

Thanks again @Nikki1993
