### ISSUE TITLE
Possible to trigger actions between steps ?

### ISSUE THREAD

**Issue by alxmorgan** [elrumordelaluz/reactour#24]
Hello,

I have an application which switches views, 
I would like a tour which walks through all views. 
For this I am triggering view changes using step actions. 
However the issue is that the selectors are not ready until after the action has run by which time the step is showing but cannot anchor to the selector. 

So is there a way to do what I am trying to do already ?
If not perhaps a feature request would be to allow actions to run between steps somehow

thanks,
alx

**Comment by elrumordelaluz** [comment]
Hi @alxmorgan,
Thanks for reporting your use-case. 
You could use the `update` prop, ie setting that value with the `pathname`.
Regarding the selectors ready, you could use `updateDelay`.

Let me know if what described above fits well or in case we'll find other solutions or mark as a feature request.

**Comment by alxmorgan** [comment]
Hi,

I don't fully understand the update prop. We are not using react-router for example so is that the pathname you mention ? 
I have tried adjusting updateDelay but it has no effect. Do this only work in conjunction with update ?

thanks

**Comment by elrumordelaluz** [comment]
Yes, `update` and `updateDelay` are related.
Could you let me know how you handle the _Views_ switching to fully understand and think a possible solution?

**Comment by alxmorgan** [comment]
So we switch views using conditional rendering in our react components. 
So say they click a certain button - this means they change to a certain mode. 
This mode is held in redux. 
Then the redux model is read as part of a component render and a choice of what to show is made at that point. 
Hope that makes some sense

thanks

**Comment by elrumordelaluz** [comment]
You could pass the `prop` which manage the views status form the _Redux_ store into `update`, something like:
```
<Tour
  steps={[…}
  isOpen={true}
  update={this.props.viewsStatus} />
```

let me know

**Comment by alxmorgan** [comment]
Interesting idea...will give it a try and report back. 
Thanks for the help

**Comment by elrumordelaluz** [comment]
@alxmorgan please let me know if this solution works in order to close the _issue_ or search another solution

**Comment by alxmorgan** [comment]
Sorry, got assigned to something else and haven't had a chance to come back to it.
I think we can close this and if I ever come back to it I can update

thanks for the help

**Comment by thisisthais** [comment]
I know this is an old issue and is closed, but I'm having a similar problem. I'd like to use this tour even when the route changes and new components are mounted. I saw some working examples using withRouter, but unfortunately my team is on react-router 3 so we don't have withRouter or __RouterContext. I built a custom hook that listens for the browserHistory location change and sets that as state that is passed down as a prop from the main App component to our router instead.

I tried using the update function (tied to the location, which I see is changing) and set updateDelay to 10000 but the selector component is still not highlighted on the route change. If I go forward a step and then back again, the component is properly highlighted. Sorry, I don't have a reproducible sandbox example yet.

**Comment by elrumordelaluz** [comment]
If I remember well, in a project with `react-router@3` I use the `location.pathname` value to pass down to `update` prop. This should work I think. Let me know @thisisthais

**Comment by thisisthais** [comment]
yeah that's what I've been doing, here's a snippet:
```
const HustleTour = ({ tour, loc }) => {
    const { pathname } = loc;
    const steps = [
      ...(pathname === '/workflows'
        ? workflowsSteps : []),
      ...(pathname === '/workflow/HKwjC3DHU4/start'
        ? scriptSteps : []),
    ];

    return (
      <Tour
        steps={steps}
        isOpen={tour.isTourOpen}
        onRequestClose={() => tour.setTourOpen(false)}
        update={pathname}
        updateDelay={2000}
      />
    );
  }
```

the location.pathname is updating correctly because I am seeing the different steps (workflowSteps vs scriptSteps) when on different routes, it just seems that the delay isn't working because the selector is not finding the given component.

**Comment by elrumordelaluz** [comment]
Are you getting any console `warn`/`error`? Because when the DOM node isn't found fires a log.

**Comment by thisisthais** [comment]
Yeah I am getting a console.warn like `Doesn't find a DOM node...`

By the way, there is another thing that I tried but maybe I am misunderstanding how observe works.
I tried setting the first step in the new route like:
```
  {
    selector: '.workflowStart',
    content: 'This is the script lorem ipsum',
    observe: '.web',
  },
```

where `workflowStart` is the component I want highlighted (which is unmounted at the beginning of page load in the new route) and `web` is the parent container that exists between both routes. I thought maybe if i observe the parent container, and it gets changed between routes, it would run the query selector function again. But that didn't work either.

**Comment by elrumordelaluz** [comment]
The `step.observe` prop works in a different way of `tour.update`. Observes a parent element which fires a re-calculation when detects a change on its children.

**Comment by elrumordelaluz** [comment]
Let's create a simple sandbox using RR3 to try to simulate your approach and understand well what could be the reason.

**Comment by thisisthais** [comment]
I've tried to create a smaller example, I'm getting a different error than in the real code I'm working with though: https://codesandbox.io/embed/async-smoke-cf5px

**Comment by spyx08** [comment]
Hey, 
got something similar, I'm using reactour in my application, the thing is that some step are triggering router navigation, but I need to focus elements who are loaded async with a promise. 
For the moment I put a static timeout but I need something automatic to set the next step once the elements are loaded and on DOM. 
I tried to use update and change the value once the elements are loaded but the step automatically changed with or without changing this variable. 

Any clue on how to achieve this without random timeout ?

**Comment by elrumordelaluz** [comment]
@spyx08 Mind share a reduced reproduction in a sandbox, in order to try alternatives? thanks!
