### ISSUE TITLE
Helper alignment

### ISSUE THREAD

**Issue by ketewan** [elrumordelaluz/reactour#244]
Hello, and thank you for your library again!

I see in the code, that the guide is firstly aligned along left/top side, and if not possible -- along right/bottom side of a target. I need it to be placed centered relatively to target. Could you consider adding a prop for preferable alignment, or, maybe, doing "center" the first option? I could prepare a PR, if this change is acceptable.

**Comment by elrumordelaluz** [comment]
Hi @ketewan, thanks for open the _Issue_.
Absolutely welcome a PR to review! Thanks in advace,
