### ISSUE TITLE
Search in iframe

### ISSUE THREAD

**Issue by ketewan** [elrumordelaluz/reactour#245]
Hello again! Another small feature request from me.

It would be great to have an ability to search and then highlight selectors in iframe (assuming it has already loaded and there is no need to wait for it).

Is there a way to do so in the current library implementation? I couldn't come up with a solution without changing a library, cause document.querySelector will not recursively search nodes inside iframe document. Please let me know if solution exists. If no, it could be done rather simply by either specifying document's root selector for step (ex. iframe id) or implementing some kind of recursive getElement function, which will try to find a node not only in window document, but also select all iframe documents and start search there. 

If you think, that this would be helpful, I will prepare a PR.

**Comment by elrumordelaluz** [comment]
Closing to focus on #328
