### ISSUE TITLE
switchable styled components / emotion

### ISSUE THREAD

**Issue by michelson** [elrumordelaluz/reactour#246]
Hi, I would like to use this project but I need to use emotion-styled, specifically because I will have this as an third party application and in some situations when the host page is also using styled-components it will break the application. yup it will break, that's because styled-components does not accept multiple instances of it, and since my script will be external I could not apply techniques such as dedupe packages. But it's supported with emotion-styled.

So , I would like to ask if it's ok for you that I submit a PR that support both systems ? the API of styled-components & emotion-styled is just the same, so I guess it will be an easy task- 
what you think?

**Comment by elrumordelaluz** [comment]
Absolutely welcome!!

**Comment by michelson** [comment]
#247

**Comment by elrumordelaluz** [comment]
#156 #132 #100

**Comment by designbyadrian** [comment]
I think styled-components are creating Content Security Policy issues in my progress web app (iOS). I'd prefer if neither was a dependency.
