### ISSUE TITLE
BUG: Invalid hook call

### ISSUE THREAD

**Issue by dovy** [elrumordelaluz/reactour#249]
I'm building a WordPress plugin, and it works flawlessly until I try to add reactour. Which is so sad because I love this component. Alas, I have been trying for 3 days now to find a resolution to this. When I load the tour inside my component I am getting the following error:

```
Invalid hook call. Hooks can only be called inside of the body of a function component.
```

See the full errors here:
- https://cldup.com/vJdRfIaCoI.png
- https://cloudup.com/ctgcyFDr34R

The code I am running can be found here:
https://github.com/starterblocks/starterblocks/blob/develop/src/modal-library/index.js

I've tested my steps and store, and bypassed them all with no change. It appears to be triggered from this line in the Portal component of reactour: https://github.com/elrumordelaluz/reactour/blob/master/src/Portal.js#L5  However, being this is a portal, it might also be coming from any of the children fed to it.

I really want to use reactour, but we've been trying to fix this for 3 days now. I might have to choose another solution. Please help!

**Comment by dovy** [comment]
I was SO wrong. This was entirely my fault. Thank you.

**Comment by quantafire** [comment]
> I was SO wrong. This was entirely my fault. Thank you.

@dovy How were you wrong though? Having my own issues with this same error.

**Comment by elrumordelaluz** [comment]
I am curious about the plugin! is there any link?

**Comment by frsmlk** [comment]
@elrumordelaluz I have this exact problem. Can't seem to get it to work. Any ideas?

**Comment by elrumordelaluz** [comment]
@frsmlk could you please share the code or create a reduced sandbox? thanks!
