### ISSUE TITLE
Is this thing alive?

### ISSUE THREAD

**Issue by PeterKottas** [elrumordelaluz/reactour#250]
Just curious if this is still maintained. I have noticed there's quite a few issues with no resolution and open PRs with no response from the maintainers. I do have a few things I am missing in this lib but most of it is already covered by various PRs and issues. What's the status pls? Cheers!

**Comment by dovy** [comment]
Yea, I am wondering the same thing. :(

**Comment by elrumordelaluz** [comment]
Yup, sorry to everyone who need some thing implemented and the _repo_ seems frozen. As soon as I can I'll reply/implement all the stuff.

**Comment by PeterKottas** [comment]
@elrumordelaluz Thanks for the input mate! There's a lot of great work in this repo, would be a shame to see it go to waste. So let me see if I understand. Are you now working primarily on master while the v1 branch is kept in sync with the current released version? Correct? Do you have any deadline for the 2 to become one? In other words, do you have a clue when the stuff on the master will be released to the public? I think right now, contributing is slightly awkward because the stuff on master won't be released while the stuff on v1 can be lost while the master is released.

**Comment by elrumordelaluz** [comment]
Everything correct, I am aware of the fact on collaborating, maintaining from the `v1` as the stable branch. In case you have any idea/input/PR absolutely open, the `master` branch should be a `@next` one while the `v1` should be switched to `master` again.
As for the release of `v2` some stuff is frozen, while need some investigation to allow implement `actions` (pre/post) on each `step` allowing to have `async` calls, but also some kind of cancellation. Open to any kind of conversations regarding those topics.

**Comment by PeterKottas** [comment]
I see. Sorry to hear you are having trouble implementing some of that stuff. Do you have slack or something similar where we could discuss this live? I've checked the main component on master and I appreciate the progress made compared to v1 branch. It's definitely much cleaner.

Why do you want to have async callbacks in the first place? Do you want to first actions that would affect the next step and want to avoid flickering? Cause that's probably the most realistic reason I could come up with. 

In other words, is my understanding clear that you want to have 
preaction - where you could possibly cancel the update
action - where you can perform something
postaction - where you could for instance transfer to different step altogether 

I have been part of similar designs talks with other libs. Have you considered making the step a controlled variable? This could circumvent some of that trouble you are seeing now. there would obviously be an onChange handler (similar to getCurrentStep ) which would serve as an indication on the step being changed. Folks could just react to that. 

Maybe you thought of actions for a totally different reason that I am not seeing right now. But who knows, maybe this fresh perspective would help you out ;) I am happy to discuss further

**Comment by elrumordelaluz** [comment]
Hey @PeterKottas, let's talk [here](https://gitter.im/reactour/Lobby)

**Comment by volkandkaya** [comment]
@elrumordelaluz  @PeterKottas how did the talks go?

This is amazing, I just need it to be cleaned up a little and I can launch the in app tours.
