### ISSUE TITLE
Action is too late

### ISSUE THREAD

**Issue by dovy** [elrumordelaluz/reactour#251]
So I perform an `action` to render a new model window. The problem is the "modal" is not in the dom, so the tour selector can't find it. @elrumordelaluz  Any ideas how I could resolve this?

**Comment by elrumordelaluz** [comment]
Or 
- wait for `v2` (which should include related stuff, but don't know when will be released) or 
- try updating the `update` value for the _Tour_ Component to force an update.

**Comment by dovy** [comment]
Do you have an example for `updated`?

**Comment by elrumordelaluz** [comment]
Do you have any reduced reproduction or at least a codesandbox with a similar example to try to explain there?

**Comment by dovy** [comment]
This is what we ended up with: https://github.com/starterblocks/starterblocks/blob/develop/src/tour/index.js

Works fine for us. Thank you.

**Comment by elrumordelaluz** [comment]
Awesome!
