### ISSUE TITLE
Not scrolling elements into view when I use reactour selector in list element

### ISSUE THREAD

**Issue by greatdolphinls** [elrumordelaluz/reactour#252]
Reactour is not auto-scrolling to elements.  
I send reactour selector as props in list(map) component.
```javascript
{tabs.map((tab) => (
        <Tab
          key={tab.id}
          icon={tab.icon}
          label={tab.label}
          data-tut={tab.tour || ''}
          className={classes.tab}
        />
 ))} 
```
Any idea what could be preventing the scrolling?

**Comment by elrumordelaluz** [comment]
Hi @thomashanahan, thanks for open the _Issue_. Mind share reduced reproduction in a codesandbox?

**Comment by aatif24** [comment]
is this resolved, i am facing the same issue, when i list a selector in steps on the page where you need to scroll, it does not work

**Comment by elrumordelaluz** [comment]
@aatif24 could you share a reproduction on a sandbox?

**Comment by aatif24** [comment]
> @aatif24 could you share a reproduction on a sandbox?

i can share small video of the behaviour if you need

**Comment by elrumordelaluz** [comment]
sure

**Comment by aatif24** [comment]
[Screen Recording 2020-08-13 at 6.50.15 PM.zip](https://github.com/elrumordelaluz/reactour/files/5069253/Screen.Recording.2020-08-13.at.6.50.15.PM.zip)

**Comment by acomito** [comment]
I'm also having the same issue. 

Although, mine isn't fixed by removing `scroll-behavior: smooth;`

I'm using it in a big project, so getting a reproduction may be tough.

**Comment by abhijan1102** [comment]
I am also facing similar issue with my code when I am using reactour. I do not have scroll-behavior mentioned anywhere in the code

**Comment by Salvadormeal** [comment]
> sure





https://stylesheets.space/questions/issue-with-htmlcss-rectangle-doesnt-scroll-as-expected
