### ISSUE TITLE
Hide step number on the top left side.

### ISSUE THREAD

**Issue by Gia1987** [elrumordelaluz/reactour#254]
Hi, thanks so much for this great library! I really like it.

I was wondering whether it is possible to hide the number of the step?

<img width="453" alt="Screenshot 2020-04-08 at 10 09 31" src="https://user-images.githubusercontent.com/34454055/78767537-a211b400-7982-11ea-85bd-f6637ceeeefc.png">

**Comment by elrumordelaluz** [comment]
Hi @Gia1987, thanks for open the _Issue_.

You need to pass [`showNumber={false}`](https://github.com/elrumordelaluz/reactour#shownumber) to the _Tour_ Component

**Comment by Gia1987** [comment]
Hi @elrumordelaluz, thanks a lot.
