### ISSUE TITLE
show empty box  exactly the same size as before component, when goes to next step outside of view

### ISSUE THREAD

**Issue by MasoumeAfshar** [elrumordelaluz/reactour#255]
The tour starts correctly, but when it goes to the next step that is outside of view, it draws the tour component exactly the same size as before , I remove all overflow-x  style from body but it didn't solve,

It is very different with your demo example in codesandbox ,when goes to next step and  scrolling 

![Screen-Recording-2020-04-20-at-4 21 35-PM](https://user-images.githubusercontent.com/30409314/79749656-d68f5380-8324-11ea-8340-57d1849728ce.gif)

**Comment by elrumordelaluz** [comment]
Hi @MasoumeAfshar, thanks for open the _Issue_.
Are you using any library that encloses or your _Components_ are inside a `DOM` node scrollable? Seems that were some _issues_ related to those things.

Do you have a inspectionable endpoint or could you create a reduced reproduction in a codesandbox?

**Comment by Lostkill** [comment]
I have the same problem

**Comment by elrumordelaluz** [comment]
@Lostkill does the _Tour_ Component lives inside an `element` scrollable other than the `body`?

**Comment by Lostkill** [comment]
Yeap! but the parent component is not scrollable, i will try to reproduce error in codesandbox, so i post here

**Comment by Lostkill** [comment]
I guess scroll need run first then transition tooltip, because he take the position when scroll run he does not update position
