### ISSUE TITLE
'styled-components' does not contain an export named 'createGlobalStyle'

### ISSUE THREAD

**Issue by alesdonoso** [elrumordelaluz/reactour#257]
Hi there!

I just tried to use reactour but it seems that some issues are found in node_modules dependencies. I've upgraded styled-components library to v5. This is my package.json:

```json
"react": "^16.8.6",
"reactour": "^1.17.0",
"styled-components": "^5.1.0",
```

When I import the Tour component from 'reactour' the console prints the following error: 

```
./node_modules/reactour/dist/reactour.esm.js
151:18-35 'styled-components' does not contain an export named 'createGlobalStyle'.
``` 

I checked around the index.d.ts from styled-components library and found that the function is correctly exported as:

```ts
export function createGlobalStyle<P extends object = {}>(
    first:
        | TemplateStringsArray
        | CSSObject
        | InterpolationFunction<ThemedStyledProps<P, DefaultTheme>>,
    ...interpolations: Array<Interpolation<ThemedStyledProps<P, DefaultTheme>>>
): GlobalStyleComponent<P, DefaultTheme>;
```

Any suggestion? 
Thanks.

**Comment by elrumordelaluz** [comment]
Hi @alesdonoso, thanks for open the _Issue_.

Could you please check if there are more versions of `sc` installed in the project.

I couldn't reproduce the error [here](https://codesandbox.io/s/reactour-demo-template-live-d5zmk?fontsize=14&hidenavigation=1&theme=dark) where the dependencies are similar.

<img width="271" alt="Screenshot 2020-05-07 at 09 13 34" src="https://user-images.githubusercontent.com/784056/81265271-12275e80-9043-11ea-9293-5a87d8133c8c.png">

**Comment by alesdonoso** [comment]
> Hi @alesdonoso, thanks for open the _Issue_.
> 
> Could you please check if there are more versions of `sc` installed in the project.
> 
> I couldn't reproduce the error [here](https://codesandbox.io/s/reactour-demo-template-live-d5zmk?fontsize=14&hidenavigation=1&theme=dark) where the dependencies are similar.
> 
> <img alt="Screenshot 2020-05-07 at 09 13 34" width="271" src="https://user-images.githubusercontent.com/784056/81265271-12275e80-9043-11ea-9293-5a87d8133c8c.png">

```json
"css-loader": "^3.1.0",
"react": "^16.8.6",
"react-dom": "^16.2.0",
"react-router-dom": "^5.0.1",
"reactour": "^1.17.0"
```

Thanks!

**Comment by elrumordelaluz** [comment]
Hi @alesdonoso, did you found the reason?

**Comment by alesdonoso** [comment]
> Hi @alesdonoso, did you found the reason?

Hi @elrumordelaluz, I have not been able to fix the issue, sorry. You can close the issue since I'm not going to use reactour for the moment! Thanks <3

**Comment by elrumordelaluz** [comment]
ok, feel free to re-open or open a new one
