### ISSUE TITLE
Highlighting Favicon or PageTitle as one of the tour steps! 

### ISSUE THREAD

**Issue by atarazavi** [elrumordelaluz/reactour#258]
Hi, Thanks for your wonderful and easy to use package.
Is it possible to highlight Favicon and/or page title as one of the steps?
If so, how?
Thanks

**Comment by elrumordelaluz** [comment]
Hi @atarazavi, thanks for open the _Issue_.

The working area of the _Tour_ is the same of your _Application_ `<body>`. So since the _favico_ and _Title_ is outside that area, it isn't possible. 

Closing, but feel free to re-open in case you have a solution or proposals.
