### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by dutzi** [elrumordelaluz/reactour#259]
I've been looking for tour (or user journey) solutions and this one is by far the most polished one I found. Kudos!

The only issue I have is its bundle size, weighing almost 30kb (since styled-components is required for it to work) is a lot. Are there any plans to shrink it down? 

If not, @elrumordelaluz, can you please state what are the reasons it weighs so much so others can create a lighter fork?

**Comment by elrumordelaluz** [comment]
Hi @dutzi, thanks for open the _Issue_.

First of all I am happy you like _Reactour_.

Probably you are talking about the [this](https://bundlephobia.com/result?p=reactour@1.17.0) bundle size and seems that there is a considerable difference compared to [v1.13.3](https://bundlephobia.com/result?p=reactour@1.13.3) where `focus-lock` and `react-focus-lock` weren't included yet.

Absolutely agree on finding ways to shrink down the _bundle_ size. So feel free to make PRs taking this _Issue_ as tracker.

As related information, the _focus lock_ behaviour it isn't working pretty well (there are [some _Issues_](https://github.com/elrumordelaluz/reactour/issues?q=is%3Aissue+is%3Aopen+focus-lock) related open) so maybe we could think on removing/replacing it.

Thanks in advance for such interest in that important aspect of the _Library_!
