### ISSUE TITLE
Not scrolling elements into view

### ISSUE THREAD

**Issue by 5tormTrooper** [elrumordelaluz/reactour#26]
reactour is not auto-scrolling to elements outside the viewport. My header and sidebar are fixed elements, and the main element contains the components, including those not being scrolled to.

![screen recording 2018-01-22 at 04 25 pm](https://user-images.githubusercontent.com/4154407/35228395-eade13e0-ff90-11e7-998f-35a0ed452be8.gif)

My app has the following markup:
```
<div class="app">
  <header class="app-header"></header> <!-- fixed el -->
  <div class="app-body">
    <div class="sidebar"></div> <!-- fixed el -->
    <main></main>
  </div>
</div>
```

Any idea what could be preventing the scrolling?

**Comment by elrumordelaluz** [comment]
Hi @5tormTrooper,
First of all, thanks to reach out and fill this issue.
I am trying to reproduce it but everything works well in the [example](https://ppwj14pnrj.codesandbox.io/) I did.

![demo](https://user-images.githubusercontent.com/784056/35270205-b21a8464-002e-11e8-8388-b27e6f9a0dd3.gif)


Could you please give an eye to the [code of this example](https://codesandbox.io/s/ppwj14pnrj)?

Then we can analyse which is the difference with your _use case_, maybe making changes on the [sandbox](https://codesandbox.io/s/ppwj14pnrj).

**Comment by elrumordelaluz** [comment]
@5tormTrooper please let me know if you solved the _Issue_ so we can close it. Otherwise, I'll ask you more information to reproduce the behavior you showed.

**Comment by 5tormTrooper** [comment]
@elrumordelaluz thanks for taking the time to demo this. After comparing the two, I released that there was a stray overflow rule on the app-body. After removing it the scrolling works fine. So it was a problem with my app and not the package.

Sorry for the delayed response, other issues got promoted to top priority...

Thanks again for looking into it!

**Comment by elrumordelaluz** [comment]
no problem.
hope the lib is useful for your app.


Il giorno 09 mar 2018, alle ore 11:32, Storm <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@elrumordelaluz<https://github.com/elrumordelaluz> thanks for taking the time to demo this. After comparing the two, I released that there was a stray overflow rule on the app-body. After removing it the scrolling works fine. So it was a problem with my app and not the package.

Sorry for the delayed response, other issues got promoted to top priority...

Thanks again for looking into it!
