### ISSUE TITLE
Cannot use the customHelper function in typescript

### ISSUE THREAD

**Issue by saurabhmahajan0077** [elrumordelaluz/reactour#260]
Cannot use the `CustomHelper` function for `Tour` component, since there are no type definitions present for it. Can you please update the @types for this library.

Tried doing that but somehow couldn't figure out the right way to do it.

**Comment by elrumordelaluz** [comment]
Hi @saurabhmahajan0077, thanks for open the _Issue_.

Mind make a PR [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/reactour)? Thanks for the catch up!

**Comment by saurabhmahajan0077** [comment]
@elrumordelaluz 
Tried doing that, here's my [commit](https://github.com/saurabhmahajan0077/DefinitelyTyped/commit/0034a2f2d7be7b02aec088ea1cb29c4651d6d2a3)

Couldn't decipher the types for the arguments. Would appreciate some help

**Comment by heensheikh22** [comment]
I am facing the same issue, can someone please take a look at it?

**Comment by saurabhmahajan0077** [comment]
@elrumordelaluz Can you please take a look at the commit ?
It would be of great help to me.

**Comment by elrumordelaluz** [comment]
hi @saurabhmahajan0077, could you please let me know how can I help you? Is there a PR not merged?

**Comment by saurabhmahajan0077** [comment]
@elrumordelaluz I need the types of arguments passed to the `CustomHelper` function.

`{
    current,
    content,
    totalSteps,
    gotoStep,
    close
  }` are passed as parameters to the function. As far as I can understand `current` will be a `number` , `totalSteps` will be a `number` , `gotoStep` will be a `function`, `close` will also be a `function`, the only type that I'm not sure of is the `content`.

**Comment by elrumordelaluz** [comment]
`content` should be the same as [this one](https://github.com/saurabhmahajan0077/DefinitelyTyped/blob/0034a2f2d7be7b02aec088ea1cb29c4651d6d2a3/types/reactour/index.d.ts#L26)

**Comment by tgrassl** [comment]
Hi, any updates on the missing types?

**Comment by tgrassl** [comment]
I added them to the definitions 😃  [https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50832](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50832)

**Comment by tgrassl** [comment]
@elrumordelaluz the types are now merged. This issue can be closed 👍

**Comment by elrumordelaluz** [comment]
Awesome, thank you @tgrassl!
