### ISSUE TITLE
Unable to use hooks in step content

### ISSUE THREAD

**Issue by PeterKottas** [elrumordelaluz/reactour#264]
The step content is called like a javascript function instead of being called as JSX element. That's why the hooks won't work in function step content. Code responsible for this is [here](https://github.com/elrumordelaluz/reactour/blob/master/src/Tour.js#L260)

This should be pretty straight forward fix via PR, however since I cannot afford to wait for it to be released now, I've create the following function that you can use to fix that in your code before this is fixed. Here is the code:

```
export const allowHooksInStepContent = (steps: ReactourStep[]) =>
  steps.map(s => ({
    ...s,
    content:
      typeof s.content === 'function'
        ? (p: ReactourStepContentArgs) => <s.content {...p} />
        : s.content,
  }));
```

As you can see, it simply adds another layer that is properly called as JSX. Hope somebody finds this useful.

**Comment by PeterKottas** [comment]
The reason why I am using hooks in step content (which generally speaking should be kept simple) is i18n. The content rendered here needs to be translated in our app. I guess others might find themselves in similar situation.

**Comment by elrumordelaluz** [comment]
Don't know if is still relevant this issue. 
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.

**Comment by PeterKottas** [comment]
Sure thing, the instructions here are enough for anybody who struggles with it. I doubt this is an issue in v2 therefore no need for other work. Happy cleaning 🧹
