### ISSUE TITLE
issues with delay in first tour card appearing

### ISSUE THREAD

**Issue by bigfoot31** [elrumordelaluz/reactour#267]
It takes around 2-3 seconds for the first tour card to appear after triggering onOpen. Anything that I could do to speed it up. Using pretty much the default props. Using data-tour as the selector. Content is only strings.

**Comment by elrumordelaluz** [comment]
Hi @bigfoot31, thanks for open the _Issue_.

You mean after pass `isOpen=true` to the _Tour_ Component? Do you have a little reproduction o a peace of code to share?

**Comment by bigfoot31** [comment]
Seems to be ok in the production version (npm build). Closing it.
