### ISSUE TITLE
Custom component for closeButton?

### ISSUE THREAD

**Issue by tgreen7** [elrumordelaluz/reactour#268]
i see there are ways to pass custom button components for `prevButton` and `nextButton`. Why not have the same capability for the close button?

**Comment by lucas-rombaldi** [comment]
I agree with @tgreen7, that would be a pretty nice feature. Mainly because it's not so clear about what should happen on clicking in the close button.

**Comment by kkirsche** [comment]
I would also be interested in this, please

**Comment by Praharsh99** [comment]
Yeah, that would be cool!
But I tried to implement it on my own. I've set "showCloseButton" to "false" then added the "lastStepNextButton"={YOUR CUSTOM COMPONENT HERE...} and styled the custom component to be at the right place. But this component only appears on the last step which might be not suitable for all situations

**Comment by bogodars** [comment]
Same here! It will be very cool to customize close button, or change it to 'Skip" button.

**Comment by bogodars** [comment]
Well guys, i figured out, that There is Close component and it is possiy to customise it how you need. If you need a hint write to me.

**Comment by kkirsche** [comment]
@bogodars please share in the thread so that all users who have expressed interest and future search users can see the answer.

**Comment by bogodars** [comment]
in src Components there is a Close component which stands for Close button, so you just need to customize this button as you need.

**Comment by bogodars** [comment]
[url=https://imgbb.com/][img]https://i.ibb.co/mzhfbn4/Close.png[/img][/url] This is how my close button looks after customization.

**Comment by woodybooy** [comment]
> ![Close](https://camo.githubusercontent.com/54c8965a756ffb2c2f07e57d6c1d9dad481df284c556c4d0ec2dfae3df749352/68747470733a2f2f692e6962622e636f2f6d7a6866626e342f436c6f73652e706e67) This is how my close button looks after customization. (Skip button)

how do you customize like this? do you have sample ?

**Comment by bogodars** [comment]
> > ![Close](https://camo.githubusercontent.com/54c8965a756ffb2c2f07e57d6c1d9dad481df284c556c4d0ec2dfae3df749352/68747470733a2f2f692e6962622e636f2f6d7a6866626e342f436c6f73652e706e67) This is how my close button looks after customization. (Skip button)
> 
> how do you customize like this? do you have sample ?

Hi, please see here https://github.com/bogodars/user-guide

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.

**Comment by kkirsche** [comment]
As this is an issue that was never addressed, I don't agree this should be closed. This is still desired

**Comment by elrumordelaluz** [comment]
Now is possible to control each Component inside the _Popover_ through the [components](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#components-popovercomponentstype). 

[Here](https://reactour.vercel.app/#custom-components) is the demo.
