### ISSUE TITLE
Step update from outside component

### ISSUE THREAD

**Issue by switchur** [elrumordelaluz/reactour#27]
Hey! Congrats on building a great library! I'm trying to work out if it's possible to update the step number from outside the component ie. change from step 1 to step 2 via a button that is outside of reactour.  Is the update prop for this purpose? Thanks.

**Comment by elrumordelaluz** [comment]
Hi @switchur, I am happy you like the library.
At the moment there isn't a direct way to handle this situation. I am starting working on refactor which will include this and other _features_ asked before.
Anyway `update` could be useful in case you change i.e routes and want to force update the _Tour_.

I am absolutely open to heard more about your specific _use-case_ to help solve with the current version or applying new features for the future version.

**Comment by qboot** [comment]
#38 should fix this issue 😊

**Comment by elrumordelaluz** [comment]
fixed in #38
