### ISSUE TITLE
How can I prevent the tour from closing?

### ISSUE THREAD

**Issue by christiantigre** [elrumordelaluz/reactour#277]
How can I prevent the tour from closing? example modal backdrop={"static"} , when the user clicks outside the modal.
 I try. 
```
<Tour backdrop={"static"} steps={steps} isOpen={isTourOpen} onRequestClose={closeTour} />
```

**Comment by elrumordelaluz** [comment]
Hi @christiantigre, thanks for open the _Issue_.

Could you please elaborate a little more your _issue_ or better create a sandbox with a reduced reproduction?

Thanks!

**Comment by SalmanMehmood** [comment]
Add this prop..
`disableInteraction={false}`

**Comment by elrumordelaluz** [comment]
Thanks @SalmanMehmood I didn't understood, but seems the perfect answer.

**Comment by Praharsh99** [comment]
Hi @christiantigre,
Even I wanted the exact behavior. So, I tried and it worked for me.

See the snippet attached. Hope it helps

Please correct me If I am wrong or did a mistake anywhere in the code...😀
![tour](https://user-images.githubusercontent.com/38614938/93003970-bc1e7680-f560-11ea-9aeb-38bd585c89a4.png)

**Comment by LordA98** [comment]
Hi,

I noticed this issue was still open.  I was also having the same issue.  I'm not sure when this prop was added, but you can prevent the user closing the tour using this:

`closeWithMask={false}`

So:

```
<Tour 
    // ...
    closeWithMask={false}
    // ...
/>
```

This also means that the user can still close the tour using the close button / cross in the top right.

**Comment by elrumordelaluz** [comment]
Please take a look into [onClickMask](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#onclickmask-clickprops-clickprops--void) of **new v2 version** released under scoped `@rectour` package name,  try `npm i @reactour/tour`. Every feedback super welcome, thanks!
