### ISSUE TITLE
Is it possible to customize close component and it's props?

### ISSUE THREAD

**Issue by MikeKoval** [elrumordelaluz/reactour#279]
https://github.com/elrumordelaluz/reactour/blob/master/src/Tour.js#L401
I would like to add custom tooltip for close button but it seems there is no possibility to pass custom Close component into Tour, am I right?

**Comment by elrumordelaluz** [comment]
Hi @MikeKoval, thanks for open the _Issue_.

There isn't a way to pass only than button, but you could approach passing a `CustomHelper`, like in the [demo](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L62).

Let me know if could fit in your use case.

**Comment by elrumordelaluz** [comment]
Now is everything customizable using `v2`. Feel free to re-open or create a new one in any case.
