### ISSUE TITLE
How to change the default blue colour of the badge and step indicator?

### ISSUE THREAD

**Issue by deangibson89** [elrumordelaluz/reactour#28]
Might not necessarily be an issue with the code and functionality but perhaps the README can be updated to be a bit more clear in this regard?

**Comment by elrumordelaluz** [comment]
@Tiwaz89 Absolutely agree. As soon as possible I'll update into a`v2` so hopefully also new _Docs_.
In the meantime you could add what you think could be usefull with a PR [here](https://github.com/elrumordelaluz/reactour/blob/master/README.md)

Thanks!

**Comment by danloiterton** [comment]
what IS the best way to update the styles? If I render custom components in either the step `content` or in the  `badgeContent` then it seems to ignore my inline `style` attributes. Also the class names of the various elements seem to be a bit arbitrary. Is it safe to use them with css selectors? Or can I override the class names somehow (I see there's an option for the main helper class but not for the badge, etc).

**Comment by elrumordelaluz** [comment]
@danloiterton yes you are right, for now the `className`s and `style`s are a bit arbitrary. Will be different in the next major version.

**Comment by qboot** [comment]
New `accentColor` prop fix this issue (PR: #42)

**Comment by elrumordelaluz** [comment]
Now (`v1.12.0`) is possible to pass a `CustomHelper` prop, please take a look into the [demo source](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L94-L144) or check the live version at https://reactour.js.org/ (try press `Enter` to switch between default and custom _Helper_).

Closing, but feel free to re-open or open a new _Issue_ in any case.
