### ISSUE TITLE
Highlight element

### ISSUE THREAD

**Issue by RituBhawsar** [elrumordelaluz/reactour#280]
Great Module !

I am trying to figure out how i can change the look of highlighted element just for e.g i want to show the border or any background color for the highlighted element instead of showing the default one.

**Comment by elrumordelaluz** [comment]
Hi @RituBhawsar, thanks for open the _Issue_.

The highlighted element doesn't have a wrapper _per se_. Is highlighted thanks to the _Mask_ areas that creates that _hole_. However, thanks to the prop [disableinteraction](https://github.com/elrumordelaluz/reactour#disableinteraction), which adds an extra svg `rect` to avoid the _User_ interacts with the highlighted element content, you could obtain something near your needs (in case isn't a _must_ to have interaction in your _highlighted_ element).

So, first pass the `disableinteraction` into the _Tour_, then use the class `reactour__mask--disable-interaction` to style it, something like:

```css
.reactour__mask--disable-interaction {
  stroke: deeppink;
  stroke-width: 3px;
  rx: 6px;
}
```

[Here](https://codesandbox.io/s/reactour-demo-template-live-forked-l0sb3?fontsize=14&hidenavigation=1&theme=dark) is a working example.

**Comment by RituBhawsar** [comment]
Hi @elrumordelaluz , Thank you for your response
Yes i have did the same it is working fine, but when we want to apply style different for each of the Highlighted element So is there any way for that?

**Comment by elrumordelaluz** [comment]
Leaving this _issue_ open since could be interesting to have a dynamic _global_ `className` that changes based on current `step`, letting you customize also that `rect` based on it.

**Comment by RituBhawsar** [comment]
Thanks @elrumordelaluz,Yeah it's better to have the dynamic className and for now i have accessed the highlighted element and applied css for each step with the help of getCurrentStep function.
