### ISSUE TITLE
How to reset to first (or any) step on reopening

### ISSUE THREAD

**Issue by nelsonwong1012** [elrumordelaluz/reactour#281]
When the tour closes and then reopens, I want it to reset to the first step rather than the step it was at when it closed. Is there an easy way to do this without re-rendering the component?

**Comment by elrumordelaluz** [comment]
> Try adding this prop:
> startAt={0}

☝️

**Comment by nelsonwong1012** [comment]
@koiski @elrumordelaluz Ah, I had already tried `startAt={0}` and it did not work and I realize it's because I'm using the code on the `master` branch. It does work with `1.18.0`. Was this feature intentionally removed on `master` or is this a bug?

**Comment by elrumordelaluz** [comment]
mosltly problably a `bug` :(

**Comment by elrumordelaluz** [comment]
Please take a look into `useTour` hook in the **new v2 version** released under scoped `@rectour` package name, try `npm i @reactour/tour`. Every feedback super welcome, thanks!

**Comment by caespinozaml** [comment]
Try @nelsonwong1012  setCurrentStep(0) before setIsOpen(true) ☝️
