### ISSUE TITLE
[NEED INFO]: How can I call my function on clicking next step arrow.

### ISSUE THREAD

**Issue by QasimRRizvi** [elrumordelaluz/reactour#284]
I saw in props we have nextStep function, but this function overrides the default.
Do we have something like onNextStep function? So we have default functionalities of nextStep function but also we can do something after clicking the next step arrow.

**Comment by SalmanMehmood** [comment]
You can implement custom next and previous button functionality like this.

`function TourGuide(props) {
    const [current, setCurrent] = useState(0);

    const handlePrevStep = () => {
        setCurrent((prev) => {
            let prevStep = prev > 0 ? prev - 1 : prev;
            return prevStep;
        });
    };

    const handleNextStep = () => {
        setCurrent((prev) => {
            let nextStep = prev < tourGuide.length - 1 ? prev + 1 : prev;
            return nextStep;
        });
    };

    return (
        <Tour
            steps={stepsArray}
            isOpen={showTourGuide}
            prevStep={handlePrevStep}
            nextStep={handleNextStep}
            goToStep={current}
        />
    );
}`

**Comment by QasimRRizvi** [comment]
@SalmanMehmood thx :+1:
