### ISSUE TITLE
I need add alone 2 position.

### ISSUE THREAD

**Issue by christiantigre** [elrumordelaluz/reactour#285]
I need add alone top and left position, but not work.
I try
```
{
      selector: "#mySelector",
      content: `my text descrition`,
      position: ['top', 'left'], // alone top and left. 
      action: () => myEvent(),
    },
```

**Comment by elrumordelaluz** [comment]
Hi @christiantigre, thanks for open the _Issue_.

At the moment you could pass [one of 'top', 'right', 'bottom', 'left', 'center'](https://github.com/elrumordelaluz/reactour/blob/master/src/propTypes.js#L44-L47) or an Array of `[x,y]`.

Closing but feel free to re-open in any case.
