### ISSUE TITLE
Next.js Support

### ISSUE THREAD

**Issue by frankyso** [elrumordelaluz/reactour#286]

**Comment by thibaultadet** [comment]
I'm not sure you can import a package with the `dynamic` option, it didn't work for me.
You need to create a component thats holds the package.
That's how it worked for me, I created an `AppTour` component:
```javascript
import Tour from "reactour";

import steps from "utils/tourSteps";

const AppTour = ({
  open,
  setOpen,
}) => {
  return (
    <Tour steps={steps} isOpen={open} onRequestClose={() => setOpen(false)} />
  );
};

export default AppTour;
```

and imported it with `next/dynamic`:
```javascript
// ...other imports

const AppTour = dynamic(() => import("components/AppTour"), { ssr: false });

// ... your app component
```

**Comment by sreimer15** [comment]
I'm getting the invalid hook call error when using with nextjs and dynamic imports. I've isolated to this component. Does anyone know if anything has changed?

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.


```js
import dynamic from "next/dynamic";
const Tour = dynamic(() => import("reactour"), { ssr: false });

export const IntroTour = () => {
  const steps = [] as any;
  const tours = { state: { isIntroTourOpen: false }, dispatch: (x: any) => {} };
  return (
    <Tour
      steps={steps}
      isOpen={tours.state.isIntroTourOpen}
      onRequestClose={() => tours.dispatch({ type: "introTourToggle" })}
    />
  );
};

export default IntroTour;

```
