### ISSUE TITLE
Second dot is getting focused (displaying black border) in navigation bar

### ISSUE THREAD

**Issue by utkarsh22garg** [elrumordelaluz/reactour#288]
As seen in the image below a black border comes in the second dot of the navigation bar (even on demo page)
![image](https://user-images.githubusercontent.com/31355903/93457044-271ed300-f8fc-11ea-9bc9-6f289f40d3e4.png)

This border doesn't appear suddenly when you open the tour. To recreate the following issue in the demo page follow these steps:

1. Click on **Try It**.
2. Now switch to different tab.
3. Now again go back to the previous tab in which we just have opened the tour.

After following these steps you can see the black border on the second dot.

I believe this if being focused somehow. Anyone know how to remove this issue

**Comment by mhmt** [comment]
You can override it with outline:none property. Here is an example in scss. You can add this container class to className property of Tour component and it overrides outline property in arrows and dots.

`.UITourContainer {
    :global {
        [data-tour-elem="right-arrow"],
        [data-tour-elem="left-arrow"] {
            outline: none;
        }
        .reactour__dot {
            cursor: default;
            outline: none;
        }
        .reactour__dot--is-active {
            height: 12px;
            width: 12px;
            border-radius: 50%;
        }
    }
}`

**Comment by utkarsh22garg** [comment]
That's a great solution. But I believe this is a kind of hack solution. In the first place it should not be getting focused. If we override its outline then while using keyboard to navigate the dots the border will not be visible.

**Comment by mhmt** [comment]
I think border is really unneccessary. I want to get rid of it completely. But in your case you are right. Maybe someone else can provide a solution for it. Good luck :)

**Comment by utkarsh22garg** [comment]
Any updates here ?

**Comment by elrumordelaluz** [comment]
Hi @utkarsh22garg, I'm sorry for the late reply.
Should be fixed in `v1.18.2`.

Feel free to re-open in any case.
