### ISSUE TITLE
On mobile version only after change resolution it updates and make normal position of mask and container with tip

### ISSUE THREAD

**Issue by ponochovny** [elrumordelaluz/reactour#290]
I have a page, i open chrome devtools and mobile size, start tour and my block is first, at the start of the page, it highlighted but container with tip is outsite the page, and once i change resolution - it updates and looks ok.
Also tried on my android with chrome browser. Same, fitst - bad mast and container tip position - once i rotate device - it updates and looks ok

Using react & mobix

**Comment by ponochovny** [comment]
Also in modal i have a block to show in tour. and this block is modal content that need to be scrolled to be shown, modal when opened has some space at the bottom, so tour just shows half of the content i want to show, and there i need to scroll down to see full content that in this step

**Comment by ponochovny** [comment]
I think it's about to add 'offset' feature to scroll

**Comment by ponochovny** [comment]
Okay, i found the solution. Remove scroll-behavior: smooth from html tag. but would be good if u would find sime fix

**Comment by elrumordelaluz** [comment]
Hi @ponochovny, thanks for open the _Issue_.

Seems a duplicated of #252

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
