### ISSUE TITLE
`prevButton` / `nextButton` are actually labels

### ISSUE THREAD

**Issue by KATT** [elrumordelaluz/reactour#291]
I noticed I got errors from React because I have nested `<button>`s as `prevButton={<Button [..] />}` will actually render two buttons, one from my component library and one from `reactour`.

## Suggestion

- Change `prevButton` to `prevButtonLabel`
- Add `renderPrevButton` that can actually handle the whole button flow 

Will do a PR with what I'm thinking

**Comment by elrumordelaluz** [comment]
I am closing this _issue_ prioritizing all the changes in `v2` that solves this, but feel free to re-open or create a new one in any case.
