### ISSUE TITLE
Cannot use observe prop when content is injected into DOM.

### ISSUE THREAD

**Issue by JoshuaWarejko** [elrumordelaluz/reactour#295]
Having an issue implementing a few steps in my tour.

Upon going to a specific step, a modal is triggered to open via updating the state inside the `action` function for the step.
For this particular step, I set the `observe` prop to an element inside the modal, but an error is thrown and the app crashes when changing to the step. I believe this is happening because the modal content is not in the DOM until the state is updated for it to display.

![image](https://user-images.githubusercontent.com/11915837/95928597-9f9b7700-0d76-11eb-97ac-91e6682444f9.png)

The error makes sense, but I am wondering if there is a way to debounce the step opening and run the action first? Or if there is another suggested way to handle this.

**Comment by Jopzik** [comment]
Yep, there should be a way to manage observe for node that was injected, @elrumordelaluz

**Comment by elrumordelaluz** [comment]
Please take a look into **new v2 version** released under scoped `@rectour` package name, try `npm i @reactour/tour`. Every feedback super welcome, thanks!
