### ISSUE TITLE
Incorrect scrolling on iOS

### ISSUE THREAD

**Issue by Cyral** [elrumordelaluz/reactour#296]
When scrolling to out-of-view elements, the highlighted area is not positioned correctly.

This can be seen on the demo, click the last step and you will see that the highlighted area is above the button.

![IMG_0564](https://user-images.githubusercontent.com/4945029/96286151-f343d580-0fad-11eb-8c62-3f538aac29d1.jpg)

**Comment by haxxxton** [comment]
cannot replicate on ios 13.7 on iPhone 7. tested on both latest Safari and Chrome

**Comment by Cyral** [comment]
This occurs on iOS 14.0.1 on an iPhone Xs Max for me

**Comment by haxxxton** [comment]
Can confirm since moving to 14.1.0 im now experiencing the same issue as described @Cyral on my iphone 7

**Comment by joanargarrido** [comment]
Same problem in iOs 14.4. @elrumordelaluz Can you please check it?

**Comment by LordA98** [comment]
Also happening on my iPhone XR iOS v14.4.2.  I also tested on a Samsung A5 Android v8.0.0 and I did not get this issue.

Did anyone find a temporary fix for this? @Cyral @haxxxton @joanargarrido

**Comment by elrumordelaluz** [comment]
I now can replicate on iOS 14.4.2, investigating.

**Comment by elrumordelaluz** [comment]
Please try **new v2 version** released under scoped `@rectour` package name `npm i @reactour/tour`. Every feedback super welcome, thanks!
