### ISSUE TITLE
[Feature Request] Pass rendered position (direction) to CustomHelper

### ISSUE THREAD

**Issue by haxxxton** [elrumordelaluz/reactour#297]
It would be great to be able to get the position (ie. the direction of the step) passed in as a prop to CustomHelper. This would aid in adding things like directional triangles to the CustomHelper to "point" to the area in the mask.

It's my understanding that it is not enough to simply pass the defined step position value through to CustomHelper, as the actual rendered position of the Helper is smart, and will change the provided step position so that the Helper is visible within the viewport.

**Comment by haxxxton** [comment]
To add more details to this: You'll note the little top caret that is aligned to the left in this screenshot. This would be the intention of passing the rendered position through to a CustomHelper. The CustomHelper would be responsible for rendering the caret, but needs to know which position and direction to render it. The current code that detects the viewport is awesome, and moves the Helper so that it always id displayed on screen, this means you cant simply copy the 'intended' direction value to the CustomHelper, as when it gets positioned for the viewport it's likely to be pointing in the wrong direction

![image](https://user-images.githubusercontent.com/743105/97065458-c6687180-15f0-11eb-9801-ac94f2632d16.png)

**Comment by elrumordelaluz** [comment]
Hi @haxxxton, thanks for open the _Issue_.
This is a crucial point where I am working with. You'll have available the not only the position passed by user (or the `left` default) but also the final calculation and alignment. 

Will back to you as soon as I deploy it.

**Comment by elrumordelaluz** [comment]
Closed and explined in #299
