### ISSUE TITLE
[Feature Request] Add corner positions

### ISSUE THREAD

**Issue by haxxxton** [elrumordelaluz/reactour#299]
It would be great to be able to specify more specific positioning of the Helper relative to the node (eg. 'bottom-right', 'left-top', etc.)

**Comment by haxxxton** [comment]
To add more details to this: You'll not the little top caret that is aligned to the left in this screenshot. This would be the intention of a 'bottom-left' alignment. ie. position the Helper at the bottom of the selected element, then align to the left of the selected element.

![image](https://user-images.githubusercontent.com/743105/97065385-3e826780-15f0-11eb-84f0-dac47c5c0e99.png)

**Comment by elrumordelaluz** [comment]
Hey, sorry for the pretty late reply. Now this is doable using `@reactour/tour@2.x`, customizing [styles](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#styles-stylesobj--popoverstylesobj--maskstylesobj-1). [Here](https://reactour.vercel.app/#custom-popover-styles) is the example on the _Popover_ demo.
