### ISSUE TITLE
Skip the step if the node is not found

### ISSUE THREAD

**Issue by hip1310** [elrumordelaluz/reactour#30]
New feature request!!
We have some divs which are rendered only sometimes. We want to show the tour step for those if they are being displayed. If they are not being rendered just move to the next step.

**Comment by elrumordelaluz** [comment]
hey @hip1310, first of all thanks for the _feature request_.
Today you could do something like

```
steps = [
  { // step },
  ...condition ? [
     { // step },
     { // step },
  ] : [
    { // alternative step },
    { // alternative step },
  ]
```

Remember to fire the `update` prop.
Let me know if this make sense.

However, the future new API will take this in count to make it in a more flexible way.

**Comment by hip1310** [comment]
When the new API is coming out with this feature added? We are waiting for it.

The reason we can't use your suggested solution is, we create tour for a particular react component using higher order component.
