### ISSUE TITLE
Ionic capacitor ios problem

### ISSUE THREAD

**Issue by FernetB** [elrumordelaluz/reactour#300]
Hey folks!

I'm here with an issue/feature (I don't know if i can call it an issue because this library is not intended to work correctly in an app made with capacitor ) but here is the thing.

The tour i made work just fine in both chrome and safari, but when i build the ionic app with capacitor and then test it in mobile the element that are meant to be highlighted are not highlighted and i can't interact with it, all the other things works just fine.

(The element that meant to be highlighted is found in the dom)

Someone has any idea of what can be happening? 

Sorry for my english!

Pd: I putted the '/feature' because if it is not a bug and is just because is not implemented it could be added and this package will be useful not only for browsers but also for capacitor/cordova apps.

**Comment by FernetB** [comment]
You can close this, i just upgrade the iphone version from 12.1 to 14.1 and the bug fix it!

Awesome job, love this package!

Cheers!

**Comment by elrumordelaluz** [comment]
Cool to hear it work fine also in that kind of apps! Feel free to re-open in any case.
