### ISSUE TITLE
Is there a way to disable next button for a particular step?

### ISSUE THREAD

**Issue by narghev** [elrumordelaluz/reactour#301]
Hi, I am working on a demo and have some steps where I WANT the user to click on the highlighted area and perform an action. I have already figured that part by passing a ref and calling `ref.nextStep()`. Now the problem I have is that the user can just click away from that step without taking the action. Is there a way to disable it?
Also note that I do not want to disable the next button for the entire flow just some particular steps.

**Comment by siemano1** [comment]
I managed to achieve that by conditionally setting a class name and then hiding the next button based on that class

**Comment by narghev** [comment]
> I managed to achieve that by conditionally setting a class name and then hiding the next button based on that class

Thanks for the hack. You did that in action?

**Comment by farrukhayazqazi** [comment]
@siemano1 could you please elaborate with some example?
