### ISSUE TITLE
can't interact and close the step once clicking on the Mask

### ISSUE THREAD

**Issue by benyael15** [elrumordelaluz/reactour#305]
https://github.com/elrumordelaluz/reactour/blob/ee4b15e819cf3933436f4f24ba670ab1c22f158a/src/Tour.js#L282

when StepInteraction (per step) is true, and the DisableInteraction of the Tour component is false - 
according to this line i should be able to interact with the Mask and close the tour once i click it - 
somehow it doesnt happen

thinking somehow cause the classname maybe exist.. 

function maskClickHandler(e) {
    if (
      closeWithMask &&
      e.target.className.baseVal
        .split(' ')
        .indexOf(CN.mask.disableInteraction) === -1
    ) {
      close(e)
    }
  }

**please check this closeing with mask capability**

**Comment by yanickrochon** [comment]
Is this issue still relevant?

**Comment by elrumordelaluz** [comment]
It refers to the old version and I didn't check already. Help is pretty welcome. Let me know if you think we could close it. Thanks!

**Comment by yanickrochon** [comment]
Perhaps issues should be tagged with the major version (i.e. 1 or 2) so they can properly be triaged, and closed when stale?

**Comment by elrumordelaluz** [comment]
cool, done! now I'll have to navigate on all the issues to tag'em.

thanks @yanickrochon for the input!

**Comment by elrumordelaluz** [comment]
However on my end works as [expected](https://codesandbox.io/s/reactour-demo-template-live-forked-s0bqq?file=/styles.css). I am closing this _issue_, but feel free to re-open or create a new one in any case.
