### ISSUE TITLE
Highlighted selector has shadow

### ISSUE THREAD

**Issue by antonjohanssonse** [elrumordelaluz/reactour#308]
Hai, great repository, everything works as intended for me except the highlighted area, I can put a border around it but its not removing the shadow correctly.

Let me show you how it looks like
<img width="127" alt="Screenshot 2020-11-19 at 11 21 07" src="https://user-images.githubusercontent.com/40592120/99653493-5e734280-2a59-11eb-948e-0a0c0d1f52e7.png">

I would like it to be transparent, like in the example.
![Screenshot 2020-11-19 at 11 24 07](https://user-images.githubusercontent.com/40592120/99653843-d6da0380-2a59-11eb-9f8f-e1db3abd3c9c.png)

My ReactJS code:

```
<Tour
                        onRequestClose={this.closeTour}
                        steps={tourConfig}
                        isOpen={this.state.isTourOpen}
                        className="reactour-helper"
                        rounded={5}
                        accentColor="#ffc551"
                        onAfterOpen={this.disableBody}
                        onBeforeClose={this.enableBody}
                        highlightedMaskClassName="highlightedMask"
                        disableInteraction={true}
                    />
```

CSS
```
.reactour-helper {
    line-height: 1.3;
    color: #2d2323;
}

.highlightedMask {
    stroke: @sts;
    stroke-width: 3px;
    rx: 6px;
}
```

Thank you!

**Comment by elrumordelaluz** [comment]
Sorry for the late reply. However I checked the settings in [v1](https://github.com/elrumordelaluz/reactour/tree/v1) and work as expected.

Due to inactivity I am closing, but feel free to re-open or create a new one in any case.
