### ISSUE TITLE
Hide Close button on every step

### ISSUE THREAD

**Issue by stfny222** [elrumordelaluz/reactour#31]
I think this is not possible right now, so I guess this is a feature request.

It would be really helpful to include a property to hide the Close button, so we can fully manage the tour open state, and prevent the user from skipping steps if necessary.

**Comment by elrumordelaluz** [comment]
Hi @stfny222, thanks for the _issue_.
yes, right now there isn't an explicit way to hide the `x` close button. 
It should be simple to add a `prop` like `showCloseButton`, similar to `showButtons`, `showNavigation ` and so on. (PR super happily welcome).
However for the [next version](https://github.com/elrumordelaluz/reactour/milestone/1) I want to offer a more granular way to compose the _helper_.

A tricky way is to take advantage of the _Tour_ `className` prop to hide the _close button_ with `css`, supposing you have `className="my-helper"`, then in the _stylesheet_, something like: 

```css
.my-helper > button {
  display: none;
}
```
Taking in count that the `> button` generic selector could catch any other `button` direct children of the _helper_. But if you are sure that don't have this situation, you could do. 

Remember also to disable interaction adding `closeWithMask={false}` prop.

Let me know if this make sense for you and thank you again for the _feedback_.

**Comment by davej** [comment]
@elrumordelaluz: Rather than an option to simply hide the button it may be more useful to provide a `className` for the close button. This would mean that we could also restyle the button rather than just hide it. For the moment, I will use the `.my-helper > button` hack.

**Comment by elrumordelaluz** [comment]
@davej absolutely, will try to give an eye in the next days to apply changes I have in mind for the _Helper_ component.

**Comment by elrumordelaluz** [comment]
solved in #89
