### ISSUE TITLE
Support for React v17

### ISSUE THREAD

**Issue by richardantao** [elrumordelaluz/reactour#311]
Hello, please add support for React v17 in the next version.

```
npm WARN reactour@1.18.0 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN reactour@1.18.0 requires a peer of react-dom@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN reactour@1.18.0 requires a peer of react-is@^16.8 but none is installed. You must install peer dependencies yourself.
```

**Comment by yairEO** [comment]
Hello? is there anybody out there? `reacttour` is uninstallable for people with React `v17` and this issue is open since November... is this project abandoned?

**Comment by elrumordelaluz** [comment]
hi @richardantao, thanks for opening the _issue_.
Mind [open a PR](https://twitter.com/wesbos/status/1359173446740172810?s=20) in order to solve this?

thanks!

**Comment by richardantao** [comment]
PR made!

**Comment by elrumordelaluz** [comment]
Thank you!
