### ISSUE TITLE
Problem focusing element outside viewport

### ISSUE THREAD

**Issue by diegoolavarria** [elrumordelaluz/reactour#313]
Hi, first of all, good job, this is a really cool library

The tour boxes work perfectly for elements inside the viewport. The problem is with elements outside the viewport, or that render beyond the limits of it. When the next step is outside the current viewport, the hint box moves beyond the bottom limit, and I have to use the right-arrow key from the keyboard to be able to show it.

Las cajas del tour funcionan perfectamente cuando el elemento se encuentra dentro del viewport. El problema está cuando los elementos se encuentran fuera del viewport o abarcan un área fuera de éste. Cuando paso al siguiente paso del viewport, la caja del tour se mueve más allá del límite de la página. Si uso la tecla de flecha-derecha, la caja aparece junto al elemento como corresponde.

**Comment by diegoolavarria** [comment]
![Captura del escritorio de 03-12-20 14_29_26](https://user-images.githubusercontent.com/15364801/101041841-70ce9f80-3574-11eb-9dc9-4d23f01b2bb4.gif)

**Comment by diegoolavarria** [comment]
![Captura del escritorio de 03-12-20 14_52_07](https://user-images.githubusercontent.com/15364801/101044666-872a2a80-3577-11eb-9faf-c8457035a448.gif)

**Comment by bermann** [comment]
is there any news on this?

**Comment by utazabanje** [comment]
I know this thread is old, but in my case, I had on my <html> tag `scroll-behavior: smooth`. Once I removed it, this problem disappeared.

**Comment by elrumordelaluz** [comment]
This should be solved in `v2`. Every feedback super welcome, thanks!
