### ISSUE TITLE
[Feature] let user can define the range of the mask

### ISSUE THREAD

**Issue by jzsplk** [elrumordelaluz/reactour#315]
in a use case, we want the mask not to block the whole `window`.
but a part of the screen.
in this case, if we change the SVG size by CSS.
the calculate of the highlight element will be in the wrong place.

**Comment by elrumordelaluz** [comment]
This is now easily doable in **new v2 version** released under scoped `@rectour` package name, please try `npm i @reactour/tour`. Every feedback super welcome, thanks!
