### ISSUE TITLE
Waiting for the user to take an action before next step

### ISSUE THREAD

**Issue by joeynimu** [elrumordelaluz/reactour#318]
First and foremost, I'd like to appreciate the work done on this wonderful project. I really like it so far.

I am wondering if there is a way to wait for a user to take some action before the next step. For instance, say the first step shows the user how to search for some data via an input field, is there a way I can wait until they search before showing the next step? How would you recommend achieving this?

**Comment by LordA98** [comment]
Yeah, also wondering the same thing.  Did you find a solution @joeynimu?

**Comment by Emiltayeb** [comment]
exactly what im tring to accomplish.
has anyone figure it out?

**Comment by Tpuljak** [comment]
I was stuck on this problem for a couple of hours also.

The solution for me was to add 
```javascript
disableFocusLock={true}
disableInteraction={false}
```
to the Tour component.

That will enable interaction with the input field that is currently highlighted.

To change the step you need to add an event listener to the input component that will update the state that tracks the step.

For example:
Input A is highlighted as the step 1.

```javascript
inputA.addEventListener('change', () => this.setState({ tourStep: this.state.tourStep++ })
```

**Comment by elrumordelaluz** [comment]
This is now available in **new v2 version** released under scoped `@reactour` package name, please try `npm i @reactour/tour`. Every feedback super welcome, thanks!

**Comment by elrumordelaluz** [comment]
demo https://reactour.vercel.app/#disable-actions
