### ISSUE TITLE
Tour is rendering multiple times

### ISSUE THREAD

**Issue by rohitLuxor** [elrumordelaluz/reactour#321]
Hi there, I've used react tour on my app as a functional component and used that in my class component through 3 levels. It is now rendering 3-4 times. Can you please tell me how to fix this problem.
1st level: My main page(Class component)
2nd level: Main pages children's component(functional component) 
3rd level: Tour component(functional component)

https://user-images.githubusercontent.com/69580162/104545975-39621100-5651-11eb-91be-bc18b9d7a177.mp4

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
I am sorry to missed reply before. In any case, don't hesitate to re-open or open a new _issue_.
