### ISSUE TITLE
Add classname support for a step 

### ISSUE THREAD

**Issue by yairEO** [elrumordelaluz/reactour#322]
it's trivial to want to style a specific spec (the whole DOM of the step and not just the content),
so allow adding `classname` prop.

I would already go further and ask you to simply use the `...rest` to dump all custom properties (like `classname` as props, which will allow any future prop as well

Also, I would expect the current step container to have some sort of index identifier so it could be targeted by CSS.

This is how the container looks now

```html
<div tabindex="-1" class="sc-gHftXq gjays reactour__helper reactour__helper--is-open" role="dialog">
```

I suggest adding `data-step-index="3"` for example, to indicate the step and it would be of high value to also allow named steps, (because index can change) - `data-step-name="foo" and the name would be configurable via the `steps` array of course

**Comment by elrumordelaluz** [comment]
Now you can customize this and other parts, using [components](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#components-popovercomponentstype). Here is a [demo](https://reactour.vercel.app/#custom-components)
