### ISSUE TITLE
App Re-renders every time isOpen state is changed, thereby restarting the tour

### ISSUE THREAD

**Issue by drixie** [elrumordelaluz/reactour#323]
Not sure if anyone else is experiencing this issue. This happens when I use Tour at both top-level and nested components.

**Comment by elrumordelaluz** [comment]
Hi @drixie, thanks for open the _Issue_.

Mind sharing a reduced reproduction, ideally in a codesandbox.

Thanks,

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
