### ISSUE TITLE
Improve the Documentation

### ISSUE THREAD

**Issue by LordA98** [elrumordelaluz/reactour#325]
Hi,

Reactour is a great package but the documentation (or lack thereof) lets it down.  The 'Usage' section of the README does not provide enough examples or enough context to be helpful.

1. Hardly any of the properties have examples and those that do provide only one very simple example.  The descriptions only describe how those individual properties work.  There is not a lot of context to describe which properties should be used together to create specific functionality. 
   
2. Which brings me onto point 2: there are no larger, more applicable examples anywhere.   For example, changing route / URL is not very intuitive at all.  Using the 'update' property it not intuitive.  How do we open a modal and focus on it?   These are the types of specific commonly-used functionality that I feel should be given their own examples. 

The demo is amazing, but it doesn't provide any example code to see how those things are done (not that I can easily find anyway).

I apologise if there is more documentation somewhere, but I cannot find it very easily.

**Comment by LordA98** [comment]
To add to that, not all functionality is even in the documentation. 

For example, looking at the `index.d.ts` file, there are two other parameters that you can pass to `content` on top of the `goTo` and `inDOM` parameters:

```
close: () => void;
goTo: (step: number) => void;
inDOM: boolean;
step: number;
```

`close` and `step` are both not mentioned in the README documentation at all.

**Comment by kylekirkby** [comment]
@LordA98 I think there needs to be some delegation of ownership of this project. @elrumordelaluz

**Comment by elrumordelaluz** [comment]
Hi all, this should be solved in the **new v2 version** released under scoped `@rectour` package name, please try `npm i @reactour/tour`. Every feedback super welcome, thanks!
