### ISSUE TITLE
Changelog for 1.18.3

### ISSUE THREAD

**Issue by nypinstripes** [elrumordelaluz/reactour#334]
Hello @elrumordelaluz ,

We started using reactour widely in our repo in recent months and have made several workarounds to achieve different tasks based on the 1.18.1 readme documentation. I'm a little nervous about upgrading to 1.18.3 without a changelog or updated readme docs. Will there be a changelog, release notes or an updated readme for 1.18.3? I'm also anxious and excited to use the new features & capabilities, as soon as i can tell my team what they are and how to use them.

Thanks.

**Comment by elrumordelaluz** [comment]
Hey @nypinstripes, **new v2 version** released under scoped `@rectour` package name, please try `npm i @reactour/tour`. Every feedback super welcome, thanks!
