### ISSUE TITLE
RTL support 

### ISSUE THREAD

**Issue by yairEO** [elrumordelaluz/reactour#340]
Please add a prop for `rtl` mode, so when `direction:rtl` is applied, the navigation buttons won't need to be rotated via CSS.

Also please flip the arrows' callbacks, so in `rtl` the "next" step should be binded to the *left* arrow and *right arrow should go to previous step.

Thanks! :)

**Comment by elrumordelaluz** [comment]
This is now available in **new v2 version** released under scoped `@rectour` package name, please try `npm i @reactour/tour`. Every feedback super welcome, thanks!

**Comment by elrumordelaluz** [comment]
demo https://reactour.vercel.app/#rtl
