### ISSUE TITLE
Change the size of the popup box

### ISSUE THREAD

**Issue by yingying96** [elrumordelaluz/reactour#344]
Hi Team,

May i know how do we change the size of this box?

![image](https://user-images.githubusercontent.com/19566726/117949715-fdac2f00-b344-11eb-9fe7-ff4daf1f7b56.png)

**Comment by elrumordelaluz** [comment]
Hi @yingying96, thanks for open the _Issue_.

You could stylize through the [className](https://github.com/elrumordelaluz/reactour#classname)

**Comment by Danjosh0211** [comment]
I had the same issue when attempting to fill a lot of the screen with a gif style tutorial. I gave the helper a className and set it when i needed to:
`className={largeBox ? "reactour_helper_large" : ""}`

`
.reactour_helper_large{
  max-width: 70% !important;
  transform: translate(20%, 10%) !important;
}
`

**Comment by yingying96** [comment]
Thanks for helping to check. Do you think it's wise to do something like this? Use className=".jcRswH"

```
          <Tour
            steps={tourConfig}
            isOpen={isTourOpen}
            onRequestClose={() => setIsTourOpen(false)}
            className=".jcRswH"
          />
```

![image](https://user-images.githubusercontent.com/19566726/118238440-1a726f00-b4cb-11eb-8785-c1c561a7013a.png)

**Comment by yingying96** [comment]
Yup works for me. Thanks alot for the example!
