### ISSUE TITLE
Enable interaction in inputs

### ISSUE THREAD

**Issue by gvargash** [elrumordelaluz/reactour#346]
![image](https://user-images.githubusercontent.com/24488771/118859406-cf2bd800-b89f-11eb-8964-824446fb519a.png)

How could I enable interaction on that input with the active tour. Is that possible?

**Comment by elrumordelaluz** [comment]
Hi @gvargash, thanks for open the _Issue_.

Try adding `disableFocusLock`. In next versions this will be improved as well as the docs.
