### ISSUE TITLE
State Updates in Reactour

### ISSUE THREAD

**Issue by suryacris7** [elrumordelaluz/reactour#352]
Hi , regarding the action prop , how am i supposed to handle the State Updates in here
{
selector: 'toggle_switch',
content: hi hello,
action:()=>{ this.setState({toggle : true}) }
},

Here is my snippet and its executing in an infinite loop ( which is obvious ) and also i want to make my toggle on for this step and also i need to reset all of the state updates either if tour finishes or the user exits the tour

**Comment by elrumordelaluz** [comment]
Hi @suryacris7, thanks for open the _Issue_.

Mind creating a minimal reproduction in a sandbox in order to invertigate further? Thanks!
