### ISSUE TITLE
Update on development status and usage

### ISSUE THREAD

**Issue by eduardobalbo** [elrumordelaluz/reactour#353]
Hello everybody,

I'm using this library and been enjoying it so far, but i couldnt help but notice that the rate of the implementation of new features has slowed down and seems that the issues are increasing a lot.
For my actual project and team, a tour is a must have feature, and i'm choosing **_reactour_** over other libraries because the usage is way more practical and cleaner than many of the others options, but in exchange, it lacks a lot of features that this other librarys that i mentioned already have.

I would like to ask if the development is beeing held down by something, or if we are waiting for a new version or something, and also ask how is the status and ETA on the development of this new version.

Thank you very much for you work, for now i'll keep using and suporting this amazing project.

**Comment by elrumordelaluz** [comment]
Hey @eduardobalbo, **new v2 version** released under scoped `@rectour` package name, please try `npm i @reactour/tour`. Every feedback super welcome, thanks!
