### ISSUE TITLE
How to avoid closing the tour when clicking outside the tour?

### ISSUE THREAD

**Issue by christiantigre** [elrumordelaluz/reactour#355]
I have the problem that users click outside the toru and the tour closes, I need it to stay open when clicking outside the tour.
this is my code tour.

![image](https://user-images.githubusercontent.com/17419095/124167171-5ce70f80-da69-11eb-8bec-5b50bd19f7d3.png)

**Comment by elrumordelaluz** [comment]
Hi @christiantigre, thanks for open the _Issue_.

Try [closewithmask](https://github.com/elrumordelaluz/reactour#closewithmask) set to `false`.

**Comment by IvanYulin** [comment]
`closeWithMask` didnt work for me (v3.0.0) but `onClickMask={() => null}` did

**Comment by elrumordelaluz** [comment]
Updated the link, [closeWithMask](https://github.com/elrumordelaluz/reactour/tree/v1#closeWIthMask) is the same as `onClickMask={() => null}` but for v1
