### ISSUE TITLE
Potential unnecessary console.log introduced in 1.18.5?

### ISSUE THREAD

**Issue by sean-daley** [elrumordelaluz/reactour#356]
Starting with 1.18.5 we are seeing a lot of console.logs being generated by reactour.
It looks like this was added as part of https://github.com/elrumordelaluz/reactour/commit/2d07bb6071e7523e7fbe44c899c1276024c9a8e5 to src/components/Guide.js

Not sure if it was intentional or not but it looks kind of weird.
Thanks.

**Comment by elrumordelaluz** [comment]
Thank you @sean-daley to report this, absolutely not intentional, I'm sorry for this.
Should be fixed in `reactour@1.18.6`.

Thanks again!
