### ISSUE TITLE
Is it possible to drag a step?

### ISSUE THREAD

**Issue by christiantigre** [elrumordelaluz/reactour#357]
I need to drag from left to right on the screen, it is possible?

**Comment by elrumordelaluz** [comment]
Hi @christiantigre, thanks for open the _Issue_.

Sounds like an absolutely awesome _feature request_.

**Comment by elrumordelaluz** [comment]
@christiantigre just to clarify, are you talking about dragging the _Popover_? Thanks,

**Comment by elrumordelaluz** [comment]
Closing but feel free to re-open in any case.
