### ISSUE TITLE
className prop not working

### ISSUE THREAD

**Issue by gusazevedo** [elrumordelaluz/reactour#358]
The className prop are no working unless I use **!important**
```
<Tour
    onRequestClose={closeTour}
    isOpen={isTourOpen}
    steps={tourConfig}
    maskClassName="mask"
    className="helper"
    accentColor="#ff438d"
    rounded={5}
 />
```
```
.helper {
    background-color: hsl(240, 30%, 15%);
    max-width: 400px;
    color: #ffffff;
}
```

![image](https://user-images.githubusercontent.com/26143209/128072277-e0d6d10b-d364-49b2-906e-822c24fc0bd3.png)

**Comment by ShaileshParmar-WebDeveloper** [comment]
try to give `!important` to all the values in class

**Comment by elrumordelaluz** [comment]
Hi @gusazevedo, thanks for open the _Issue_.

Could you please share a sandbox in order to understand why is needed to be more specific using the css className.

Just in case you need to be higher in specificity you could do something like:

```css
.helper.helper {
  /* ... */
}
```
