### ISSUE TITLE
can i resize the window of the selected item as i want?

### ISSUE THREAD

**Issue by kepamuk** [elrumordelaluz/reactour#359]
can i resize the window of the selected item as i want? let's say I still need to grab the bottom element, but I don't want to combine these two elements into one block

**Comment by elrumordelaluz** [comment]
Hi @kepamuk, thanks for open the _Issue_.

Could you please expand a little more the issue, in order to understand at all how to solve it.

Thanks,

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
