### ISSUE TITLE
Incorrect package.json module

### ISSUE THREAD

**Issue by RXminuS** [elrumordelaluz/reactour#365]
I was getting an error in Vite that the package.json has incorrect modules set. They are currently `dist/reactour-tour.esm.js` which doesn't exist. The correct file should be `dist/tour.esm.js` and similarly for the other packages.

**Comment by elrumordelaluz** [comment]
Hi @RXminuS, thanks for open the _Issue_.

Could you please share a little more information, like the version and context or some screenshots or better a minimal reproduction or a sandbox. As shown [here](https://github.com/elrumordelaluz/reactour/blob/master/packages/tour/package.json#L31) the file is correct. 

Thanks in advance,

**Comment by mingzizhennimafan** [comment]
Same problem "@reactour/tour": "2.0.0",

**Comment by elrumordelaluz** [comment]
@mingzizhennimafan could you please expand a little what is the issue, and maybe share an example/sandbox?

**Comment by mingzizhennimafan** [comment]
@elrumordelaluz see: https://codesandbox.io/s/quirky-hofstadter-6y9k3?file=/src/App.tsx

**Comment by elrumordelaluz** [comment]
Now [should work](https://codesandbox.io/s/crimson-sound-d6ned?file=/package.json) on `v2.0.4`, due to invalid `module` file path. Thanks for the input!
