### ISSUE TITLE
i have sidemenu bar which has library , settings , home etc , is it wrong to use data-tut inside map function? its coming out of the focus

### ISSUE THREAD

**Issue by virinchi-manepalli-trysolvio** [elrumordelaluz/reactour#367]
![image](https://user-images.githubusercontent.com/78961690/132886040-b14a30b5-4a62-400c-949d-22d00afd4f03.png)

const navigation = [
  {
    name: "Library",
    href: "/library",
    as: "/library",
    icon: LibraryIcon,
    current: false,
    tourGuide: "reactour__library",
  },

  {
    name: "settings",
    href: "/settings",
    as: "/settings",
    icon: LibraryIcon,
    current: false,
    tourGuide: "reactour__settings",
  },

]

 {navigation.map((item) => (
  
                        <div
                          className={classNames(
                            item.current
                              ? "bg-gray-100 text-gray-900"
                              : "text-gray-600 hover:bg-gray-50 hover:text-gray-900",
                            "group flex items-center px-2 py-2 text-base font-medium rounded-md"
                          )}
                          data-tut={item.tourGuide}
                        >
</div>
)}

**Comment by elrumordelaluz** [comment]
If I understand well, you ca use any CSS selector you want for the steps, like `data-*` or `.step` or `#step`. 

In any case try creating a minimal reproduction if the problem persist and feel free to re-open the _issue_.
