### ISSUE TITLE
firstStepPrevButton

### ISSUE THREAD

**Issue by fostimus** [elrumordelaluz/reactour#368]
There is a `lastStepNextButton` for the last step's next button. It would be nice to have a native prop to control the first step's previous button in the same way.

**Comment by elrumordelaluz** [comment]
Hi @fostimus, thanks for open the _Issue_.

In `@reactour/tour@2.0.0` you have full control over [prevButton](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#prevbutton-props-btnfnprops--void) and [nextButton](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#nextbutton-props-btnfnprops--void).

**Comment by elrumordelaluz** [comment]
Closing but feel free to re-open in any case.
