### ISSUE TITLE
Controls component takes space even if no controls

### ISSUE THREAD

**Issue by yossijacob** [elrumordelaluz/reactour#37]
I remove all controls I still get the control div with a top margin of 24px.
There is no condition on the inclusion of the control component.

https://github.com/elrumordelaluz/reactour/blob/b9d3a2c43ba5e0b7e856dcd7580f55f9dabb6e31/src/TourPortal.js#L441

I would maybe change it to 
`{(showButtons || showNavigation) &&
 <Controls>
    ....
`

**Comment by elrumordelaluz** [comment]
absolutely!

**Comment by yossijacob** [comment]
https://github.com/elrumordelaluz/reactour/pull/44

**Comment by elrumordelaluz** [comment]
🎉
