### ISSUE TITLE
callback called twice when step has target:"body", placement:"center"

### ISSUE THREAD

**Issue by wbolduc** [elrumordelaluz/reactour#371]
https://codesandbox.io/s/amazing-fermi-en5xo?file=/src/Tour.js

This is a fork of the demo branch with a simple reproduction.
Notice the inclusion of Tour.js

I'm not totally sure if this has anything todo with this being controlled.

The tour should start automatically and walk you through the bug

This callback being called twice makes it hard to call imperative code during a step and for this use-case I cannot use the functional style for it

**Comment by elrumordelaluz** [comment]
Hi @wbolduc in this demo you are using `react-joyride`. Probably you have to open this _Issue_ in that repo.

Feel free to re-open in any case.

**Comment by wbolduc** [comment]
My bad, I'm shopping around tour libraries and I didn't realize I had posted the comment in the wrong tab 🤦

Feel free to delete the heck out of this

**Comment by elrumordelaluz** [comment]
No problem at all!
