### ISSUE TITLE
How to resize the highlight ?

### ISSUE THREAD

**Issue by djaffer** [elrumordelaluz/reactour#372]
How do I resize the highlight. I am using the reactour without provider

![image](https://user-images.githubusercontent.com/5740725/133975567-5764df86-39f2-420a-a46f-8ae75b622c9a.png)

```
    <Tour
        steps={tourSteps}
        isOpen={showTour}
        disableInteraction={false}
        disableFocusLock={true}
        startAt={0}

      />
      ```

**Comment by elrumordelaluz** [comment]
Hi @djaffer, thanks for open the _Issue_.

Did you tried [maskSpace](https://github.com/elrumordelaluz/reactour/tree/v1#maskspace)?

**Comment by djaffer** [comment]
thanks for your response. The issue is that I just want just one of the steps to have more space.

![image](https://user-images.githubusercontent.com/5740725/134417379-a77d1ab4-389a-4749-a042-57edebac1229.png)

**Comment by elrumordelaluz** [comment]
Always in `v2` the spaces can be controlled for each `step`, [details](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#padding-padding)

**Comment by elrumordelaluz** [comment]
Closing but feel free to re open in any case.
