### ISSUE TITLE
Fix problem with UNSAFE_componentWillReceiveProps

### ISSUE THREAD

**Issue by ivankuziukfpwd** [elrumordelaluz/reactour#376]
I have a problem with UNSAFE_componentWillReceiveProps, after implementation Tour component, a have a warning in console

```
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: Tour
```

Please fix this problem as recommended React: https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

**Comment by elrumordelaluz** [comment]
This is only a warning, should work everything well beside this.
In a moment I'll try to update this in v1, for now you can use v2.
