### ISSUE TITLE
skip step if it's not visible

### ISSUE THREAD

**Issue by mahboubehsalmani** [elrumordelaluz/reactour#379]
I have some elements (for example a sidebar) in my project which is not visible in smaller screens. Is it possible to skip the steps that refer to sidebar in smaller screen?

**Comment by elrumordelaluz** [comment]
Hi @mahboobehsalmani, thanks for open the _Issue_.

Before go further to develop a solution, which I think is possible or on user-land or adding some logic inside the package, let me know if your sidebar is not present in the DOM (ie. not rendered by a react condition) or is simply hidden using css?

Should be awesome if you can create a minimal reproduction in a sandbox of your use-case with the Sidebar and Tour, in order to analyze possible solutions.

**Comment by manuelurenah** [comment]
This is my workaround
```tsx
/**
 * In utils.ts
 */

/**
 * Checks whether a tour step selector is in the DOM or not
 */
export function isElementInDOM(step: StepType) {
  const nodes = document.querySelectorAll(step.selector);

  return nodes.length > 0;
}

/** 
 * In TourButton.tsx
 */
export function TourButton({ steps }: Props) {
  const { isOpen, setIsOpen, setSteps, setCurrentStep } = useTour();

  useEffect(() => {
    // Reset tour if closed
    if (isOpen === false) setCurrentStep(0);
  }, [isOpen, setCurrentStep]);

  return (
    <TourIcon 
        onClick={() => {
          // Filter out steps that their selector is not in DOM
          const filteredSteps = steps?.filter(isTourStepInDOM) ?? [];

          setSteps(filteredSteps);
          setIsOpen(true);
        }}
    />
  );
}
```

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.

**Comment by adel12790** [comment]
Question that I think is related.

if we have a responsive web side and elements are displayed and hidden as per media query, if we have the selector set as `.className` the highlighter won't pick up what's actually currently displayed and rendered.

It would only pick up the first element in the tree with this class name.

How can we workaround that issue to make the selector focus on what's visible only?

**Comment by elrumordelaluz** [comment]
hey @adel12790, mind creating a minimal reproduction in a sandbox? thanks!
