### ISSUE TITLE
Show badge prop is spelled wrong

### ISSUE THREAD

**Issue by zackharley** [elrumordelaluz/reactour#381]
### Problem

The prop on `Tour` and therefore the `TourProvider` for showing the badge is spelled `showBagde` instead of `showBadge`. Not sure how you want to address this since it will be a breaking change but thought I'd bring it up.

https://github.com/elrumordelaluz/reactour/blob/4ce0c5539e796a2c6a469189ce8fd0eef75cd478/packages/tour/src/Tour.tsx#L41

**Comment by elrumordelaluz** [comment]
Hi @zackharley, thanks for open the _Issue_.

omg what a typo!

**Comment by elrumordelaluz** [comment]
Should be available on `v2.0.2`. Thanks again @zackharley

**Comment by zackharley** [comment]
Thanks for such a quick turnaround!
