### ISSUE TITLE
[V2.0] Steps prop: highlightedSelectors ignores the selector when both DOM elements present

### ISSUE THREAD

**Issue by dmitriifrlv** [elrumordelaluz/reactour#385]
I would like to start by thanking @elrumordelaluz , @qboot and other contributors who put their effort, knowledge and time into this amazing library!

**Description of the issue**

One of the steps of my tour requires a user to click a button and fetch some data. So, we have 2 DOM elements which present on the page at the time of clicking this button :

-DOM element 1 (button)  with a selector '.step1' 
-DOM element 2(data-container)  with a selector '.text'  with some initial data

I want that during this step a user clicks the button(DOM element 1), some data is fetched and then the mask rerenders with a new highlighted area. However, instead of that, I have the highlighted area right on the data container(DOM element 2) at the very beginning of this step. 

**To Reproduce**
I created a sandbox to reproduce described behaviour:
https://codesandbox.io/s/tour-with-data-fetching-jq1nl?file=/src/index.js:225-245

**Expected behaviour**
https://codesandbox.io/s/working-tour-gjtj9?file=/src/index.js:222-242

I would appreciate any suggestions on how to make the sample with data fetching work like the second sandbox.

**Comment by elrumordelaluz** [comment]
Hi @dmitriifrlv, thanks for open the _Issue_.

What a great issue description with examples. 

Thank you also for your kind words. Let me check the sandboxes and back to you.

**Comment by dmitriifrlv** [comment]
> You could do something like [this](https://codesandbox.io/s/tour-with-data-fetching-forked-56dmk?file=/src/index.js)

@elrumordelaluz Hello! Thank you for your help! It works exactly as I wanted now. Do you think this case may be helpful for other users? If so, I'll create PR.

**Comment by elrumordelaluz** [comment]
Sure! thank you.
