### ISSUE TITLE
StepTypes content accepts not ReactElement

### ISSUE THREAD

**Issue by mepaJanitza** [elrumordelaluz/reactour#393]
Hello, i saw that you designed the type of StepType as follows

https://github.com/elrumordelaluz/reactour/blob/38e7e767f849de89757a32b2b193836c4900f175/packages/tour/src/types.tsx#L83

Do you really want to keep it how it is, i would expect , that content could be also an React.ReactElement instead just a string.

**Comment by elrumordelaluz** [comment]
Hi @mepaJanitza, thanks for open the _Issue_.
You are absolutely right, mind make a PR?
Thanks!
