### ISSUE TITLE
Missing react-is dependency.

### ISSUE THREAD

**Issue by richburdon** [elrumordelaluz/reactour#407]
```
 ERROR  reactour@1.18.6 requires a peer of react-is@^16.8 || ^17.0.0-0 but none was installed.
```

**Comment by elrumordelaluz** [comment]
Hi @richburdon, thanks for open the _Issue_.

Yes, in `v1.x` versions this is a [peerDependency](https://github.com/elrumordelaluz/reactour/blob/v1/package.json#L77-L82)
