### ISSUE TITLE
Programatically update position in v2

### ISSUE THREAD

**Issue by aeharding** [elrumordelaluz/reactour#409]
Hello! Thank you for this useful project!

I'm migrating from v1, and in v1 I can programmatically update the position with the `update` attribute on the `Tour`.

I use this when elements are asynchronously added or changed in the dom.

Is it possible to get similar functionality in the `useTour()` of v2? Perhaps a `setUpdate` function that, when changed, will programmatically update the positioning?

**Comment by aeharding** [comment]
Found a hack to use a mutationObserver on each step, changing between 0/1px. But it's really hacky. I'd love an alternative method. :)

<img width="566" alt="image" src="https://user-images.githubusercontent.com/2166114/144467593-dc21f83f-aa3b-4f8d-9613-0925c44f8978.png">

**Comment by elrumordelaluz** [comment]
Hi @aeharding, thanks for open the _Issue_.

Can you please share a reduced reproduction in a sandbox?

Thanks!

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
