### ISSUE TITLE
I am reactour v2, How to prevent the tour from stopping on clicking on the mask?

### ISSUE THREAD

**Issue by vegeta123254** [elrumordelaluz/reactour#410]
I am using reactour version v2.
I understand that there is a **closeWithMask** prop with Tour, in v1.
Is there any similar prop, to prevent the tour from closing on clicking outside the mask?

**Comment by elrumordelaluz** [comment]
Hi @vegeta123254, thanks for open the _Issue_.

You could do it using [onClickMask](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#onclickmask-clickprops-clickprops--void)

```js
onClickMask={()=> {}}
```

**Comment by vegeta123254** [comment]
Worked, Thanks for your valuable suggestion.
