### ISSUE TITLE
Is there a way invoke a function on clicking the close button on the popover?

### ISSUE THREAD

**Issue by vegeta123254** [elrumordelaluz/reactour#413]
I am using reactour v2,
I have placed the **TourProvider** at the app level. 
And used _useTour_ hook to _setSteps_ in different components.
Here is [sandbox](https://codesandbox.io/s/angry-satoshi-0h3l7) link,
I understand that **beforeClose** method can be used, to do something just before tour ends. 
But how can I make a different HTTP request on each component , on clicking the close button on the helper popover.

**Comment by elrumordelaluz** [comment]
`onClickClose` should be available on `@reactour/tour@2.4.0`.

[Here](https://reactour.vercel.app/#close-click) is the example.
