### ISSUE TITLE
Is it possible to focus on multiple doms in one step?

### ISSUE THREAD

**Issue by naopin** [elrumordelaluz/reactour#416]
Is it possible to focus on multiple doms in one step?

Exsample1
<img width="266" alt="スクリーンショット 2021-12-27 19 28 08" src="https://user-images.githubusercontent.com/63636652/147463051-a9b4b145-e3fc-4631-a67a-4638a1820ef9.png">

**Comment by elrumordelaluz** [comment]
Hi @naopin, thanks for open the _Issue_.

It is possible using [highlightedSelectors](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#highlightedselectors-string) prop on your `step`. Keep in mind that the _Mask_ will be calculated with a combination of both bounding box, not clipping each one individually.

duplicated #113

**Comment by naopin** [comment]
Thank you for your reply!!

Is there a readme for the highlightedSelectors ?

In addition, is it possible to focus on multiple doms with just <Mask> without using <Tour>? 
If you use multiple <masks>, you can only see the first <mask>. This is because the opacity: 0.7 overlaps. Is there a way around it?

**Comment by elrumordelaluz** [comment]
demo: https://reactour.vercel.app/#highlighted-selectors

**Comment by elrumordelaluz** [comment]
Could you explan this:
> In addition, is it possible to focus on multiple doms with just without using ?

and 
> If you use multiple , you can only see the first . This is because the opacity: 0.7 overlaps. Is there a way around it?

**Comment by naopin** [comment]
I'm sorry. Change the question.
With this setting, only Mask of size1 will be displayed.
In order to display the size2 mask, you need to comment out the size1 mask.
` {/* <Mask sizes={size1} /> */}`

Is it possible to display size1 and size2 masks at the same time?

![スクリーンショット 2021-12-27 22 40 01](https://user-images.githubusercontent.com/63636652/147477172-e428863e-33a3-4007-b3c2-5e3328a628bd.png)

**Comment by elrumordelaluz** [comment]
If I understand well, since is a question related on [Mask](https://github.com/elrumordelaluz/reactour/tree/master/packages/mask) Component, could you please close this _issue_ and open a new one? Thanks!
