### ISSUE TITLE
Is it possible to display multiple Masks?

### ISSUE THREAD

**Issue by naopin** [elrumordelaluz/reactour#417]
With this setting, only Mask of size1 will be displayed.
In order to display the size2 mask, you need to comment out the size1 mask.
{/* <Mask sizes={size1} /> */}

Is it possible to display size1 and size2 masks at the same time?
![スクリーンショット 2021-12-27 22 40 01](https://user-images.githubusercontent.com/63636652/147485218-22d40deb-9488-4b03-9cc6-d9bba08f13da.png)

**Comment by elrumordelaluz** [comment]
@naopin thank you for pointing this out. There was an error with the `mask` and `clipPath` ids. Now should be solved using `@reactour/mask@0.4.0`. [Here](https://reactour.vercel.app/#more-masks) is the example.
