### ISSUE TITLE
How to use the highlighted selector

### ISSUE THREAD

**Issue by naopin** [elrumordelaluz/reactour#418]
I want to focus on multiple buttons in 1 step
However, it doesn't work with the photo code.
Please point out the mistake.

<img width="663" alt="スクリーンショット 2021-12-28 11 53 22" src="https://user-images.githubusercontent.com/63636652/147522829-762aedbf-6de4-4975-aaf6-c3d3627b10e9.png">

**Comment by naopin** [comment]
In addition, is it possible to forcus only button1 and button3 by using highlightedSelectors?

<img width="663" alt="スクリーンショット 2021-12-28 11 53 22" src="https://user-images.githubusercontent.com/63636652/147524149-a91f6926-4ad3-4758-a490-df4082c08dc5.png">

**Comment by elrumordelaluz** [comment]
@naopin mind creating a condesanbox in order to use as a base to apply examples? thanks!

**Comment by elrumordelaluz** [comment]
I think [this sandbox](https://codesandbox.io/s/tour-with-data-fetching-forked-kq69n?file=/src/index.js) could be useful. Let me know,

**Comment by naopin** [comment]
@elrumordelaluz 
Thank you!!!!
Is it possible to focus the upper and lower buttons separately if the middle button is unchecked?

<img width="213" alt="スクリーンショット 2022-01-05 13 17 38" src="https://user-images.githubusercontent.com/63636652/148159912-9e874d0b-4c78-4eb3-a5b0-d1cf449f050a.png">

**Comment by elrumordelaluz** [comment]
As noted [here](https://github.com/elrumordelaluz/reactour/issues/416#issuecomment-1001528235).

> Keep in mind that the Mask will be calculated with a combination of both bounding box, not clipping each one individually.

It's related on how _Mask_ is calculated. For those cases, the internal calculations should generate more than one mask. Maybe in a future this will be considered. Obviously PR welcome.
