### ISSUE TITLE
how can I automatically trigger the Tab component of bootstrap in my tour

### ISSUE THREAD

**Issue by namanappbroda011** [elrumordelaluz/reactour#419]
My app consists of a multiple tabs on a single page which does not include change of path name so how can I automatically trigger the tabs during my tour?

**Comment by elrumordelaluz** [comment]
Hi @namanappbroda011, thanks for open the _Issue_. Mind creating a sandbox with your example? Thanks

**Comment by namanappbroda011** [comment]
yes sure. [Here](https://codesandbox.io/s/stoic-brook-r7n5f?file=/src/App.js) is my code please have a look! I want to trigger the tab during the tour.

**Comment by elrumordelaluz** [comment]
I found something like the starter sandbox in your link, maybe I am missing something?

![Screenshot 2022-01-12 at 21 36 18](https://user-images.githubusercontent.com/784056/149217811-7f5749f5-499b-4128-a359-78c7d943b674.png)

**Comment by namanappbroda011** [comment]
sorry my code didn't get saved! [here](https://codesandbox.io/s/stoic-brook-r7n5f?file=/src/App.js:1450-1455) is my code!

**Comment by elrumordelaluz** [comment]
Thank you @namanappbroda011. Can you explain a little what is the behavior you are expecting? Like, open the tour and focus on the _Tab 1_ and change step and content, when user triggers the other tabs?

**Comment by namanappbroda011** [comment]
No, I want when user click on the next step during the tour the tab automatically changes and highlight the content of that specific tab.

**Comment by elrumordelaluz** [comment]
[Here](https://codesandbox.io/s/zealous-lovelace-v9u7j?file=/src/index.js) is an example. Keep in mind that you have to use the new version of `@reactour/tour` instead of `reactour@1x`

**Comment by namanappbroda011** [comment]
Thanks man got it!

**Comment by eelkevdbos** [comment]
You can also configure the step with an action if you don't want to rewire the stepping mechanism.

```jsx
<TourProvider
  steps={[
    {
        selector: '[data-tut="second"]',
        content: "...",
        action: () => setTabKey("profile"),
        resizeObservables: ['[data-tut="second"]']
    }
  ]}
>
```

The `resizeObservables` is necessary to do a recalculation of the selected area after switching tabs.

See the [Forked Example](https://codesandbox.io/s/condescending-joana-ebn80e?file=/src/index.js) for full details.
