### ISSUE TITLE
Components as required property when using Typescript

### ISSUE THREAD

**Issue by macmessa** [elrumordelaluz/reactour#420]
I've just started using this great package in a project but I couldn't use the basic configuration following [this example](https://codesandbox.io/s/reactour-tour-demo-using-react-router-dom-kujql) but I've got an error about not providing the components property, that, as the docs says, is a optional parameter.

Here is the error:
![image](https://user-images.githubusercontent.com/13797580/149134781-642c968a-d065-428e-adcb-21eb9e15cf25.png)

And the doc about the property:
https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#components-popovercomponentstype
![image](https://user-images.githubusercontent.com/13797580/149135029-327d3bcc-d4df-4cfb-94c2-c9495ae751a7.png)

Am I doing something wrong?

The type inherited in PopoverComponentsType, the line 35 is a required property:
![image](https://user-images.githubusercontent.com/13797580/149135370-a3903416-392d-414c-ab28-6c74efb3b283.png)

I'll do a PR for this, but please let me know if I'm missing something.

**Comment by elrumordelaluz** [comment]
Should be available on `@reactour/tour@2.7.1`. Please let me know if is fixed and thanks for the catch and the PR!
