### ISSUE TITLE
Actions remain disabled even if step defines disableActions to false

### ISSUE THREAD

**Issue by yanickrochon** [elrumordelaluz/reactour#424]
When every steps in the tour allow user navigation, when a step sets `disableActions: true` and `stepInteraction: true`, the navigation remains disabled for the remaining steps even if `disableActions: false` is explicitly specified.

There is a demo, [here](https://codesandbox.io/s/trusting-sunset-fhit7?file=/src/Demo.tsx).

Basically, the state of one step should not bleed to another step.

**Comment by elrumordelaluz** [comment]
Good catch @yanickrochon, thank you!
Should be solved in `@reactour/tour@2.8.1`, [here](https://codesandbox.io/s/fast-sun-y84dl) is your example forked. 
Let me know in any case.

**Comment by yanickrochon** [comment]
Thanks!

(For reference, if you tag issues in your commits, for example : "Resolves issue #424", then your commits will appear associated with the issue, so people can understand better the changes and resolutions within the code.)

**Comment by elrumordelaluz** [comment]
Cool, thanks for the reference. So you mean that this (img) is not enough?

![Screenshot 2022-01-20 at 15 29 25](https://user-images.githubusercontent.com/784056/150357892-9c7367cb-f269-43f8-859a-b93296769adc.png)

**Comment by yanickrochon** [comment]
If you are using Git CLI, you can create your commit message like this :

```sh
$ git commit -m 'Improve disabledActions check allowing step override. Resolves issue #424'
```
And this will automatically link the commit in the issue (i.e. here). So, whoever is concerned can easily view the changes directly from the issue instead of browser through the project or commit tree.

For example, you can see an example of this (randomly from one of my repository), [here](https://github.com/yanickrochon/promise-events/issues/9).

**Comment by yanickrochon** [comment]
Oh, I guess I was not awake enough, haha! Yes, what you did is fine also. I don't know what you use to manage your Git projects, but it works also.

My bad.

**Comment by elrumordelaluz** [comment]
great! I use the CLI.
