### ISSUE TITLE
Cannot style highlighted area

### ISSUE THREAD

**Issue by kevinRoomies** [elrumordelaluz/reactour#426]
I'm trying to style the highlighted area but I can only pass a callback using props and state? I have no idea how this is supposed to work, the documentation says nothing about it

**Comment by elrumordelaluz** [comment]
You have to pass the key needed into [styles](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#styles-stylesobj--popoverstylesobj--maskstylesobj-1) prop.

For details regarding keys and its documentation, please refer to _Mask_ docs [here](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#styles-stylesobj--popoverstylesobj--maskstylesobj-1).

You could make weird stuff like this:

```js
const styles = {
  maskWrapper: (base) => ({
    ...base,
    color: "purple"
  }),
  maskArea: (base) => ({
    ...base,
    rx: 16
  }),
  highlightedArea: (base, { x, y, width, height }) => ({
    ...base,
    stroke: "blue",
    strokeWidth: 3,
    fill: `url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg'><linearGradient id='grad'><stop offset='0%' stop-color='%23ff00cc'/><stop offset='100%' stop-color='%23333399'/></linearGradient></svg>#grad") purple`,
    display: "block",
    width: width - 10,
    height: height - 10,
    x: x + 5,
    y: y + 5,
    rx: 10
  })
};

// ...

<TourProvider styles={styles} steps={steps} >
  {/* ... */}
</TourProvider>

**Comment by ArutanSipdrae** [comment]
I tried to do that but the style of the highlighted area doesn't change

**Comment by elrumordelaluz** [comment]
@ArutanSipdrae could you please share your code or better a sandbox? thanks!

[Here](https://codesandbox.io/s/tour-tests-kg9qr) is the example

![Screenshot 2022-01-21 at 11 50 55](https://user-images.githubusercontent.com/784056/150514655-fd2d09c3-635b-41c9-ba21-88abadcb826c.png)
.

**Comment by kevinRoomies** [comment]
This is how I initiate my TourProvider

`<TourProvider
            steps={steps}
            className={'ibm subtitle'}
            styles={{
                popover: (base) => ({...base, borderRadius: '0.938rem'}),
                highlightedArea: (base) => ({...base, borderRadius: '0.938rem'}),
                dot: (base) => ({ ...base, border: 'none', background: 'hsl(var(--neon-blue))'})
            }}
            components={{
                Arrow: ({disabled, inverted, styles}) =>
                    <Icon style={styles} name={`chevron-${inverted ? 'right' : 'left'}`}/>
            }}
            disableInteraction={true}
            showCloseButton={false}
            showBadge={false}
        >`

**Comment by elrumordelaluz** [comment]
it works?

**Comment by ArutanSipdrae** [comment]
No it doesn't my highlighted area doesn't have rounded corners

**Comment by elrumordelaluz** [comment]
are you the same person? if not, can you please share your code?

**Comment by ArutanSipdrae** [comment]
I am the same person I'm just logged on another account from another pc

**Comment by elrumordelaluz** [comment]
Keep in mind that the `highlightedArea` isn't visible by default, allowing interaction. maybe you are looking to round `maskArea`, that also works with `rx`.

**Comment by kevinRoomies** [comment]
oh so I need to use that rx/ry... this is not very clear the documentation doesn't mention svg and the mask/popover doc are 404

**Comment by elrumordelaluz** [comment]
I'm sorry about that. Can you tell me where are you getting 404? I can access [Mask](https://github.com/elrumordelaluz/reactour/tree/master/packages/mask) and [Popover](https://github.com/elrumordelaluz/reactour/tree/master/packages/popover) docs and the playground at https://reactour.vercel.app without problems.

Appreciate a lot if you can point where can be improved the docs, also PR welcome!

**Comment by kevinRoomies** [comment]
https://www.npmjs.com/package/@reactour/tour

"Refer to Mask docs and Popover docs for its specific Components"
Both hyperlinks are 404
