### ISSUE TITLE
Where is lastStepNextButton?

### ISSUE THREAD

**Issue by kevinRoomies** [elrumordelaluz/reactour#427]
I come from reactour (v1) but I find nothing on the new version that allows me to do that?

**Comment by elrumordelaluz** [comment]
Hi @kevinRoomies, thanks for open the _Issue_.

In `v2` you could obtain similar results using the generic [nextButton](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#nextbutton-props-btnfnprops--void) prop.

Doing something like this:

```js

function nextButton({ Button, stepsLength, currentStep, setIsOpen }) {
  return currentStep === stepsLength - 1 ? (
    <button onClick={() => setIsOpen(false)}>bye!</button>
  ) : (
    <Button />
  );
}

// ...

<TourProvider steps={steps} nextButton={nextButton}>
   {/* ... */}
</TourProvider>

```

**Comment by kevinRoomies** [comment]
Ah I see. May I suggest to not name the Arrow Component "Button" for those props? Button being a very common component to create if you destructure the props here this can rapidly cause an issue

`nextButton={({stepsLength, currentStep, ...rest}) =>
                currentStep === stepsLength - 1
                    ? <Button
                        text={t('common:button.understood')}
                        variant={'filled'}
                        onClick={() => {}}
                    />
                    : <rest.Button/>
            }`

**Comment by elrumordelaluz** [comment]
maybe `ArrowButton`?

**Comment by kevinRoomies** [comment]
> maybe `ArrowButton`?

That would be less likely to overlap with an existing component indeed, could event go ArrowNextButton just to be sure, and ArrowPrevButton for the prevButton props

**Comment by yanickrochon** [comment]
I may be missing something, but I fail to see the why `prevButton` and `nextButton` aren't defined in `components`?

For example :

```jsx
<TourProvider 
   steps={steps} 
   nextButton={ <Button />    /* <--- why is this here? */ }
   components={{
      NextButton={ <Button /> /* <--- and not here? */ }
      ....
      Navigation: (
         styles, setCurrentStep, steps, currentStep, disableDots,
         nextButton /* <-- HERE is the component returned above */, prevButton,
         setIsOpen, hideButtons, hideDots, disableAll, rtl, Arrow) => { ... }
   }}
>
   {/* ... */}
</TourProvider>
```

**Comment by elrumordelaluz** [comment]
why not!? 👍🏼 

the source is that the `v2` wanted, in some way to maintain `props` from `v1`. But why not move and clean _TourProvider_ props when new features were added (`components` is pretty new).

**Comment by yanickrochon** [comment]
Favor the new props, and fallback to the old ones with a deprecation notice. With a roadmap, devs can plan and refactor ahead of time (especially if the changes are trivial, like in this case).

**Comment by elrumordelaluz** [comment]
more in #430
