### ISSUE TITLE
startAt does not work as expected

### ISSUE THREAD

**Issue by yossijacob** [elrumordelaluz/reactour#43]
If you pass both isOpen true and startAt as the same time you are going to get the tour to open on the previous startAt instead of the one passed in startAt.

I think it is because the open method is called in componentWillReceiveProps. it then get startAt from current props which is not updated yet with the new values. it should get it from the nextProps.

https://github.com/elrumordelaluz/reactour/blob/b830ac3ab681e8f2e28edd64f6078287bfbd0945/src/TourPortal.js#L115

So this line will always get the startAt from the current props before the update

https://github.com/elrumordelaluz/reactour/blob/b830ac3ab681e8f2e28edd64f6078287bfbd0945/src/TourPortal.js#L145

I am not sure but maybe having the open method get the props as a parameter can solve this.

**Comment by yossijacob** [comment]
Here
https://codesandbox.io/s/o48lo6xj7y
the first time you click on the "try it" button is should open step 3 but it wont, it will open step 0.
If  you then close it and open it again only then it will open step 3.

**Comment by elrumordelaluz** [comment]
Ok, got it. 

The point is that the `open` method get the `startAt` declared when the _Component_ mounted, so takes the `step: 0` initialized in the `constructor`.

> I am not sure but maybe having the open method get the props as a parameter can solve this.

I think could be a real solution for this _issue_ pass `startAt` as a parameter on `open` method.

**Comment by yossijacob** [comment]
https://github.com/elrumordelaluz/reactour/pull/45

**Comment by elrumordelaluz** [comment]
Made a little change to pass only the `startAt` number instead of the whole `props` Object.

**Comment by yossijacob** [comment]
I am happy i could help.
