### ISSUE TITLE
Checkbox not working well

### ISSUE THREAD

**Issue by Ibrahim-CloudLabs** [elrumordelaluz/reactour#431]
I'm not sure if this is a bug but I have a controlled input that works outside the steps object, however when I have it inside the content of a selector the checkbox only checks in one way. Not sure why this is happening.

**Comment by yanickrochon** [comment]
Without understanding your configuration and use case, this is difficult to see what you're not sure why something is happening. Please provide a sandbox of what you're trying to accomplish by creating one, or forking [this one](https://codesandbox.io/s/reactour-sandbox-1wmyd?file=/src/App.jsx)

**Comment by Ibrahim-CloudLabs** [comment]
https://codesandbox.io/s/reactour-sandbox-forked-nxs6d?file=/src/App.jsx

**Comment by elrumordelaluz** [comment]
You need to put the `state` inside the `content`. For this you can pass a React function component into `content` like this:

```js
function content() {
  const [checked, setChecked] = React.useState(false);
  return (
    <div>
      <span>
        <input
          type="checkbox"
          checked={checked}
          onChange={(e) => {
            setChecked(e.currentTarget.checked);
            console.log(e.currentTarget.checked);
          }}
        />
      </span>
    </div>
  );
}


const steps = [
  {
    selector: '[data-tour="step1"]',
    content,
  },
  // ...
]


```

[Here](https://codesandbox.io/s/reactour-sandbox-forked-ygcou?file=/src/App.jsx:128-490) is your example modified.

**Comment by Ibrahim-CloudLabs** [comment]
Thanks a lot! One last question :D, How can I have a another tour within my application ?

**Comment by elrumordelaluz** [comment]
You could control `steps` and all the stuff, using the same _TourProvider_, isn't that enough? In that case can you please open another issue sharing a sandbox with a reduced reproduction? Thanks!
