### ISSUE TITLE
Autoscrolling broken in scrollable HTMLElement

### ISSUE THREAD

**Issue by PeterKottas** [elrumordelaluz/reactour#432]
Fix needed in an external library, pr here: https://github.com/Pixeden/scroll-smooth/pull/14 . Once that lands could you please bump the version? Currently, this causes some weird issues when the window is scrolled and the scrollable container isn't. FYI, I am seeing the problem in v1 branch, not sure if this affects or has been resolved in v2.

**Comment by elrumordelaluz** [comment]
Hi @PeterKottas, thanks for open the _Issue_ and for the PR, in `v2` is no more needed this lib.

**Comment by elrumordelaluz** [comment]
Should be available on `reactour@1.18.7`

**Comment by PeterKottas** [comment]
Thanks for the quick work, you're a star! I gave it a quick look to update to v2 but I am afraid we have a lot of custom work in place that would make it tedious, to say the least. Sticking with v1 for the time being. V2 looks good though, kudos.
