### ISSUE TITLE
When the page is switched then the react tour doesn't start from beginning for the particular page so is there any way to achieve this?

### ISSUE THREAD

**Issue by namanappbroda011** [elrumordelaluz/reactour#434]

**Comment by elrumordelaluz** [comment]
Hi @namanappbroda011, thanks for open the _Issue_.
Mind creating a reduced reproduction in a sandbox? thanks!

**Comment by namanappbroda011** [comment]
I don't understand why withRouter is giving error on codesandbox. Please have a look! 
https://codesandbox.io/s/staging-fast-prcdu?file=/src/index.js

![image](https://user-images.githubusercontent.com/94125204/151647143-c366fad8-4ce9-4d81-a13a-20e03e94b720.png)

**Comment by elrumordelaluz** [comment]
[Seems that `withRouter` doesn't exists in `v6`](https://reactrouter.com/docs/en/v6/faq#what-happened-to-withrouter-i-need-it). Try also using `@reactour/tour` for modern solutions.

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
