### ISSUE TITLE
Position Popover when screen size height is small

### ISSUE THREAD

**Issue by dickyindra** [elrumordelaluz/reactour#437]
I have long text content, when the web is opened with a small screen height, always position the popover to the center, even though the page can still be scrolled down.

This is how it looks when the screen size height is small.
![Screen Shot 2022-02-07 at 10 47 52](https://user-images.githubusercontent.com/13186704/152721529-47a55d5b-2b8c-44d5-a085-7ce803e7b8c4.png)

I want the page to scroll down so there is room for a popover
![Screen Shot 2022-02-07 at 10 48 24](https://user-images.githubusercontent.com/13186704/152721595-fffb1dce-8031-427a-b751-0ff3353d5e07.png)

Can I fix it?

Code: https://codesandbox.io/s/stupefied-kirch-48ky5
Demo: https://48ky5.csb.app/

**Comment by elrumordelaluz** [comment]
Hi @dickyindra, thanks for open the _Issue_.

The _Tour_ is responsible only of scrolling into view elements (steps) that are outside the viewport when needed. However you can handle cases controlling the scroll before open the tour. Something like:

```js
```

**Comment by dickyindra** [comment]
Great, thanks for the information!
But can I use it for the next step?

I'm also having this kind of problem:
<img width="496" alt="Screen Shot 2022-02-09 at 00 46 46" src="https://user-images.githubusercontent.com/13186704/153045591-37f9be23-8e7a-4171-9979-321852875359.png">

Code: https://codesandbox.io/s/tender-kowalevski-7p6mn
Demo: https://7p6mn.csb.app/

**Comment by elrumordelaluz** [comment]
You could do something like [this](https://codesandbox.io/s/fragrant-thunder-qdqln?file=/src/index.js) using [nextButton](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#nextbutton-props-btnfnprops--void) prop.

**Comment by dickyindra** [comment]
Thanks a lot!
