### ISSUE TITLE
setCurrentStep to go back 1 or more steps

### ISSUE THREAD

**Issue by Mihai-github** [elrumordelaluz/reactour#440]
Hi,

   I have a 5 step tour and I wanna let the user go back 1 step by pressing a "prev" button. For going to the next step I'm using the setCurrentStep and at first, I thought I could use it also for going to the previous step but seems to not be the case.
   Maybe someone knows how I can achieve this?

**Comment by yanickrochon** [comment]
By default, `setCurrentStep` is a standard [`useState`](https://reactjs.org/docs/hooks-reference.html#usestate) tuple, meaning that you can do

```js
setCurrentStep(currentStep => currentStep - 1);`
```

**Comment by Mihai-github** [comment]
Yes, I realized that after I made the post

**Comment by Mihai-github** [comment]
Any idea if I can remove the close of the tour on clicking outside the tour?

**Comment by elrumordelaluz** [comment]
> Any idea if I can remove the close of the tour on clicking outside the tour?

https://github.com/elrumordelaluz/reactour/issues/410#issuecomment-990978132

**Comment by Mihai-github** [comment]
@elrumordelaluz It worked, thank you very much :)
