### ISSUE TITLE
disableInteraction not working React Native 

### ISSUE THREAD

**Issue by MDmubarak786** [elrumordelaluz/reactour#444]
`import { disableBodyScroll, enableBodyScroll } from 'body-scroll-lock'
import { Placeholder, doSteps } from '../utils'
const demoId = 'scroll-lock'
const steps = doSteps(demoId)
const disableBody = target => disableBodyScroll(target)
const enableBody = target => enableBodyScroll(target)

;<TourProvider steps={steps} afterOpen={disableBody} beforeClose={enableBody}>
  <Placeholder demoId={demoId} />
</TourProvider>`

i couldn;t understand anyone tell me how to do this and doSteps is it function  whats happening inside

**Comment by elrumordelaluz** [comment]
please follow the discussione [here](https://github.com/elrumordelaluz/reactour/discussions/442)
