### ISSUE TITLE
An error occurred while upgrading @react-aria/utils

### ISSUE THREAD

**Issue by mingzizhennimafan** [elrumordelaluz/reactour#445]
Reproduce Step: 
Upgrad "@react-aria/utils": "3.11.1"
Got error:
Module parse failed: Unexpected token

I did nothing and found this error this morning when packaging using github actions. What should I do now?

**Comment by efattal** [comment]
Having the same error here.

**Comment by chireia** [comment]
I'm having a issue starting the application after running:

`yarn add @reactour/tour @emotion/react`

I think this should be something related:
```
./node_modules/@react-aria/interactions/dist/module.js 625:13
Module parse failed: Unexpected token (625:13)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| }, ref) => {
|   let newRef = $7R3Av$useRef();
>   ref = ref ?? newRef;
|   let {
|     pressProps: pressProps
```

I also found this [issue](https://github.com/adobe/react-spectrum/issues/2857) on `react-spectrum`(aka @react-aria) repo

Is there any workaround for that?

**Comment by McFoggy** [comment]
as [I mentionned](https://github.com/adobe/react-spectrum/issues/2857#issuecomment-1041872035) on the issue you have pointed, migrating to webpack 5 did the trick for us.

we followed [webpack 5 migrating guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5)
