### ISSUE TITLE
Safari mask issue (round corners)

### ISSUE THREAD

**Issue by maks-hayduk** [elrumordelaluz/reactour#446]
## Tutorial I was looking when developing [link](https://reactour.vercel.app)

Seems like rx property is not working correctly when using Safari

This one in **safari** 
<img width="290" alt="Знімок екрана 2022-02-16 о 20 30 19" src="https://user-images.githubusercontent.com/44266854/154332042-43d8b5e5-e133-4cfe-9d3c-af3640c0697b.png">

This one in **chrome**
<img width="274" alt="Знімок екрана 2022-02-16 о 20 32 10" src="https://user-images.githubusercontent.com/44266854/154332311-8cbf6435-714c-4fc6-9ed2-50df24e7838f.png">

Expected behavior: corners in mask should be rounded when updating styles property.

**Comment by maks-hayduk** [comment]
#448

**Comment by elrumordelaluz** [comment]
Should be available on `@reactour/tour@2.9.1`. Thank you @maks-hayduk for the fix!
