### ISSUE TITLE
Paddings in maskRect overlay or in overall svg

### ISSUE THREAD

**Issue by maks-hayduk** [elrumordelaluz/reactour#450]
Is it possible to add paddings in tour so it will have empty space as on picture (red lines, f.x. 20px)
<img width="856" alt="Знімок екрана 2022-02-21 о 20 20 28" src="https://user-images.githubusercontent.com/44266854/155009033-e9b69414-01e7-44ea-a51b-28165c8c7af7.png">

@elrumordelaluz could you please help me with this one?

**Comment by elrumordelaluz** [comment]
Thanks for the input @maks-hayduk.
Now `@reactour/mask@0.5.0` has the [wrapperPadding](https://github.com/elrumordelaluz/reactour/tree/master/packages/mask#wrapperpadding-number--number-number) prop to control this. It is also available on `@reactour/tour@2.10.0` through [padding](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#padding-padding-1) prop like:

```js
<Tour
  padding={{ wrapper: 20 }}
  ...
/>
```

[Here is a preview](https://reactour.vercel.app/#masking-dom-elements) working with _Mask_ and [here ](https://reactour.vercel.app/#padding)working with _Tour_.
