### ISSUE TITLE
Use goTo in actions

### ISSUE THREAD

**Issue by Adrian12317** [elrumordelaluz/reactour#453]
Hi I'm trying to switch to the next step with the action prop but i can't, because the prop goTo is only in the content.

Is there any way to use goTo inside the action prop?

![image](https://user-images.githubusercontent.com/48723226/155340751-b642b6d2-efaf-4020-8c5f-bf73b9f05fbf.png)

**Comment by elrumordelaluz** [comment]
Hi @Adrian12317, I suggest you to try to migrate into `v2`, using `@reactour/tour` package with lots of improvements, included the user case you are looking for.
