### ISSUE TITLE
Switch from navigation arrow to button

### ISSUE THREAD

**Issue by yingying96** [elrumordelaluz/reactour#455]
Hello,

I would like to check if it's possible to switch from navigation arrow to use buttons instead?

Thanks!

**Comment by elrumordelaluz** [comment]
Could you expand a little more, explaining which version of _Reactour_ you are using and sharing a sandbox with a minimal reproduction? Thanks,

**Comment by yingying96** [comment]
Hi i'm using version": "1.18.6"
Here's the arrow i'm referring to.
![image](https://user-images.githubusercontent.com/19566726/158495748-c45202dd-d0b9-42da-887c-24256b7c16f5.png)

Wondering if we can switch to something like this

![image](https://user-images.githubusercontent.com/19566726/158495798-dab2589b-0da8-4466-a861-385dfc017a99.png)

**Comment by yingying96** [comment]
Found it under the custom components part of the guide!

https://reactour.vercel.app/#popover

![image](https://user-images.githubusercontent.com/19566726/158577711-64ad6d60-b71b-479d-b947-306b743a5ee0.png)

**Comment by yingying96** [comment]
Apologies just wanted to confirm if components is only available on v2? Because i'm using v1.

**Comment by elrumordelaluz** [comment]
Hi @yingying96, thanks for open the _Issue_.

In [v1](https://github.com/elrumordelaluz/reactour/tree/v1) there is a _CustomHelper_ prop, which can receive a Component fully customizable. Thake a look into [this comment](https://github.com/elrumordelaluz/reactour/issues/135#issuecomment-493583313).

Keep in mind that `v2` have more flexibility on most aspects.

**Comment by yingying96** [comment]
Great! Let me try to explore this abit more. Thank you.

**Comment by yingying96** [comment]
Just to close off this question. Managed to do it with tour props.


```

      <Tour
        steps={tourConfig}
        isOpen={isTourOpen}
        onRequestClose={() => setIsTourOpen(false)}
        prevButton={(
          <ButtonComponent
            btnTheme="outline-blue"
            size="small"
            label="Back"
            callbackFunc={(e) => { e.preventDefault(); return false; }}
          />
        )}
        nextButton={(
          <ButtonComponent
            btnTheme="blue"
            size="small"
            label="Next"
            callbackFunc={(e) => { e.preventDefault(); return false; }}
          />
        )}
        lastStepNextButton={(
          <ButtonComponent
            btnTheme="blue"
            size="small"
            label="Done"
            callbackFunc={(e) => { e.preventDefault(); return false; }}
          />
        )}
      />
```
