### ISSUE TITLE
Resize close button

### ISSUE THREAD

**Issue by yingying96** [elrumordelaluz/reactour#457]
Hi there,

Is there a way to resize the close button on the v1 reactour?
Thanks!

![image](https://user-images.githubusercontent.com/19566726/158603000-5dcba5c5-6163-4287-b0f0-b96045971c25.png)

**Comment by elrumordelaluz** [comment]
You can use the `reactour__close` classname to modify styles.

**Comment by yingying96** [comment]
Yes thank you. For those who are interested or needed help with CSS like me to edit the button. Here's an example.

```
              <Tour
                steps={steps}
                isOpen={this.state.isTourOpen}
                onRequestClose={this.closeTour}
                rounded={5}
                className="reactour_helper_large reactour_close"
              />
```

```
.reactour_helper_large{ 
    max-width: 60% 
}
.reactour_helper_large button.reactour__close{ 
    width: 15px;
}
```
