### ISSUE TITLE
Turning off the SVG mask

### ISSUE THREAD

**Issue by bmoquist** [elrumordelaluz/reactour#46]
Hello -- The tour that I've constructed requires that users interact with content on the screen during the tour (e.g. canvas) so I need to turn off the mask entirely. 

I upgraded to 1.7.1 from 1.6.2. Previously, I used maskClassName with the following to turn off the mask: 
```
.tourMaskStyle {
  display: none;
}
```
In 1.7.1, maskClassName no longer appears to work. The class appears to get passed into SvgMask as a prop ```className={maskClassName}```, but then this className prop is not actually used in the SvgMask file.  

Is there a new way to turn off the mask? Advice on how to proceed would be appreciated! Thanks!

**Comment by elrumordelaluz** [comment]
hey @bmoquist thanks for pointing this out. 

Missed to pass down the `className` into the `svg` element. Should be fixed now.
I'll publish a new version with `maskClassName` working as expected.

**Comment by jakebanks** [comment]
For other readers, I was able to achieve this by passing this style to TourProvider

```ts
                maskWrapper: (() => {
                    return {
                        display: 'none'
                    }
                }),
```

It did look a bit odd without an arrow pointing to the target of that step of the tour, this looks to work but I abandoned the idea https://github.com/elrumordelaluz/reactour/issues/98
