### ISSUE TITLE
React tour running on development mode but fails when built with Vitejs!

### ISSUE THREAD

**Issue by legionairre** [elrumordelaluz/reactour#464]
Hello, we are using @reacttour/tour as you know v2 and specific version is v2.10.2. Our project infrastructure has vitejs v2 and we are building our project with vitejs. 

While I was in development mode, I completed my development with reactour. Everything was working properly at this stage. After that I must build the project but, I got an error. Error message is below:

<img width="1416" alt="Screen Shot 2022-04-16 at 15 01 35" src="https://user-images.githubusercontent.com/13413021/163674916-e61188b8-cf47-4d67-a687-219a0ee6ab05.png">

If you change the import statement in the `tour.esm.js `on 1st line shown in the photo above to
`import { useState, useCallback, useEffect, useContext } from 'react';`, the problem goes away.

I also looked for other solutions but i cannot resolve this issue differently.

I created a mini project so that you can understand reactour's build process more easily. You can find out this mini project following repository: https://github.com/legionairre/vite-react-ts-reactour

In this repository if you run `npm run dev` you will see everything is working fine. However, if you run `npm run build` you will see the error message and cannot build the project anymore.

@mustafaakin fyi.

**Comment by legionairre** [comment]
In addition to this, actually issue related with React new JSX transformation (React v17). You can find more details [here](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) That's why when you delete the React from the import statement, build is running properly.

**Comment by ahadcove** [comment]
Yeah running into the same issue. Even manually updating tour esx in node modules allows the build but springs up a bunch of other issues after the app is built

**Comment by legionairre** [comment]
@ahadcove You are right, I am also looking for a permanent solution. I forked the repository and changed some configurations in tsconfig.json, but I didn't find any solution yet. Can you let me know If you have found any solution?

**Comment by abdevlpr** [comment]
I'm running into the same problem and i couldn't fix it after manually changing the node modules, any help?

**Comment by abstud** [comment]
@legionairre i'm having an issue when trying to build (using vite atm) i switched from joyride to react tour, please let me know if you find any solution i don't see any reason to go back to joyride

**Comment by legionairre** [comment]
> I'm running into the same problem and i couldn't fix it after manually changing the node modules, any help?
> 
> 

If you delete the React keyword from the first line of tour.esm.js, the problem seems to be gone. But this is not a solution. Different problems may arise.

**Comment by legionairre** [comment]
> @legionairre i'm having an issue when trying to build (using vite atm) i switched from joyride to react tour, please let me know if you find any solution i don't see any reason to go back to joyride 

Joyride is not supporting to Provider logic also React Hook infrastructure. That's why I chose this library. I hope we find a nice solution

**Comment by legionairre** [comment]
I found a workaround with the use of Vite. I don't know what problem will arise after doing this yet.
In vite.config.js
`
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
...
...
export default defineConfig({
   plugins: [react({ jsxRuntime: 'classic' })],
   ...,
});
`
If you add into the plugin react inside jsxRuntime: 'classic' as above, the building process will be a success. But, I said, I don't know which problems will arise after doing this. Could you please share your experiences?

**Comment by ahadcove** [comment]
> I found a workaround with the use of Vite. I don't know what problem will arise after doing this yet. In vite.config.js
> 
> ```js
> import { defineConfig } from 'vite';
> import react from '@vitejs/plugin-react';
> ...
> ...
> export default defineConfig({
>    plugins: [react({ jsxRuntime: 'classic' })],
>    ...,
> });
> ```
> 
> If you add into the plugin react inside jsxRuntime: 'classic' as above, the building process will be a success. But, I said, I don't know which problems will arise after doing this. Could you please share your experiences?

I tried this a few days ago. This causes issues with other libraries that don't work well with JSX classic. I had hook issues pop up after switching to classic. I even tried importing Reactour as a commonjs module and that caused issues as well.
I don't see any simple solution other than reactour support the new jsx runtime

**Comment by elrumordelaluz** [comment]
Hi all and thanks for open the _Issue_ and for the pretty detailed steps to reproduce it ❤️ . I'm sorry for the late reply. I'll investigate right now and back to you.

**Comment by elrumordelaluz** [comment]
Can you please check if works upgrading to latest patch version?

**Comment by ahadcove** [comment]
You're amazing @elrumordelaluz this fixed it. Thank you!

**Comment by legionairre** [comment]
It works now with the latest update. @elrumordelaluz thank you very much. This is not relevant, but we do get a Sentry alert that the ResizeObserver loop limit has been exceeded. Do you know what this is?

**Comment by elrumordelaluz** [comment]
> Sentry alert that the ResizeObserver loop limit has been exceeded. Do you know what this is?

Conestly don't know what they mean. Mind open another issue in case you could get more info related?

Thanks!

**Comment by viniciusalvess** [comment]
> Can you please check if works upgrading to latest patch version?

How do I update to this version? I'm getting affected by the same issue.

**Comment by elrumordelaluz** [comment]
I am closing this _issue_, but feel free to re-open or create a new one in any case.
