### ISSUE TITLE
Using Reactour with Vite causes an error on compiling: pragma and pragmaFrag cannot be set when runtime is automatic

### ISSUE THREAD

**Issue by ahadcove** [elrumordelaluz/reactour#465]
**Describe the bug**
When using Reactour with Vite i'm getting this error:

```
[vite:react-babel] /Users/bk/Coding/Lumia/LumiaStream/node_modules/@reactour/tour/dist/tour.esm.js: pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 | import React, { useState, useCallback, useEffect, useContext } from 'react';
    | ^
  2 | import { inView, smoothScroll, getWindow, getRect, Portal, Observables } from '@reactour/utils';
  3 | import { Mask } from '@reactour/mask';
  4 | import { Popover } from '@reactour/popover';
file: /Users/bk/Coding/Lumia/LumiaStream/node_modules/@reactour/tour/dist/tour.esm.js
/Users/bk/Coding/Lumia/LumiaStream/node_modules/@babel/core/lib/transformation/file/file.js:249
    return new _Error(msg);
```

I've seen the same issue with emotion before and it was fixed by using in vite.config in the renderer:

```
	plugins: [
		react({
			jsxImportSource: '@emotion/react',
			babel: {
				plugins: ['@emotion/babel-plugin'],
			},
		}),
```

Sadly this same method isn't working for Reactour

**Comment by ahadcove** [comment]
It looks like removing the React import from `node_modules/@reactour/tour/dist/tour.esm.js` fixes the issue. I'm still looking into if there's a babel setting that I can apply for just react tour so that we don't have to manually remove the React import

**Comment by ahadcove** [comment]
Temporarily switching back to the Classic react runtime fixes the issue although I think it should be a simple solution to fix in the reactour bundler
Here's what I had to add to my vite.config to fix it:

```js
{
       plugins: [
		react({
			jsxRuntime: 'classic',
		})
	]
}
```

**Comment by legionairre** [comment]
Same issue is [here](https://github.com/elrumordelaluz/reactour/issues/464).

**Comment by abdevlpr** [comment]
Having the same issue here, i'm switching to vite and i'm getting build error

**Comment by elrumordelaluz** [comment]
closing to follow in #464
