### ISSUE TITLE
Maximum Call stack when using with MaterialUI Dialog

### ISSUE THREAD

**Issue by fawwaz** [elrumordelaluz/reactour#469]
**Describe the bug**
I need to highlight the material UI dialog, but as soon as I the MUI dialog opened and I click an element inside MUI Dialog, an error appear in the console saying `Maximum call stack size exceeded.` making it unusable.

**To Reproduce**
1. Open this codesandbox : https://codesandbox.io/s/cocky-heyrovsky-8ys6q1
2. Click start tour button
3. Click the button to trigger the modal, a popover from tour component will appear.
4. Click any part inside MUI Dialog

**Expected behavior**
No error message in the console, browser won't crash

**Screenshots**
See this video recording 

https://user-images.githubusercontent.com/1295143/165016934-8eb45383-8801-42a6-a880-95316da91302.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : Chrome
 - Version :  99.0.4844.51 (Official Build) (64-bit)

**Additional context**
Side questions, things that I am not sure : 
1. Am I using the react tour properly ? My needs is to highlight a modal, but the content of the modal is fetched from server (async). 
2. If it is not correct, what is the best way to fulfill my need ?

**Comment by elrumordelaluz** [comment]
Hi @fawwaz, thanks for open the _Issue_.

Seems that there is some conflict between the `TrapFocus` MUI component and the one inside the _Tour_.

Try adding `disableFocusLock` like:

```js
<TourProvider steps={steps} disableFocusLock>
  <Main />
</TourProvider>
```

[Here](https://e11w2q.csb.app/) is a working example

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
