### ISSUE TITLE
Tour not scrolling to view the next component

### ISSUE THREAD

**Issue by s-pcode** [elrumordelaluz/reactour#471]
**Describe the bug**
The tour initialization is correct and it works as expected for 1st 3 steps as all the components are in the viewport. But the 4th step is regarding the component which is not visible and here the problem arises that the tour does not scroll the page to bring that component into view. I followed the exact steps mentioned in the docs and also the code is similar to the demo.

**To Reproduce**
1. Go to https://stackblitz.com/edit/nextjs-m696rr?file=pages/_app.js
2. Scroll down to view the issue
3. See that component does not come into view

**Expected behavior**
When the component is not in view the tour should scroll the page to bring that component into view.

**Desktop (please complete the following information):**
 System:
    OS: Windows 10 10.0.19044
    Browser: Chrome and Brave
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 2.24 GB / 15.83 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD

**Additional context**
I'm using nextjs and material UI. I'm not able to figure out the issue for 2 days. I went through all the previous issues but yet couldn't figure out anything specifically useful. Urgent help is needed. Thanks 👍

**Comment by elrumordelaluz** [comment]
Hi @s-pcode, thanks for open the _Issue_.

Is it possible to you to upgrade to `@reactour/tour@2.x.x` version?

The scrolling when switching routes seems to work as expected, like in [this demo](https://codesandbox.io/s/tour-demo-using-react-router-dom-with-automatic-route-switching-forked-z8jyvg)

**Comment by s-pcode** [comment]
Ok, I'll have a look at v2. 
Thanks 👍

**Comment by jorgadev** [comment]
> 

Is it possible to make that popover doesn't go do center first (like it goes in demo), and then to highlighted element, but immediately to highlighted element?
