### ISSUE TITLE
Not going to the last section in iphone

### ISSUE THREAD

**Issue by vivektak** [elrumordelaluz/reactour#480]
I used the package for Desktop as well as for mobile, I added 6 steps into this. The desktop is working fine as well as android, but facing an issue with the last step in the iPhone devices, basically, it's not highlighting the last section I have in the footer, all the other sections are working fine. also, the same thing is working fine on android devices

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
