### ISSUE TITLE
Hide prevButton for first step

### ISSUE THREAD

**Issue by yingying96** [elrumordelaluz/reactour#482]
Hello, may i know if it is possible to hide prevButton for the first step?

Currently the prevButton/arrow is shown even if it is the first step.

Thanks!

**Comment by elrumordelaluz** [comment]
Hi @yingying96, it is possible using [prevButton prop](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#prevbutton-props-btnfnprops--void). Something like:

```js
<TourProvider steps={steps} prevButton={({Button, currentStep}) => 
   <Button kind="prev" hideArrow={currentStep === 0} />
 }>
  {/* ... */}
</TourProvider>
```

[Here](https://codesandbox.io/s/reactour-tour-demo-using-react-router-dom-forked-ei815u?file=/index.js:256-398) is a working example.

**Comment by yingying96** [comment]
Thanks for the example! May i know how do you set/configure the currentStep? Because if i add in the part shown, my prevButton will be gone.

**Comment by elrumordelaluz** [comment]
`currentStep` is calculated internally and passed into `prevButton` function. Mind creating a minimal reproduction on a sandbox in order to debug it there?

**Comment by yingying96** [comment]
Something like this - https://codesandbox.io/s/reactour-tour-demo-using-react-router-dom-forked-4yhf0q?file=/index.js
I'm using custom button from material ui.

Currently the nextButton shows up for me

      <Tour
        steps={tourConfig}
        isOpen={isTourOpen}
        onRequestClose={() => setIsTourOpen(false)}
        showNavigation={false}
        showNavigationNumber={false}
        showNumber={false}
        rounded={5}
        className="reactour_helper_large"
        prevButton={({ Button, currentStep }) => <Button kind="prev" hideArrow={currentStep === 0} />
        }
        nextButton={(
          <Button variant="contained" color="primary">
            Next
          </Button>
        )}
      />


![image](https://user-images.githubusercontent.com/19566726/176164351-ea20b3a4-433f-44bc-8e33-2d8190ba21d9.png)

**Comment by elrumordelaluz** [comment]
Oh! seems you are using `v1`!

In that case the [prevButton](https://github.com/elrumordelaluz/reactour/tree/v1#prevbutton) accepts only a `node` and not a function. If you are able I recommend to switch into `@reactour/tour` package.

**Comment by yingying96** [comment]
I see. May i know if there is any way we can achieve that in v1? Thanks!

**Comment by elrumordelaluz** [comment]
unfortunately `v1` is much more limited in various aspects, and doesn't comes me in mind a tricky way for achieve this.

**Comment by yingying96** [comment]
Alright thanks!

**Comment by pribrahimsari** [comment]
For anyone who uses v1 and wants to hide prevButton on firstStep, here is my solution:

```javascript
const [currentStep, setCurrentStep] = useState(0);

// ...

return (
    <Tour
           // ...
            getCurrentStep={(curr) => {
                setCurrentStep(curr);
            }}
            prevButton={currentStep > 0 ? <MyCustomPrevButton /> : <></>}
            // ...
        />   
);
```
