### ISSUE TITLE
Not working when using it for elements inside shadow root

### ISSUE THREAD

**Issue by MarcLopezAvila** [elrumordelaluz/reactour#486]
First of all thanks for this great library, I have used it in several projects so far but when it comes to Microfrontend development we have found some issues:

**Describe the bug**
When using shadow DOM it is just not working. I am passing an element that is inside a shadow root using the 'selector' property as an element and it is not showing the tour in the right position, it just appearing in the top left corner.

**To Reproduce**
- Usage in React
1. Create a web component with a shadow root in 'open' mode
2. Create Button element inside the shadow root
3. Try to set up the tour targeting the Button inside the shadow root 

**Expected behavior**
Display the Tour Popover in the right position. It would be great to be able to provide an element where the <reactour-portal > is appended and also all the JSS styles are applied so the global scope is not polluted. Something like StyleSheetManager in styled-components.

If you know a possible workaround would be also great. For now we are disabling the Tour in some modules because of this issue.

Thanks

**Comment by elrumordelaluz** [comment]
Hi @MarcLopezAvila, thanks for open the _Issue_.

Since you closed the issue, can you share what was the solution, in order to be helpful to others?

Otherwise, if the issue persists, mind creating a minimal reproduction in a sandbox in order to allow to debug your use-case and try to find a solution? Thanks!

**Comment by MarcLopezAvila** [comment]
In this case I managed to always pass an Element as a selector (because with js you can querySelector the shadow root) but because the elements of the steps are not there all at once, I had to do a 'setSteps' execution all the time with the right step index. 
It's a workaround but it works for selectors. It doesn't though for detecting mutations so I created an Issue in this repository. https://github.com/elrumordelaluz/reactour/issues/487
