### ISSUE TITLE
Unnecessary network requests

### ISSUE THREAD

**Issue by spiderhands** [elrumordelaluz/reactour#488]
**Describe the bug**
On every render there is a new network request in the Network Tab

**To Reproduce**
1. Go to [https://reactour.vercel.app](https://reactour.vercel.app/)
2. Scroll down to "Smooth scroll"
3. Open developer tools
4. Navigate to the network tab
5. Click on "Start tour"
6. Click on the "Right arrow" of Popover

**Expected behavior**
No requests are sent

**Screenshots**
<img width="1787" alt="Screen Shot 2022-08-11 at 12 27 05 PM" src="https://user-images.githubusercontent.com/8925613/184095032-71859b0c-3dcd-4259-a3bd-a77bdbed01b2.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 103.0.5060.134 (Official Build) (x86_64)

**Comment by elrumordelaluz** [comment]
Hi @spiderhands, thanks for open the _Issue_.

I am only getting the same result on Chrome, not in FF nor in Safari.
Let's investigate which could be the source of the problem.

**Comment by elrumordelaluz** [comment]
It seems that there are `img` requests.
![Uploading Screenshot 2022-08-11 at 11.38.36.png…]()

**Comment by spiderhands** [comment]
Something tries to navigate to a URL with the mask hash at the end

https://emaxple.com/some-page#mask__dvybzk7rb9a

**Comment by elrumordelaluz** [comment]
where did you found this?

**Comment by spiderhands** [comment]
Our internal deployment returns 404 with the HTML body on any page that is not the /index.html

The browser prints errors in the console like this:
<img width="1060" alt="Screen Shot 2022-08-11 at 3 14 08 PM" src="https://user-images.githubusercontent.com/8925613/184121434-1a935e1e-2b72-42b9-b95c-0ad038eb749b.png">

**Comment by spiderhands** [comment]
Our internal deployment returns 404 with the HTML body on any page that is not the /index.html

The browser prints errors in the console like this:
<img width="1018" alt="Screen Shot 2022-08-11 at 3 16 31 PM" src="https://user-images.githubusercontent.com/8925613/184121780-821b44e2-9218-4bf5-89bb-3deec0fcad5f.png">

**Comment by elrumordelaluz** [comment]
So you are getting the same result/issue as in the demo, in your project using `@reactour/tour` (outside the playground).

Is weird that those `/sesson#mask__{…}` calls are different of those on the demo and with different response codes.

**Comment by elrumordelaluz** [comment]
Also, for some reason and always using Chrome, this didn't happens on the Demo site at https://reactour.js.org which is using all [updated dependencies](https://github.com/elrumordelaluz/reactour/blob/master/demo/package.json#L6-L16)

<img width="1840" alt="Screenshot 2022-08-11 at 15 34 25" src="https://user-images.githubusercontent.com/784056/184145608-454b5ef1-6aa6-43fd-9f1e-c198a23b2995.png">

**Comment by elrumordelaluz** [comment]
_unrelated_: for some reason the site on gh-pages stopped working, investigating.

**Comment by elrumordelaluz** [comment]
`@reactour` packages now are _css-in-js_ lib agnostic; this means avoid the creation of `<style>` blocks on each chage with new `css` declarations for each mask change and related stuff.

Please try the same [demo](https://reactour.vercel.app/#tourprovider) and updating your project into `@reactour/tour@3.0.0`. 

![Screenshot 2022-08-12 at 10 44 59](https://user-images.githubusercontent.com/784056/184318886-46b9fe5f-ece6-4313-b36e-ff4d11ec9151.png)

On my side seems solved. Please re-open in any case.
