### ISSUE TITLE
Library download on request

### ISSUE THREAD

**Issue by dartess** [elrumordelaluz/reactour#489]
This library is great. But I would like to use the library in very rare cases. Therefore, I would not like to put it in the main bundle, but download it as needed (lazy).

However, due to the fact that the application needs to be wrapped in a `TourProvider`, this seems to be impossible without rerendering the App (which is unacceptable for me).

Can you suggest something?

**Comment by yanickrochon** [comment]
The problem is less about wrapping your app inside a `TourProvider`, as this can be done rather easily through `React.lazy`, but it is more about controlling the tour using `useTour` inside of your app. You would need to create a wrapped component of each and every parts of your app who make use of `useTour`, then conditionally and lazy load these wrapped components as well.

Something like this :


```js
import MyComponent from './path/to/MyComponent';

const WrappedTourProvider = React.lazy(() => import('./path/to/WrappedTourProvider'));
const WrappedMyComponent = React.lazy(() => import('./path/to/WrappedMyComponent'));

const AppComponent = () => {
  const [ enableTour, setEnableTour ] = React.useState(false);

  return enableTour ? (
    <WrappedTourProvider ...>
      <WrappedMyComponent ...>
        <MyComponent />
     </<WrappedTourComponent>
    </WrappedTourProvider>
  ) : (
    <MyComponent />
  );;
};
```

If both `WrappedTourProvider` and `WrappedMyComponent` normally import `@reactour/tour`, because of optimized bundles, they will be lazily imported in your application only when they are rendered.

And because you can use selectors, like `data-*` attributes for example, with Reactour, then `WrappedMyComponent` do not need actual references to the elements in order to control the tour.

**Comment by dartess** [comment]
Unfortunately, there are still two problems here.

1. in this case, `MyComponent` will be rendered twice - when the tour is turned on, an unmount will occur, and then there will be a new mount. As I wrote above, this is not acceptable in my case, as many things will be reset.

2. Even though I rarely need the tour, it shows elements that are related to the application shell, among other things. This further exacerbates the first problem. The entire application will be unmounted and mounted again.

I think that in the first version of this library a few years ago I did not have such a problem. It's a pity that this time i have to look for an alternative, because your library is amazing.

**Comment by dreamfalcon** [comment]
> @yanickrochon It's me again. I have tried several alternatives and they are all terrible. None of the libraries managed to show one of the steps after the animated menu opening. That's why I came back here.
> 
> I tried not to wrap the whole application in a Provider, and just render it in an arbitrary place. Everything works, my tour runs on the entire application.
> 
> It turns out that I was simply disoriented by the api provider and misunderstood its purpose.
> 
> Thanks again for your excellent work.

Here only works if I wrap the entire app.
How did you managed it?

**Comment by elrumordelaluz** [comment]
> > @yanickrochon It's me again. I have tried several alternatives and they are all terrible. None of the libraries managed to show one of the steps after the animated menu opening. That's why I came back here.
> > I tried not to wrap the whole application in a Provider, and just render it in an arbitrary place. Everything works, my tour runs on the entire application.
> > It turns out that I was simply disoriented by the api provider and misunderstood its purpose.
> > Thanks again for your excellent work.
> 
> Here only works if I wrap the entire app. How did you managed it?

Non necessarily you have to wrap all the _App_ with _TourProvider_ but you only are allowed to use `hook` only in the tree inside the provider. You can do something like this:

```js
```

Here is the working example.

**Comment by dreamfalcon** [comment]
I will have to check this better later.
Thanks
