### ISSUE TITLE
Reactour arrow styling no longer works on v3

### ISSUE THREAD

**Issue by cdelst** [elrumordelaluz/reactour#494]
Upgraded to v3 and found that the styling implemented based on 

https://codesandbox.io/s/tour-with-data-fetching-forked-ic5es?file=/src/index.js:1698-1713

no longer works.  Is this expected? Or is there some other way to implement dynamic pointer arrows in the popovers now? I haven't found any resources relating to this.

I can absolutely confirm that the only change between a working -> non-working state is the package upgrade.  

Thanks! 

Versions: 
2.12 -> 3.0.1

**Comment by elrumordelaluz** [comment]
Hi @cdelst, thanks for open the _Issue_.

As described on #492 the lib now isn't using an external `css-in-js` lib, so the approach to make the arrow is a little different now.

Now you can have the same result tweaking some css variables, like:

```js
function doArrow(position, verticalAlign, horizontalAlign) {
  if (!position || position === "custom") {
    return {};
  }

  const width = 16;
  const height = 12;
  const color = "white";
  const isVertical = position === "top" || position === "bottom";
  const spaceFromSide = 10;

  const obj = {
    [`--rtp-arrow-${
      isVertical ? opositeSide[horizontalAlign] : verticalAlign
    }`]: height + spaceFromSide + "px",
    [`--rtp-arrow-${opositeSide[position]}`]: -height + 2 + "px",
    [`--rtp-arrow-border-${isVertical ? "left" : "top"}`]: `${
      width / 2
    }px solid transparent`,
    [`--rtp-arrow-border-${isVertical ? "right" : "bottom"}`]: `${
      width / 2
    }px solid transparent`,
    [`--rtp-arrow-border-${position}`]: `${height}px solid ${color}`
  };
  return obj;
}
```

remember to pass `import "@reactour/popover/dist/index.css"` somewhere in your app.
