### ISSUE TITLE
import popover/dist/index.css is unresolved

### ISSUE THREAD

**Issue by cjhensen** [elrumordelaluz/reactour#496]
Hi @elrumordelaluz! I'm trying to `import "@reactour/popover/dist/index.css"` per your example and it does not resolve.

On version 3.0.5

![Screen Shot 2022-08-26 at 10 29 23 AM](https://user-images.githubusercontent.com/6188364/186927198-3b5da213-e562-4e87-836e-671fb6466cda.png)

**Comment by elrumordelaluz** [comment]
@cjhensen can you try installing `@reactour/popover` as a dependency?

**Comment by elrumordelaluz** [comment]
Closing as this issue is related on [this one](https://github.com/vercel/next.js/issues/12079)

**Comment by elrumordelaluz** [comment]
[RFC](https://github.com/vercel/next.js/discussions/27953)
