### ISSUE TITLE
Add Test 🙏

### ISSUE THREAD

**Issue by elrumordelaluz** [elrumordelaluz/reactour#5]

**Comment by belgac** [comment]
What test library do you want to use?

**Comment by elrumordelaluz** [comment]
Probably `mocha` and `chai`, did you tried [`jest`](https://facebook.github.io/jest/)?

**Comment by jjcc1421** [comment]
@elrumordelaluz What test components you need to test?

**Comment by elrumordelaluz** [comment]
hi @jjcc1421 thanks for the interest, I think the primary _Component_ to test is the _Tour_ itself and the methods in each `step`. Also the _scroll_ behaviour, and so on…
