### ISSUE TITLE
Automatically re-open Tour

### ISSUE THREAD

**Issue by toduyen** [elrumordelaluz/reactour#506]
how to do when the user has not finished the tour but the user presses F5 or refreshes the page? 
the tour must automatically reopen.

**Comment by elrumordelaluz** [comment]
Hi @toduyen, thanks for open the _Issue_.

In that case you must handle the state of the steps tour outside (as opposite as the internal state handled automatically without extra config), just passing [setCurrentStep](https://github.com/elrumordelaluz/reactour/tree/main/packages/tour#setcurrentstep-dispatchreactsetstateactionnumber) and [currentStep](https://github.com/elrumordelaluz/reactour/tree/main/packages/tour#currentstep-number) in that case handling with a persistent way (like saving step in `localStorage` for example). Same way, using persistent state, you can handle if the _Tour_ was open or close when the page was refreshed.

[Here](https://codesandbox.io/s/reactour-tour-demo-using-react-router-dom-forked-5brgwo?file=/components/App.js) is a working example, which uses [use-persisted-state](https://www.npmjs.com/package/use-persisted-state).

https://user-images.githubusercontent.com/784056/192112643-a7643dc6-c63b-4a9a-967d-b81113a787e1.mp4
