### ISSUE TITLE
useTour re-render many times when i proceed to scroll

### ISSUE THREAD

**Issue by toduyen** [elrumordelaluz/reactour#508]
I tried putting console.log where useTour() is declared and after each step my component is re-rendered many times and even when scrolling horizontally or vertically is re-rendered.

**Comment by elrumordelaluz** [comment]
Hi @toduyen, thanks for open the _Issue_.

Mind creating a minimal reproduction in a sandbox in order to allow others to debug your use-case and try to find a solution? Thanks!

**Comment by elrumordelaluz** [comment]
a bit of maybe related threads: 

https://github.com/facebook/react/issues/22257#issuecomment-915250655

https://stackoverflow.com/a/69104314/1920004

**Comment by toduyen** [comment]
i just have a video of the problem i'm having. Please help me thank you very much @elrumordelaluz https://drive.google.com/file/d/1iU_CHT1m5JqkmdhEuAGVfjxadh98Kvsc/view?usp=sharing

**Comment by elrumordelaluz** [comment]
could you please try updating to the last version?

**Comment by toduyen** [comment]
Hi @elrumordelaluz My latest version is 3.1.4 
![1](https://user-images.githubusercontent.com/62172265/193204624-cefb2708-c56d-43a9-b05c-106f44f114ea.PNG)

**Comment by toduyen** [comment]
This is the TourProvider. mine. But every time I declare useTour in a certain part, every change like vertical and horizontal scrolling causes re-render as video. @elrumordelaluz 
![2](https://user-images.githubusercontent.com/62172265/193206581-659cd9a2-ae40-439e-ad6f-846454248318.PNG)

**Comment by elrumordelaluz** [comment]
could you please try to upgrade into [v3.1.5](https://github.com/elrumordelaluz/reactour/blob/main/packages/tour/package.json#L3)?

**Comment by toduyen** [comment]
ok bro @elrumordelaluz

**Comment by elrumordelaluz** [comment]
great, please let me know.

**Comment by toduyen** [comment]
Too bad when I change the version it seems that useTour crashes ( setCurrentStep , currentstep ) Not woking

https://user-images.githubusercontent.com/62172265/193211910-8c53b45d-acb6-4ddc-b214-e516052e48da.mp4

**Comment by toduyen** [comment]
even though the multiple render issue has been resolved, I still get the setCurrentStep error and the console.log currentstep doesn't change. @elrumordelaluz width 3.1.5

**Comment by toduyen** [comment]
Too bad when I change the version it seems that useTour crashes ( setCurrentStep , currentstep ) Not woking @elrumordelaluz

**Comment by toduyen** [comment]
And when I changed to your new version my program crashed a lot. Please help me to solve this problem.
![3](https://user-images.githubusercontent.com/62172265/193217486-5a762b58-0ac2-42d5-9a4e-9b241bd87bcf.PNG)

**Comment by elrumordelaluz** [comment]
ok, rolled back the last changes, please use `v3.1.6` and please give an eye here https://reactour.vercel.app/ where I added a [`console.log`](https://github.com/elrumordelaluz/reactour/blob/5a978e00d9f72ca0eeed165505dcb30b64cdd3e6/apps/web/components/Home.tsx#L27) for testing purposes in the same Component where is present `useTour` hook, and check if has the same behavior than on your case.

**Comment by toduyen** [comment]
ok bro i will try your latest version

**Comment by toduyen** [comment]
I made a video of two different versions of you. Your version 3.1.6 is still giving me the same problem @elrumordelaluz https://drive.google.com/file/d/1L_1y2Tj3gc8pRpKVXZUux5b57Y6gHIiy/view?usp=sharing

**Comment by elrumordelaluz** [comment]
did you tried the online demo here https://reactour.vercel.app, looking at the `log` and making the same changes you made with window sizes and so on?

**Comment by toduyen** [comment]
thank you i made it. because my source code uses the global window.innerWidth object. New resulted in re-rendering above. I have successfully fixed it but I also hope in future reactour updates to limit the re-render when moving to other steps. Thank you very much bro @elrumordelaluz

**Comment by elrumordelaluz** [comment]
Cool, so I am closing this _issue_, but feel free to re-open or create a new one in any case.
