### ISSUE TITLE
Can I customize onClose function in each tour(steps)?

### ISSUE THREAD

**Issue by nemu626** [elrumordelaluz/reactour#516]
Hello.
First, Thank you your awesome package.

I'm using single  `tourProvider` in app, and using multiple tours with changing steps(`setSteps`).

I want to change the 'onClose' function depends on tour(steps).
Because I want to mark 'this tour is completed or not' to my localstorage.
Currently `stepType` has `action` and `actionAfter`, but haven't `onClickClose`, `onClickMask` props.
So,  I suggest several  way for easily customize close function.
1. Add a prop `onClickClose` to `stepType`  which override default close function.
2. Add a function `setOnClickClose` or `setBeforeClose` to `useTour()`s return object.

Do you have any ideas?

**Comment by elrumordelaluz** [comment]
Hi @nemu626, thanks for open the _Issue_.
I am sorry for the late reply.
Did you tried using [onClickClose](https://github.com/elrumordelaluz/reactour/tree/main/packages/tour#onclickclose-clickprops-clickprops--void) or [onClickMask](https://github.com/elrumordelaluz/reactour/tree/main/packages/tour#onclickmask-clickprops-clickprops--void) which both has `ClickProps` args, including `currentStep`?

**Comment by nemu626** [comment]
@elrumordelaluz  Thank you for reply. 
yeah `ClickProps` has `currentStep`, but It is just index number so It is usefull only page has a single tour.
In my app, page has multiple tour(steps[]) and want to change `onClosed` event by step.
```typescript
const tour1: StepType[] = [ step1, step2, step3,...]
const tour2: StepType[] = [step4, step5, step6,...] 
if (someFlag) {
  tour.setSteps(tour1)
} else {
  tour.setSteps(tour2)
}
```

**Comment by elrumordelaluz** [comment]
Now using `@reactour@3.1.9` you could handle this using [meta](https://github.com/elrumordelaluz/reactour/tree/main/packages/tour#meta-string) and [setMeta](https://github.com/elrumordelaluz/reactour/tree/main/packages/tour#setmeta-dispatchreactsetstateactionstring). Take a look into [the demo](https://github.com/elrumordelaluz/reactour/blob/main/apps/web/pages/index.tsx#L37-L52).

Pleas let me know in any case.

**Comment by nemu626** [comment]
OMG It is Awesome feature. I'll trying it. Thank you.
