### ISSUE TITLE
Document for observe

### ISSUE THREAD

**Issue by kenzouno1** [elrumordelaluz/reactour#53]
Hi.
I have tour with two step.
one button if user onClick will open a modal and forcus to element in modal.
I  saw example have `observe`. i'm try config steps but not working.
```javascript
   <Tour type="abc" isOpen={this.state.showTours}
           onRequestClose={() => this.setState({ showTours: false })}
           steps={[
                 {
                            selector: '.add-widget',
                            'content': 'ahihi',
                        },
                        {
                            selector: '.add-widget',
                            'content': 'ahihi',
                            observe: '.new-widget'
                        },

                    ]} />
```

Can you write an example of this problem?

**Comment by elrumordelaluz** [comment]
Hi @kenzouno1, thanks for the issue.

First of all, you are absolutely right, tha `observe` feature needs a better _documentation_. 

I am thinking in improve the API for this and _docs_ in next versions.

However, consider that you need to `observe` a _parent_ DOM element where the changes will happen during this specific _step_. 
For example, In the demo, the [`selector` of the last step](https://github.com/elrumordelaluz/reactour/blob/5364ade94e9ae5b120a224bee2d3ba92acc5206d/src/demo/Demo.js#L200-L204) and [the changing part](https://github.com/elrumordelaluz/reactour/blob/5364ade94e9ae5b120a224bee2d3ba92acc5206d/src/demo/Demo.js#L206-L251) are both [inside the `observe` selector DOM element](https://github.com/elrumordelaluz/reactour/blob/5364ade94e9ae5b120a224bee2d3ba92acc5206d/src/demo/Demo.js#L130-L133)

Please let me know if it's clear and if works well in your _use case_

**Comment by kenzouno1** [comment]
###Here is my code in project
```javascript
 <div className="observer">
                {
                    this.state.showModalWidget &&
                    <ModalNewWidget
                        show
                        onSave={data => this.handleNewWidget(data)}
                        onClose={() => this.setState({ showModalWidget: false })}
                    />
                }
                <Button className="add-widget" icon="plus" onClick={() => this.setState({ showModalWidget: true })} />
                <Tour isOpen={this.state.showTours}
                    onRequestClose={() => this.setState({ showTours: false })}
                    steps={[
                        {
                            selector: '.add-widget',
                            'content': 'step 1',
                        },
                        {
                            selector: '.new-widget',
                            'content': 'step 2',
                            observe: '.observer'
                        },

                    ]} />
            </div>
```

**Comment by kenzouno1** [comment]
I think need a API 

- callback function on Update Step ` (currentStep,nextStep)=>{ }`
- props disabled nextStep ( In my project nextStep and step 2 only enabled if modal is opened

**Comment by iooops** [comment]
I'm having the same issue here.

**Comment by dcdourado** [comment]
Same for me

**Comment by koiski** [comment]
same
