### ISSUE TITLE
`rx` CSS property doesn't work for Safari

### ISSUE THREAD

**Issue by bachlv** [elrumordelaluz/reactour#533]
Hi,
Firstly, thanks for this awesome package. Very easy to use.
However, I got a problem displaying dots (using Mask) on Safari. This is what your demo looks like on Safari 12.6 (latest version)

<img width="1337" alt="Screenshot 2023-02-06 at 15 25 35" src="https://user-images.githubusercontent.com/6280802/216925065-9946b2a2-24aa-40de-a448-d46ded5a1d2c.png">

This doesn't works for Safari, though works on Chrome and Firefox.
```
highlightedArea: (base, { x, y, width, height }) => ({
    ...base,
    rx: 10,
});
```

My suggestion is allow providing custom property for the `rect` element. Something like:
```
<Mask highlightedAreaRectProps={{ rx: 10 }} />
```

**Comment by elrumordelaluz** [comment]
Should be now solved in `@reactour/mask@1.0.5`
