### ISSUE TITLE
Docs breaking on production?

### ISSUE THREAD

**Issue by RobyCigar** [elrumordelaluz/reactour#537]
hi, I found out that I cant interact with the official website, seems like the website  didnt get the js file correctly
![image](https://user-images.githubusercontent.com/69680330/220228032-7da40bcf-b987-42ab-ad3f-8896d3025f53.png)
![image](https://user-images.githubusercontent.com/69680330/220228090-6bad8c3e-984d-47a8-bfa3-6c32dcebff8d.png)

**Comment by elrumordelaluz** [comment]
Hi @RobyCigar, thanks for open the _Issue_ and to pointing this out.
I just pushed some uncommitted files, which solved this issue. 
![Screenshot 2023-02-21 at 11 02 56](https://user-images.githubusercontent.com/784056/220313391-eda77e90-c17a-4474-985f-303eaa6f4c78.png)

Thank you again.
