### ISSUE TITLE
Using reactour in an application that also uses styled-components destroys styles

### ISSUE THREAD

**Issue by PetrykowskiM** [elrumordelaluz/reactour#54]
### Setup
Create a project that already uses styled-components. Add reactour as a dependency. You will see that it destroys the styles.

### Example
Look at this [CodeSandbox (https://codesandbox.io/s/lpwj1n5697)](https://codesandbox.io/s/lpwj1n5697)

### Suggestions
Styled Components version >=3.2.5  offers a constant `SC_ATTR` that can be set during the build. It allows some kind of namespacing of the styled component. But you currently do not bundle the styled-components library into your bundle. This needs to be changed than.

**Comment by elrumordelaluz** [comment]
hey @PetrykowskiM thanks for the issue.

in the example you provided I see the `button` red and big.

<img width="578" alt="screen shot 2018-07-03 at 15 22 18" src="https://user-images.githubusercontent.com/784056/42222261-ecd64c6c-7ed4-11e8-965a-3b264d14f212.png">

**Comment by PetrykowskiM** [comment]
The interesting, because I actually did not as I created it... Let me check.

**Comment by PetrykowskiM** [comment]
Hey @elrumordelaluz , it seems that the bug only appears on first setup on codebox.

![setup-bug](https://user-images.githubusercontent.com/5831420/42223723-becc1a8c-7ed8-11e8-9a05-f0acda98572a.gif)

I just reproduced it for you in a seperate codebox. However, I have the bug in a project of mine.

**Comment by elrumordelaluz** [comment]
ok, will try in a local repro and get back to you asap

**Comment by PetrykowskiM** [comment]
Sounds good! Thanks.

**Comment by PetrykowskiM** [comment]
@elrumordelaluz I tried it out in a local repo too. I also tried different things like a `ThemeProvider` to get closer to my actual Project Structure. But it worked fine!

After upgrading my project's version of styled-components from `^2.1.2` to `3.3.3` everything worked. So this issue could have been related to the older version.

**Comment by elrumordelaluz** [comment]
awesome!
