### ISSUE TITLE
highlight multiple divs

### ISSUE THREAD

**Issue by lijie602** [elrumordelaluz/reactour#540]
Hi,

First off, thanks for the fantastic package.And I have a question:

Is there any way to highlight multiple divs in one specific step.

Many thanks,
Lee

**Comment by elrumordelaluz** [comment]
Hi @lijie602, thanks for open the _Issue_. Glad you are enjoying the package.

> Is there any way to highlight multiple divs in one specific step.

It is possible. However the Tour will create a mask calculating the compounded bounding box, won't mask each div separatedly.

Please follow one of this threads: https://github.com/elrumordelaluz/reactour/issues/416#issuecomment-1001528235
