### ISSUE TITLE
Only pass childList to MutationObserver Config

### ISSUE THREAD

**Issue by PetrykowskiM** [elrumordelaluz/reactour#55]
# Summary
Within the MutationObserver Handler you only deal with `childList` mutations. You even filter everything else out. See following Ref:

https://github.com/elrumordelaluz/reactour/blob/000bf205a365182ceb01dfc5c45058a63dec3302/src/TourPortal.js#L182-L204

# Solution
I would suggest to set the MutationObserver Config to:
```
{ childList: true }
```

**Comment by elrumordelaluz** [comment]
Closing since `{ childList: true }` is set as proposed.
