### ISSUE TITLE
Padding for each side

### ISSUE THREAD

**Issue by nickcanarelli** [elrumordelaluz/reactour#551]
Is it possible to set the padding for the mask for each side instead of just an x and y? 

I have a mask that is near the end of the page and id like to set the padding on the bottom and either side to different numbers. Is this possible?

looking for: 
```
padding: {
   popover: [0, 8, 0, 16]
}
```

**Comment by elrumordelaluz** [comment]
Should now be available at `@reactour/mask@1.1.0`, `@reactour/popover@1.1.0` and `@reactour/tour@3.4.0`. Thanks for the input!
