### ISSUE TITLE
Can you add arrows to the guide card？

### ISSUE THREAD

**Issue by miaomiao1024** [elrumordelaluz/reactour#559]

**Comment by elrumordelaluz** [comment]
https://codesandbox.io/s/tour-with-data-fetching-forked-ic5es?file=/src/index.js:144-186

**Comment by miaomiao1024** [comment]
> https://codesandbox.io/s/tour-with-data-fetching-forked-ic5es?file=/src/index.js:144-186

I'm sorry, the reactour version number I'm using is 1.18.7

**Comment by qaws5503** [comment]
@elrumordelaluz Great work!! And Thanks for creating this amazing package.
I've post some typescript version of your code.
Since some type you're not exporting them, so I manually create some of them just to let typescript not complaining.

```
import { PopoverStylesObj } from "@reactour/popover";

type VerticalAlign = "top" | "bottom";
type HorizontalAlign = "left" | "right";
type Position = VerticalAlign | HorizontalAlign | "custom";

const styles: PopoverStylesObj = {
  popover: (base, state: any) => {
    return {
      ...base,
      borderRadius: 10,
      ...doArrow(state.position, state.verticalAlign, state.horizontalAlign),
    };
  },
};

const oppositeSide = {
  top: "bottom",
  bottom: "top",
  right: "left",
  left: "right",
};

const popoverPadding = 10;

function doArrow(
  position: Position,
  verticalAlign: VerticalAlign,
  horizontalAlign: HorizontalAlign,
) {
  //  rest of the code...
}

```

**Comment by elrumordelaluz** [comment]
> @elrumordelaluz Great work!! And Thanks for creating this amazing package. I've post some typescript version of your code. Since some type you're not exporting them, so I manually create some of them just to let typescript not complaining.
> 
> ```
> import { PopoverStylesObj } from "@reactour/popover";
> 
> type VerticalAlign = "top" | "bottom";
> type HorizontalAlign = "left" | "right";
> type Position = VerticalAlign | HorizontalAlign | "custom";
> 
> const styles: PopoverStylesObj = {
>   popover: (base, state: any) => {
>     return {
>       ...base,
>       borderRadius: 10,
>       ...doArrow(state.position, state.verticalAlign, state.horizontalAlign),
>     };
>   },
> };
> 
> const oppositeSide = {
>   top: "bottom",
>   bottom: "top",
>   right: "left",
>   left: "right",
> };
> 
> const popoverPadding = 10;
> 
> function doArrow(
>   position: Position,
>   verticalAlign: VerticalAlign,
>   horizontalAlign: HorizontalAlign,
> ) {
>   //  rest of the code...
> }
> ```

Mind creating a PR in case you consider some ts part is missing? thanks!
