### ISSUE TITLE
Only taking initial state value

### ISSUE THREAD

**Issue by HemaRamasamy** [elrumordelaluz/reactour#563]
Hi @elrumordelaluz ,
I'm working in react-tour (TourProvider component). <TourProvider> component props only take the initial value, after I'm updating the state it's not rendering. I have reproduced this issue in Codesandbox
[https://codesandbox.io/s/tourprovider-rendering-issue-forked-4tl43v](url)

Please, help me to find a way, to update the state

**Comment by elrumordelaluz** [comment]
Hi @HemaRamasamy, can you explain a little more on which is the issue on your end or what are you expecting the app to do? Thanks!

**Comment by HemaRamasamy** [comment]
@elrumordelaluz  Thanks for your reply. I'm trying to update the value of defaultOpen when the state value changes. But it's not accepting the updated state value. Taking only the initial state value

**Comment by elrumordelaluz** [comment]
In fact `defaultOpen` is used only for the first state of the _Tour_, to update all the other stuff, use `useTour()` hook inside the _TourProvider_ as shown in the [docs](https://github.com/elrumordelaluz/reactour/tree/main/packages/tour#usage)

**Comment by HemaRamasamy** [comment]
Understood @elrumordelaluz , but only when I give defaultOpen is true, the tour comes, if I'm not giving or defaultOpen as false, it's not showing the react-tour.
You can refer this in this link [https://codesandbox.io/s/tourprovider-rendering-issue-forked-4tl43v](https://github.com/elrumordelaluz/reactour/issues/url)

**Comment by elrumordelaluz** [comment]
Use this structure please: https://codesandbox.io/s/tourprovider-rendering-issue-forked-kvnn3w?file=/src/App.js

**Comment by HemaRamasamy** [comment]
Thanks for your effort to make it work!
But in this example [https://codesandbox.io/s/tourprovider-rendering-issue-forked-enm3in](url) when I used the **setIsOpen** hook in the same component it's not working

**Comment by elrumordelaluz** [comment]
Because the `useTour` hook needs to be inside the tree under the _TourProvider_.

**Comment by HemaRamasamy** [comment]
Thanks for this reply @elrumordelaluz . It's working now.
