### ISSUE TITLE
How to style specific focused/highlighted  element ?

### ISSUE THREAD

**Issue by sohitdeveloper** [elrumordelaluz/reactour#567]
### Discussed in https://github.com/elrumordelaluz/reactour/discussions/566

<div type='discussions-op-text'>

<sup>Originally posted by **sohitdeveloper** May  9, 2023</sup>
hi team, 

I have stucked in achieving one requirement, I want to style specific focused element like want to increase the width, height padding of specific highlighted element.
Is there any way to achieve this ?</div>

**Comment by elrumordelaluz** [comment]
following [here](https://github.com/elrumordelaluz/reactour/discussions/566)
