### ISSUE TITLE
Tour Popover Not Displaying When Steps Change from Empty Array to Page Steps Array

### ISSUE THREAD

**Issue by itbeginswithi** [elrumordelaluz/reactour#569]
**Description**
I am currently facing an issue with the display of the tour popover in my application. The tour popover should show different steps for each page, and to achieve this, I need to update the steps value based on the current page. However, when the steps value changes from an empty array to an array containing steps for a specific page, the tour popover does not display.

**Configuration**
1. steps object:
```
export const TourSteps: Steps = {
    search: {
        steps: [
            {
                selector: ".test",
                content: "First Test",
            },
            {
                selector: ".testTwo",
                content: "Second test",
            },
        ],
    },
};
```

2. Implement a TourWrapper component that retrieves the current page title using useTutorialContext() and dynamically sets the steps value based on the page title, for example:

```
const TourWrapper = ({ children }: React.PropsWithChildren<{}>) => {
    const { pageTitle } = useTutorialContext();

    const steps = useMemo(() => {
        if (pageTitle !== "") {
            return TourSteps[pageTitle]?.steps;
        }
        return [];
    }, [pageTitle]);

    return (
        <TourProvider
            steps={steps}
        >
            { children }
        </TourProvider>
    );
};

export default TourWrapper;

```

**Additional Information**

- I have verified that the steps array is correctly updated with the appropriate steps for each page.
- The tour popover works correctly when the steps value is initially set to a non-empty array (steps={steps["search"].steps})
- The issue seems to be specifically related to the transition from an empty steps array to a non-empty steps array when the page changes.

Environment:

NextJS version: 12

**Comment by wahur666** [comment]
what was the solution? I have the same issue currently

**Comment by itbeginswithi** [comment]
@wahur666, it's not possible to directly update the TourProvider props. Instead, you can update the steps within a component wrapped with the TourProvider. To achieve this, you can use the setSteps dispatch function that is returned from the useTour hook. Here's an example: `const { setSteps, setCurrentStep } = useTour();`
