### ISSUE TITLE
Replace the next button with renderNextButton func.

### ISSUE THREAD

**Issue by leuction** [elrumordelaluz/reactour#57]
Right now, we can customize the button text with nextButton prop. However, if we want to replace our own button, such as material-ui, we can not put the button into that prop since we are nesting a `<button />` into another `<button />`, It will be much better if we can add a hoc to give the ability to the user so that we can customize everything of the button and the close button.

**Comment by elrumordelaluz** [comment]
hey @leuction you are absolutely right.

Let me make some changes to allow pass that `prop` a `function` to render anything.

**Comment by Setsun** [comment]
This is something I also need for a project I'm working on at my company. We're maintaining an internal fork, but are looking to make a PR for an upstream change as soon as that is ready.

A potential solution is a function as child render to handle rendering the step in all cases when the internal state changes? Example:

```
<Tour
   steps={steps}
   ...
>
{(props) => (
  <Container>
       <CustomDots step={props.stepIndex} />
       <CustomCloseButton onClick={props.onRequestClose} />
        {...}
  </Container>
)}
</Tour>
```

**Comment by elrumordelaluz** [comment]
@Setsun absolutely!

This is what I working on for the next version.

Glad to know you are using for `reactour` for your project. Thanks for the ideas!

**Comment by elrumordelaluz** [comment]
Now (`v1.12.0`) is possible to pass a `CustomHelper` prop, please take a look into the [demo source](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L94-L144) or check the live version at https://reactour.js.org/ (try press `Enter` to switch between default and custom _Helper_).

Closing, but feel free to re-open or open a new _Issue_ in any case.

Thanks again for the input!

**Comment by or-cohen-planck** [comment]
@elrumordelaluz This is very unclear how to do
