### ISSUE TITLE
How can I migrate 'reatour' to '@reactour/tour'

### ISSUE THREAD

**Issue by MarianaZavarunska** [elrumordelaluz/reactour#573]
### Discussed in https://github.com/elrumordelaluz/reactour/discussions/572

<div type='discussions-op-text'>

<sup>Originally posted by **MarianaZavarunska** June 22, 2023</sup>
Hi, I am working on migration 'reatour' to **'@reactour/tour' v 3.4.0** package in my React app with SSR.  React version is **16.13.1.**  

I faced with error` (export 'TourProvider' (imported as 'TourProvider') was not found in '@reactour/tour' (possible exports: default) )`
when I wrapped the main App Component  into` TourProvider` or import `useTour `hook in my functional component.

Could you help me resolve the issue?</div>

**Comment by elrumordelaluz** [comment]
Closing to follow in #572
