### ISSUE TITLE
How to select or wait for content that needs to load - NextJS App Router

### ISSUE THREAD

**Issue by ghost** [elrumordelaluz/reactour#579]
## Description
I'm currently trying to create a tour across multiple routes. The tour is navigating properly. The problem, however, is that once the page is fully loaded the popover doesn't navigate to the selected element/component on the page.

I also want this to work for users with slow internet.

Is there a way to fix this at all?

## What I've tried

I've tried various things
- useEffect with an empty dependency array
- restarting the tour after a period of time etc.
- double checked the selectors are named correctly

Happy to edit this and provide the code for the tour setup etc.

**Comment by GeorgeDMFincher** [comment]
Nvm I made a stupid error, didn't add the data-tour selector to the desktop component 👍
