### ISSUE TITLE
Scroll for elements that are loaded after the tour has started.

### ISSUE THREAD

**Issue by oli7812** [elrumordelaluz/reactour#58]
Hi, 
I'm implementing Reactour on my platform but Im having issues with scrolling to the next step. I'm building a tour that shows the user how to include his/her agenda on the platform. The problem is that as he/she starts the tour and selects the option to add an agenda, a form opens on the page so the user can fill out their information, react tour finds the selectors but doesn't scroll the page. I followed the sandbox implementation and got the tour to work but not the scrolling.

**Comment by oli7812** [comment]
What I did for now is to use an action to trigger an srcollIntoView() on the element being passed to the action. But the problem is that the page itself scrolls but the tooltip and the highlight are using the old positioning of the page and not the current one after the scroll.

**Comment by elrumordelaluz** [comment]
hi @oli7812 thanks for the _issue_.

Should be super useful if you can reproduce a minimal example with a [codesandbox](https://codesandbox.io/s/1ql2n6l9o3?module=%2FApp.js) or similar.

However to understand better the situation: 
- do you have a `step`that points to (or _highlight_) that button or something that allows _selects the option to add an agenda_?
- the _agenda_ is a separate `step`?
- the _agenda_ is present in the DOM before _added_?
- are you looking to implement something like the last `step` of the [demo](https://elrumordelaluz.github.io/reactour/) which uses `observe`?

Looking forward to your answer to understand better what could be the problem.

**Comment by oli7812** [comment]
Hi @elrumordelaluz , 

Thanks for the quick response :)

Heres how I set up the Tour:
I load a list of steps that includes the step by step to add an agenda. The first step highlights the button to add the agenda and I trigger the click on the button using the action on the step, which shows the form using conditional rendering. The next step highlights a field on the form that is not in the viewport, thus the screen would need to be scrolled for it show up to the user. However, the tour finds the target but the screen doesn't scroll. Using the action on the step that points to the field I want to highlight, I triggered a scrollIntoView, but I assume it is too late for that because the tour already has the position of the target. So I scroll the page but not the highlighter or tooltip.

So to answer your questions:

do you have a stepthat points to (or highlight) that button or something that allows selects the option to add an agenda? Yup, thats is the first step.

the agenda is a separate step? Actually the button is a step and the fields of the form are separate steps.

the agenda is present in the DOM before added? We use conditional rendering to show the form for the user to add an agenda.

are you looking to implement something like the last step of the demo which uses observe? No really, I want the behaviour shown when you go form the middle of the screen and scrolls down all the way to the footer :)

Regarding the codesandbox request, its a bit complicated for me to set it up, but I can send you more info if you need it.

Thanks in advance.

**Comment by elrumordelaluz** [comment]
@oli7812 the `update` prop is for those cases. Expects a value that when changes fires a re-render, so let the _Tour_ the opportunity to catch DOM that wasn't present before. 

You have `updateDelay` in case you consider need more time.

Let me know if this could work.

**Comment by elrumordelaluz** [comment]
also, could you share at least the `steps` Object?

**Comment by oli7812** [comment]
Sure @elrumordelaluz , here are the steps:
```
export const reactourPsicosConfig = {
    'mySchedules':[{
        selector: '',
        content: () => (<div><h3>Bem vindo à Vittude</h3><p>O tour a seguir, irá mostar a localização das funcionalidades na plataforma, assim como os primeiros passos necessários para que o seu perfil seja disponibilizado para o público. Vamos começar?</p></div>),
        position: 'right',

      },
      {
        selector: '.add-agenda',
        content: () => (<div><h3>Cadastro do Consultório</h3><p>Para que seu perfil apareça na busca, é necessário o cadastro do seu consultório na Vittude. Para isto, é só continuar seguindo o tour :)</p></div>),
        position: 'right',
        action: (element) => {
          element.click()
        }
      },
      {
        selector: '.type-clinic',
        content: () => (<div><h3>Tipo de Consultório</h3><p>Comece selecionando o tipo de consultório que você deseja cadastrar. Não esqueça de verificar qual tipo de consultório pertence ao seu plano contratado.</p></div>),
        position: 'right',
        // style: { yOverflow:'scoll'},
      },
      {
        selector: '.t-nickname',
        content: () => (<div><h3>Apelido do seu consultório</h3><p>Defina um apelido para o seu consultório. Caso o tipo de consultório escolhido seja o virtual, o apelido não poderá ser editado.</p></div>),
        position: 'right',
        // action: (element) => {
        //   scrollBy({top: 350, left: 0, behavior: 'smooth'})
        // }
      },
      {
        selector: '.t-cep',
        content: () => (<div><h3>CEP do seu consultório</h3><p>Insira o CEP do seu consultório, caso ele seja online o preenchimento dessa seção não é necessário.</p></div>),
        position: 'right',
      },
      {
        selector: '.t-address',
        content: () => (<div><h3>Endereço do seu consultório</h3><p>Complete o endereço do seu consultório, caso ele seja online o preenchimento dessa seção não é necessário.</p></div>),
        position: 'right',
      },
      {
        selector: '.t-price',
        content: () => (<div><h3>Valor da Consulta</h3><p>Comece selecionando o tipo de consultório que você deseja cadastrar. Não esqueça de verificar qual tipo de consultório pertence ao seu plano contratado.</p></div>),
        position: 'left',
      },
      {
        selector: '.t-time',
        content: () => (<div><h3>Valor da Consulta</h3><p>Comece selecionando o tipo de consultório que você deseja cadastrar. Não esqueça de verificar qual tipo de consultório pertence ao seu plano contratado.</p></div>),
        position: 'right',
      },
      {
        selector: '.t-color',
        content: () => (<div><h3>Valor da Consulta</h3><p>Comece selecionando o tipo de consultório que você deseja cadastrar. Não esqueça de verificar qual tipo de consultório pertence ao seu plano contratado.</p></div>),
        position: 'right',
      },
      {
        selector: '.t-save',
        content: () => (<div><h3>Salver Consultório</h3><p>Clique em salvar alterações para confirmar a criação do seu consultório.</p></div>),
        position: 'right',
        // action: (element) => {
        //   scrollBy({top: -900, left: 0, behavior: 'smooth'})
        // }
      },
      {
        selector: '.schedules-list',
        content: () => (<div><h3>Consultórios Cadastrados</h3><p>Depois de criado o consultório, eles aparecerão aqui.</p></div>),
        position: 'top',
      },
      {
        selector: '.button-google',
        content: () => (<div><h3>Sincronização com o Google</h3><p>Você sabia que você pode sincronizar o seu calendário na Vittude com o calendário do Google? É bem simples, basta clicar no botão Conectar com o Google e aceitar as permissões :).</p></div>),
        position: 'top',
      },
      {
        selector: '',
        content: () => (<div><h3>Organizar o seu Consultório</h3><p>Pronto! Agora que seu consultório está criado, clique em Organizar do lado de 'Minhas Agendas' para selecionar os horários que você estará disponível para atendimento nos seus consultórios.</p></div>),
        position: 'top',
      }],
```
The Tour component:
```
                        <Tour 
                            onRequestClose={this.closeTour}
                            showNavigation={false}
                            steps={tourConfig}
                            isOpen={isTourOpen}
                            maskClassName="mask"
                            className="helper"
                            rounded={2}
                            accentColor={'#ff6a58'}
                            inViewThreshold={350}
                            scrollOffset={350}
                            scrollDuration={300}
                            prevButton={<p style={{'marginTop':'12px'}}>Voltar</p>}
                            nextButton={<p style={{'marginTop':'12px', 'margin-left': '113px'}}>Próximo</p>}
                            lastStepNextButton={<p style={{'marginTop':'12px', 'margin-left': '81px'}}> Ok, entendi !</p>}
                            update={this.updateTour}
                            updateDelay={200}
                        />
```

And the functions used are:
```
    closeTour = () => {
        this.setState({ isTourOpen: false, forceUpdate: false });
      };
    
    openTour = () => {
        this.setState({ isTourOpen: true });
    };

    updateTour = () => {
        this.setState({ forceUpdate: true })
    }

    configTour(config){
        this.setState({ tourConfig: reactourPsicosConfig[config] })
    }
```

**Comment by oli7812** [comment]
@elrumordelaluz the thing with the update prop is that I can't re-render the page. Otherwise, it reinitialises the form and hides it again. What I tried to do was to return false from the shouldComponentUpdate when I update the prop, but then the scroll still doesn't work.

**Comment by oli7812** [comment]
I think I figured it out. If I trigger a forced update and inside the function to force update I scroll the page combined with the observe feature, the page scrolls and the tour positions itself correctly. However, I will need to customize the next and previous step functions to figure out when I need to force update so the user can go up/down according to the step he / she is on, because I don't like the idea to always trigger a forced update.

I would like to use the getCurrentStep within these new next and prev functions, do you have an example on how I can use it?

**Comment by oli7812** [comment]
@elrumordelaluz thanks for all the help :) I will try it out and let you know.

**Comment by elrumordelaluz** [comment]
Closing for now. Feel free to re-open in any case.
