### ISSUE TITLE
How to make popover centered under maskArea?

### ISSUE THREAD

**Issue by lyandzao** [elrumordelaluz/reactour#583]
like react-joyride
![image](https://github.com/elrumordelaluz/reactour/assets/33866716/7005d044-2096-4197-a744-fc3932bda812)

**Comment by Danilogomes76** [comment]
To center Popover in Mask use This

`  {
    selector: null,
    content: 'Center Popover',
    position: 'center',
  },`
  
  
  in steps Array

**Comment by elrumordelaluz** [comment]
Hi @lyandzao, thanks for open the _Issue_ and sorry for the late reply.

You have full control of the popover using styles. Doing something like: 

```js
const styles = {
  popover: (base: any, state: any) => {
    return {
      ...base,
      ...calculateArrowAndPosition(state),
    };
  },
};

export default function App() {
  return (
    <TourProvider steps={steps} styles={styles}>
      <Main />
    </TourProvider>
  );
}
```

[Here](https://codesandbox.io/p/sandbox/compassionate-meadow-qkw7hv?file=%2FApp.js%3A6%2C17) is a working example.

> To center Popover in Mask use This
> 
> `
> 
> { selector: null, content: 'Center Popover', position: 'center', },
> 
> `
> 
> in steps Array

@Danilogomes76  this option puts the _Popover_ in the center of the screen
