### ISSUE TITLE
Incorrect type for onClickHighlighted prop

### ISSUE THREAD

**Issue by jpreis** [elrumordelaluz/reactour#587]
In [7855cd5](https://github.com/elrumordelaluz/reactour/commit/7855cd5ac7d25aa2f4ccc04ca9bac3ef4b7d7cfb#diff-b28daaab59dfdc9e801848b4bf17a9e41e11b0014cd125cc3c771870a6c47641R39) the signature of the onClickHighlighted prop of the `TourProvider` was changed from

```onClickHighlighted?: MouseEventHandler<SVGRectElement>``` 
to
 ```
onClickHighlighted?: (
    e: MouseEventHandler<SVGRectElement>,
    clickProps: ClickProps
  ) => void
```
So `e` is incorrectly typed as an `MouseEventHandler` rather than `MouseEvent`.

This breaks calls like `e.stopPropagation()` (see minimal [Codesandbox example](https://codesandbox.io/p/sandbox/reactour-tour-3-6-0-onclickhighlighted-zr5mpm?file=/src/App.tsx:8,35)).

**Comment by elrumordelaluz** [comment]
Thanks @jpreis for the input!
Should be solvet at `@reactour/tour@3.6.1`.
