### ISSUE TITLE
Update styled-components break styles

### ISSUE THREAD

**Issue by elrumordelaluz** [elrumordelaluz/reactour#59]
Updating from `styled-components@3.1.5` into `styled-components@3.3.3` breaks silently all the styles and consequently the _Mask_ and _Overlay_ calculations based on css `transforms`.

@mxstbr any idea looking from what to what version we are trying to switch?

Attaching a gif of the [demo](https://elrumordelaluz.github.io/reactour/) using `v3.3.3`

![sc3 3 3](https://user-images.githubusercontent.com/784056/42700091-01ecf826-86c3-11e8-96b4-cf97907a36b5.gif)

**Comment by henryoliver** [comment]
@elrumordelaluz we are experiencing this issue here as well. I tried to switch between version but couldn't find a solution for this.

If you transition to a new component (route) that was open/load for the first time the issue happens.

Please, let me know if you find any solution to this problem.

Thanks!
Henry

**Comment by elrumordelaluz** [comment]
@henryoliver your problem is using `reactour`?

**Comment by henryoliver** [comment]
Yes, follow the issue:
![issue](https://user-images.githubusercontent.com/870784/42828341-6c728d1e-89b6-11e8-9454-58b506be175b.png)

I think that the problem is that `styled-components` won't apply the full `style` in some `reactour` elements.

**Comment by henryoliver** [comment]
But if you open the component first and then try the tour again, it will work as showed below:

![anago-customer-app-development s3-website-us-west-2 amazonaws com_](https://user-images.githubusercontent.com/870784/42828931-1046eb56-89b7-11e8-9fe7-5a74c5f1f786.png)

**Comment by henryoliver** [comment]
Looks like this style is not been applying to the element below:

```
.jWyfWJ {
    opacity: 0.7;
    width: 100%;
    left: 0px;
    top: 0px;
    height: 100%;
    position: fixed;
    z-index: 99999;
    pointer-events: none;
}
```

`<div class="sc-dnqmqq jWyfWJ"></div>`

Only if you reload and revisit the component.

**Comment by henryoliver** [comment]
@elrumordelaluz I fixed the issue temporarily adding the missing style directly on my `tour.css`:

```
.reactour__mask .jWyfWJ {
    z-index: 100;
    opacity: 0.7;
    width: 100%;
    left: 0px;
    top: 0px;
    height: 100%;
    position: fixed;
    pointer-events: none;
}
```

**Comment by henryoliver** [comment]
@elrumordelaluz sadly it is not working completely, I've tried to downgrade and upgrade the `styled-components` but still, it is missing apply its style into some inner elements.

**Comment by henryoliver** [comment]
@elrumordelaluz the problem was a weird conflicted with the library: `import Typed from 'react-typed';`

**Comment by henryoliver** [comment]
@elrumordelaluz you're right, the issue was the following conflict:
```
├─┬ react-typed@1.0.8
│ └── styled-components@2.4.1
└─┬ reactour@1.8.2
  └── styled-components@3.1.5
```

**Comment by elrumordelaluz** [comment]
Seems that the point is when there are different SC versions from different _libraries_. In the case of the _Demo_, had to update [reshake](https://github.com/elrumordelaluz/reshake/)

**Comment by henryoliver** [comment]
@elrumordelaluz yes, the solution was solved implementing a unique `alias` for both dependencies as below:

```
resolve: {
+   alias: {
+     'styled-components': path.resolve('node_modules', 'styled-components'),
+   }
  }
```

source: https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page
