### ISSUE TITLE
Change navigation arrow svg

### ISSUE THREAD

**Issue by yrsluv** [elrumordelaluz/reactour#590]
Are there any way to change only svg inside navigation button to custom arrow? Not found any types \ props for this

**Comment by elrumordelaluz** [comment]
Hi @yrsluv, thanks for open the _Issue_.

Sure you can change the svg arrow, through the [component](https://github.com/elrumordelaluz/reactour/tree/main/packages/tour#components-popovercomponentstype) prop, doing something like:

```js
function Arrow({ inverted }) {
  return <CustomArrow />
}

const steps = [
  /* ... */
]

export default function App() {
  return (
    <TourProvider steps={steps} components={{ Arrow }}>
      {/* ... */}
    </TourProvider>
  )
}
```

[Here is a working example](https://codesandbox.io/s/reactour-tour-demo-template-forked-gr2yk8?file=/index.js:237-465)
