### ISSUE TITLE
Support Styled Components 6

### ISSUE THREAD

**Issue by jussibility** [elrumordelaluz/reactour#594]
Would be nice if this supported v6 of Styled Components instead of only 4 and 5.

**Comment by elrumordelaluz** [comment]
Hi @jussibility, thanks for open the _Issue_.

What version of the Tour are you using?

**Comment by elrumordelaluz** [comment]
thank you @jussibility, at the moment I am not making changes for major versions from `v1`. However you are super welcome to make a PR in any case.

**Comment by elrumordelaluz** [comment]
Closing but feel free to re-open in case needed.
