### ISSUE TITLE
When Interactive Tour is open the background should be disabled

### ISSUE THREAD

**Issue by Ashwini-Kadam** [elrumordelaluz/reactour#61]
Now, when tour is open the background functionality is clickable. How to disabled it.

**Comment by elrumordelaluz** [comment]
@Ashwini-Kadam did you try the prop `closeWithMask: false`?

**Comment by Ashwini-Kadam** [comment]
@elrumordelaluz where to place this condition, however I have placed it in constructor, and also when we open interactive tour it is not working.

**Comment by elrumordelaluz** [comment]
In the `<Tour />` Component you need to pass this prop, like [here](https://codesandbox.io/s/r1yr1mj56m?module=%2FApp.js)

![reactour](https://user-images.githubusercontent.com/784056/43256814-448980fe-90ce-11e8-998b-f1b5903af850.gif)

**Comment by Ashwini-Kadam** [comment]
@elrumordelaluz  thanks it is working.

**Comment by elrumordelaluz** [comment]
cool
