### ISSUE TITLE
please update react-focus-lock package in reactour v1

### ISSUE THREAD

**Issue by prafull-opensignlabs** [elrumordelaluz/reactour#629]
facing conflict issue with react 18

<img width="535" alt="Screenshot 2024-05-22 100033" src="https://github.com/elrumordelaluz/reactour/assets/93375423/cf2b0a75-5333-47f8-b660-8b4f6e92f456">

**Comment by prafull-opensignlabs** [comment]
I have raised PR #632 
please check

**Comment by elrumordelaluz** [comment]
Merged thank you!
