### ISSUE TITLE
Set disabled state for first/last buttons when contextually unavailable

### ISSUE THREAD

**Issue by klepas** [elrumordelaluz/reactour#63]
Hi there,

Thanks for writing this component! :-)

I have a small accessibility/UX improvement suggestion—

It would be nice to have the left/right arrow next/previous buttons ideally set to `disabled` when either on the first or last steps respectively (viz., where there is nothing to go back to, or nothing to go next to).

Rationale:

- As a user, I should be informed when a button’s actions are currently unavailable.
- As a developer/implementer, it would be nice to be able to target the disabled buttons for further UX/stylistic improvements (eg `cursor: not-allowed` for `button:disabled { … }`).

***

I have a few other accessibility suggestions in mind. I’d be happy to make additional issues and assist in closing them, if you’re interested.

**Comment by elrumordelaluz** [comment]
Hi @klepas, thanks for the _Issue_!

Absolutely agree on the suggestion for the prev/next buttons and super happy to collect (also PR welcome) more accessibility improvements.

The idea for the [next version](https://github.com/elrumordelaluz/reactour/milestone/1) is to have more granular control for the _Helper_ Component and by default offers one with lots of improvements.

Thanks to start sharing and assist with the accessibility part of this project!

**Comment by elrumordelaluz** [comment]
Closing since solved in #64. 

In case, let's open new issues related on _a11y_. thanks again!
