### ISSUE TITLE
mutationobservables doesnt work with other popover in DOM

### ISSUE THREAD

**Issue by ngntrung** [elrumordelaluz/reactour#636]
I tried to use both mutationObservables or observe props to detect when a popover appears or changes in DOM however it doesn't work. Only when I change the viewport size then it works.

[Demo](https://codesandbox.io/p/devbox/priceless-snow-ygctdk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxn71vdr0007356mihedo73z%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxn71vdq0002356m4qf98rff%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxn71vdq0004356mrvqvmdkc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxn71vdr0006356mc1oba6lp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxn71vdq0002356m4qf98rff%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxn71vdq0001356mhhuy7odr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clxn71vdq0002356m4qf98rff%2522%252C%2522activeTabId%2522%253A%2522clxn71vdq0001356mhhuy7odr%2522%257D%252C%2522clxn71vdr0006356mc1oba6lp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxn71vdr0005356mwq85nlbt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxn71vdr0006356mc1oba6lp%2522%252C%2522activeTabId%2522%253A%2522clxn71vdr0005356mwq85nlbt%2522%257D%252C%2522clxn71vdq0004356mrvqvmdkc%2522%253A%257B%2522id%2522%253A%2522clxn71vdq0004356mrvqvmdkc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxn71vdq0003356m4sxn1wr1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxn71vdq0003356m4sxn1wr1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by ngntrung** [comment]
thank you for checking @elrumordelaluz , I managed to render the color picker popup in the same tree. Unfortunately, the issue persists :(

**Comment by elrumordelaluz** [comment]
Same CS demo link?

**Comment by ngntrung** [comment]
thanks for checking @elrumordelaluz . Indeed there is a conflict with `antd` color picker. Looks like at beginning it will append popover to the DOM then change classes. Is it possible to modify the mutationobserver of the library to observe the class change?

**Comment by elrumordelaluz** [comment]
> Is it possible to modify the mutationobserver of the library to observe the class change?

Probably yes, PR welcome!
