### ISSUE TITLE
demo page is broken

### ISSUE THREAD

**Issue by igtm** [elrumordelaluz/reactour#637]
https://elrumordelaluz.github.io/reactour/
i notice the demo page might be broken.
maybe deploy process failed or something?

![image](https://github.com/elrumordelaluz/reactour/assets/6331737/90c9600d-1218-437f-8d60-ec49c09896cc)

**Comment by elrumordelaluz** [comment]
Hi, @igtm thank you for pointing this out. Can you tell me where this url is present to replace with https://www.react.tours/ 

Thank you

**Comment by igtm** [comment]
oh! i went to the wrong url that's why. thank you for telling me right url!
i went to the wrong url from the npm page.
https://www.npmjs.com/package/reactour
![image](https://github.com/elrumordelaluz/reactour/assets/6331737/f83a5256-ffca-4115-b73a-b481967f3d25)
