### ISSUE TITLE
Step 12 in "try it" has wrong text

### ISSUE THREAD

**Issue by wnim** [elrumordelaluz/reactour#643]
![image](https://github.com/user-attachments/assets/74a0d9da-2639-4056-94f9-18371cb35af5)

There's no tool tip at this stage.

I think you meant to say "click 'open modal'"

**Comment by elrumordelaluz** [comment]
You are right! mind making a PR?

**Comment by JeffreyQ** [comment]
Hello, I have a PR. @elrumordelaluz mind reviewing? 
https://github.com/elrumordelaluz/reactour/pull/647

**Comment by elrumordelaluz** [comment]
Thank you @JeffreyQ, closing since #647 was merged.
