### ISSUE TITLE
Regarding action prop in StepType

### ISSUE THREAD

**Issue by sakarozone** [elrumordelaluz/reactour#648]
In my current use case, I have a case from where let's say the tour has three steps:
1 -> in this step, the user is at page A
2 -> in this step, the user comes to page B
3 -> in this step, I again take the user back to page A
So the user will have navigated from page A to page B and i am showing a tour step in both of these pages. If the user comes back to page A, through the tour itself, I want them to perform something else when they are on page A again. So my "action" field differs for all these 3 steps.

But the issue i am facing is that when I come back to page A, the old action of step 1 is also getting triggered along with the new action of step 3.

So what I wanted to clarify if this is an expected behaviour? Meaning, is the action prop in the StepType perpetual or does it run only if the user has reached that particular step?

**Comment by elrumordelaluz** [comment]
Hi @sakarozone, thanks for open the _Issue_.

Mind creating a minimal reproduction in a sandbox in order to allow others to debug faster your use-case and try to find a solution as soon as possible? Thanks!

**Comment by sakarozone** [comment]
Closing this issue. An event listener was being retriggered in my code. It wasnt an issue with reactour!
Thank you for the swift response @elrumordelaluz
