### ISSUE TITLE
Improve button semantics by adding ARIA labels

### ISSUE THREAD

**Issue by klepas** [elrumordelaluz/reactour#65]
Hi again,

Currently the `<button>` navigation elements just hold SVGs.

It would be nice to improve the semantics and accessibility of the buttons by giving each one an `aria-label`.

Technically, this is quite straight-forward to do, with the only complication being localization/internationalization to remain language agnostic. To that end it would probably be nice to expose the ARIA label text via a prop to implementers? :-)

**Comment by elrumordelaluz** [comment]
sure, let's hold this to apply with the new Component structure instead of pass down from the _Tour_ Component.

Did you found another places where it's necessary to improve _a11y_, i.e, the _Helper_ with it's content focused, etc?

Thanks again @klepas

**Comment by gdsrosa** [comment]
This issue can be developed or need more details @elrumordelaluz? 😉

**Comment by nelsonwong1012** [comment]
@gdsrosa I believe https://github.com/elrumordelaluz/reactour/pull/197 should take care of this.
