### ISSUE TITLE
Bug: WebSite (https://www.react.tours/) Giving Error 404: Not_Found

### ISSUE THREAD

**Issue by vinaysanwal** [elrumordelaluz/reactour#653]
Getting Error While Trying to Access website (https://www.react.tours/) 

Error : 404 : Not_found

Screenshot : 

<img width="1728" alt="Screenshot 2024-10-08 at 8 05 01 AM" src="https://github.com/user-attachments/assets/34bcadfb-2c8d-4348-b26e-5eab75707ad2">

**Comment by vinaysanwal** [comment]
please check @elrumordelaluz  let me know if I can help with the issue

**Comment by elrumordelaluz** [comment]
Solved, thank you @vinaysanwal
