### ISSUE TITLE
Should hide previous button for the first step

### ISSUE THREAD

**Issue by leuction** [elrumordelaluz/reactour#67]
The previous button shows up on the first step. we should hide it because there is no "prev step"  for the first step.

**Comment by elrumordelaluz** [comment]
Now (`v1.12.0`) is possible to pass a `CustomHelper` prop, please take a look into the [demo source](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L94-L144) or check the live version at https://reactour.js.org/ (try press `Enter` to switch between default and custom _Helper_).

Closing, but feel free to re-open or open a new _Issue_ in any case.

Thanks again for the input!
