### ISSUE TITLE
can react tour work for routing on different page in continuation

### ISSUE THREAD

**Issue by Ashwini-Kadam** [elrumordelaluz/reactour#68]
want interactive tour in continuation on various pages. can interactive tour work in case of routing in continuation.

**Comment by elrumordelaluz** [comment]
@Ashwini-Kadam yes, you have to put the _Tour_ in a shared place, like _App_ ie and update the `prop` update when change the _route_, in my case I pass the `pathname` from `react-router` into the `update` prop.

Let me know if it's clear and if works in your case.

**Comment by Ashwini-Kadam** [comment]
I want interactive tour to work on clickable components i.e if I click on one component's button it should be change the page i.e another page/component and open tour itself.

**Comment by elrumordelaluz** [comment]
[Here](https://codesandbox.io/s/myry48155p) is an example of what I mean.

![reactour](https://user-images.githubusercontent.com/784056/43824770-304e26ce-9af3-11e8-9cdc-bfbfdfae3dd4.gif)

I created a _Component_ with `withRouter` HoC to listen the `pathname`, then update the `stepas` based on it, and also `update` the _Tour_ when the prop changes.

**Comment by elrumordelaluz** [comment]
@Ashwini-Kadam were you able to make this work for your _use-case_?

**Comment by jsequeira92** [comment]
@elrumordelaluz Hi, I tried using reactour for different page continuation by using Link. However why routing to that page, the step counter does not get reset for that particular page. It resumes from the step where I had triggered the routing. Any ideas how to reset the counter?

**Comment by elrumordelaluz** [comment]
@developdeez did you tried passing `location.pathname` into `update` prop of _Tour_ Component? Also customizable `updateDelay`, just in case. 

However super curious what you mean about `toastify`, will take a look on it.

**Comment by demkovych** [comment]
I wanna show one tour window throw my application (different routes). Is it possible somehow to check nextStep click and then change location? (history.push('/blabla')

**Comment by elrumordelaluz** [comment]
Hi @demkovych,
Did you tried with [action](https://github.com/elrumordelaluz/reactour#steps-shape) prop of the specific `step`?

**Comment by demkovych** [comment]
Hi, @elrumordelaluz ,
I tried everything, found only one workaround:
```
content: () => {
        const nextArrow = document.querySelector('[data-tour-elem="right-arrow"]');
        if (nextArrow) nextArrow.onclick = () => history.push('/about');

        return (
          <div className="tour-content">
            <div className="tour-title">title</div>
            <div className="tour-text">text</div>
          </div>
        );
      }
```

**Comment by demkovych** [comment]
Need some callbacks for every step, which will redefining arrow clicks:
```
onNext: () => {},
onPrev: () => {}
```

**Comment by elrumordelaluz** [comment]
[Here](https://myry48155p.codesandbox.io/) is an example using `action`, where when changes to `step[1]` (the second one) the _Application_ navigates into `/topics`. [code](https://codesandbox.io/s/myry48155p?fontsize=14)

**Comment by LordA98** [comment]
For anyone else struggling with the example sandbox posted above or the rather complex-looking `steps` variable (around line 61), I found it easier to do this:

```
export const UserTour = ({ isTourOpen, closeTour }) => {

  const history = useHistory();
  
  const steps = [
    {
      content: 'Start Tour',
    },
    // You would likely have more steps here for your initial page.
    {
      // The purpose of this step is to change page. 
      // I provide a generic message for the context of the following steps.
      content: 'Part 1: Menu',
      action: () => history.push("/dashboard/menu"),
    },
    {
      // We are then on the correct page to carry on.
      selector: '.add-menu-button',
      content: 'Add Menu'
    }
  ];

  return <Tour steps={steps} isOpen={isTourOpen} onRequestClose={() => closeTour(false)} />;
};
```

Essentially, I use a step just to change page.  The content is a generic message that sums up the page and the following step.  

This way isn't as feature-rich as the sandbox method above but it's simpler to read & manage (in my opinion).

I'm using React with useHistory from react-router-dom.

**Comment by fostimus** [comment]
@elrumordelaluz found this after looking how to make our Tour be functional across multiple routes.

It seems the `update` prop is the crux here, can you explain more about what happens with it? How does passing the pathname trigger an update? How does the tour know to update when different pathnames are passed (e.g. a tour across routes)?

Thanks for everything! 🙏🏼

**Comment by elrumordelaluz** [comment]
@fostimus `update` is just a value that when updated (through [componentWillReceiveProps](https://github.com/elrumordelaluz/reactour/blob/v1/src/Tour.js#L55-L79)) updates the Component.

In case your project and use case allows you, I suggest to give a try to `v2`, where the approach is easier and offering more possibilities I think. Here is an example using React Router: https://codesandbox.io/s/reactour-tour-demo-using-react-router-dom-kujql

**Comment by muchisx** [comment]
@elrumordelaluz Is there anyway to do a continuous cross-page tour?

What I'm looking for is the user being able to click next (go to next page) and previous (should return to the previous step)

in your examples it seems that the when changing location the previous steps get removed from the state
