### ISSUE TITLE
goToStep prop does not work when changing the value on closed tour

### ISSUE THREAD

**Issue by paolostyle** [elrumordelaluz/reactour#74]
Hey,

I'm using your library, but we have a bit non-standard use case in our app. Some tour steps are not available at first, so I'm generating an array with steps dynamically, based on Redux app state. This works totally fine. The problem occurs when the user has e.g. finished the tour (so he's currently on the last step, say, stepId = 10) and the app goes back to the state in which there are only 7 steps. I would expect that something like this would do the trick:

```
componentDidUpdate() {
    if (!this.props.tabIsActive && this.props.currentStep > 6) {
      this.props.setStep(6);
    }
  }

  render() {
    return (
      <Tour
        steps={this.getSteps()}
        isOpen={this.props.isTourOpen}
        onRequestClose={this.props.toggleTour}
        getCurrentStep={this.props.setStep}
        goToStep={this.props.currentStep}
      />
    );
  }
```

but it doesn't work - the tour is still stuck somewhere on that non-existing step and throws this:
```
app:8 Uncaught TypeError: Cannot read property 'style' of undefined
    at ProxyComponent.render (TourPortal.js:451)
    at ProxyComponent.hotComponentRender (react-hot-loader.development.js:620)
    at ProxyComponent.proxiedRender (react-hot-loader.development.js:635)
    at finishClassComponent (react-dom.development.js:13194)
    at updateClassComponent (react-dom.development.js:13156)
    at beginWork (react-dom.development.js:13825)
    at performUnitOfWork (react-dom.development.js:15864)
    at workLoop (react-dom.development.js:15903)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at HTMLUnknownElement.nrWrapper (app:8)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at replayUnitOfWork (react-dom.development.js:15311)
    at renderRoot (react-dom.development.js:15963)
    at performWorkOnRoot (react-dom.development.js:16561)
    at performWork (react-dom.development.js:16483)
    at performSyncWork (react-dom.development.js:16455)
    at interactiveUpdates$1 (react-dom.development.js:16720)
    at interactiveUpdates (react-dom.development.js:2150)
    at dispatchInteractiveEvent (react-dom.development.js:4533)
    at HTMLDocument.nrWrapper (app:8)

The above error occurred in the <TourPortal> component:
    in TourPortal

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

I found an absolutely disgusting workaround, but I wish I wouldn't have to do that:
```
componentDidUpdate() {
    if (!this.props.tabIsActive && this.props.currentStep > 6) {
      this.props.setStep(6); // this is actually not needed anymore
      this.tourRef.portal.state.current = 6; // this is ref from Tour component
    }
  }
```

Please make it work as one would expect if possible. Thanks.

**Comment by elrumordelaluz** [comment]
hey @paolostyle thanks for the _issue_.

Did you tried using the `update` prop?

You could pass a value that triggers an _update_ when changes, in your case could be the step from your store.

In case could help, [here](https://codesandbox.io/s/myry48155p) is an example where `update`s steps based on _Route_.

Let me know if could works for you.

**Comment by paolostyle** [comment]
Sorry for VERY late response, but I just left it as it is since there was no need to change anything with the tour in my app.

I had a moment today to check that and unfortunately your solution didn't work - the step was still stuck on the "old" one from before the change (i.e. was on step 10 => tour is closed => app state changed, so only 7 steps available => `currentStep` changed to 6, `goToStep` and `update` are now also 6 => `current` in the tour state is still on 9 and I get the same error). And by the way, the `update` prop in PropTypes accepts only strings, I think it should be `any` or one of primitives (number/string/bool).

Anyway, I managed to find a workaround:
```
  render() {
    return (
      <Tour
        steps={this.getSteps()}
        isOpen={this.props.isTourOpen}
        onRequestClose={this.props.toggleTour}
        getCurrentStep={this.props.setStep}
        startAt={!this.props.extendedTour && this.props.currentStep >= 6 ? 6 : undefined}
      />
    );
  }
```

`this.props.extendedTour` determines if there are 7 or 11 tour steps.

Since that works for me, I guess you can close this issue, but I feel like this `update` prop is a bit awkward to use, though I don't have any other alternative. Perhaps a static method (like Reactour.forceUpdate()) could be some kind of solution, but that's not very React-y.

**Comment by cherishh** [comment]
I found a hack on this. If you log the Tour component i.e. put it in a ref, you will find that it has a `gotoStep` function.
![image](https://user-images.githubusercontent.com/20265415/91018592-5b1b1700-e622-11ea-9c83-cdc8babd1c9e.png)
You can use this to dynamically change step.

**Comment by sasha1016** [comment]
@cherishh The goToStep doesn't work after the tour is closed
