### ISSUE TITLE
can i go to next step when click mask ??

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [elrumordelaluz/reactour#78]
![image](https://user-images.githubusercontent.com/33291479/46339945-4adca600-c65e-11e8-855f-7445ffac0074.png)
a want to go to next step when i click inside mask, any  props support this issue?

**Comment by nguyenvanphuc2203** [comment]
@elrumordelaluz so i think it's a good behavier, i hope you implement in the feature :D

**Comment by elrumordelaluz** [comment]
@nguyenvanphuc2203  ping you to show you [this idea](https://github.com/elrumordelaluz/reactour/pull/91#issuecomment-445035646) based on the PR made to solve this issue, since you have a specific _use-case_ and could show your POV regarding the mask click behaviour.
