### ISSUE TITLE
Support typescript

### ISSUE THREAD

**Issue by rohmanhm** [elrumordelaluz/reactour#81]
I think it will be nice if you have typescript support.

**Comment by elrumordelaluz** [comment]
yup! should be awesome, In case you want, PRs super welcome in the meanwhile.

**Comment by imravichhetri** [comment]
Working on it.

**Comment by imravichhetri** [comment]
Do you want typescript and js both enabled?

**Comment by imravichhetri** [comment]
Please check PR #82

**Comment by paolostyle** [comment]
FYI typings for this package are now on DefinitelyTyped: https://www.npmjs.com/package/@types/reactour

**Comment by elrumordelaluz** [comment]
awesome @paolostyle thanks! 
so could we close this _issue_?
