### ISSUE TITLE
Error in create react app project

### ISSUE THREAD

**Issue by fchienvuhoang** [elrumordelaluz/reactour#83]
Cannot read property 'getBoundingClientRect' of undefined
<img width="757" alt="screen shot 2018-10-31 at 2 11 44 pm" src="https://user-images.githubusercontent.com/4451749/47771716-f4bf5900-dd16-11e8-8cf1-1c8679e2d8e6.png">

**Comment by elrumordelaluz** [comment]
yes, I have to fix this asap, for now can you please use `styled-components@^3`. 
thanks for report @fchienvuhoang

**Comment by fchienvuhoang** [comment]
It worked, Thanks! @elrumordelaluz

**Comment by elrumordelaluz** [comment]
now you can use `styled-components@4` with `reactour@1.9.1`
