### ISSUE TITLE
Allow custom icon / svg to be passed for close button

### ISSUE THREAD

**Issue by jamieshepherd** [elrumordelaluz/reactour#84]
We use a custom design system library with a unique set of icons, and would like to pass a custom icon for the close button. I can't currently see a way this is possible. It would be great if an SVG could be passed as an optional prop.

**Comment by elrumordelaluz** [comment]
hey @jamieshepherd thanks for the input, that is one of the new things that `reactour` will have in the next major version.

**Comment by elrumordelaluz** [comment]
Now (`v1.12.0`) is possible to pass a `CustomHelper` prop, please take a look into the [demo source](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L94-L144) or check the live version at https://reactour.js.org/ (try press `Enter` to switch between default and custom _Helper_).

Closing, but feel free to re-open or open a new _Issue_ in any case.

Thanks again for the input!

**Comment by pash90** [comment]
Is this going to updated in docs?

**Comment by elrumordelaluz** [comment]
@pash90 your absolutely right. I've try to update in the next days.
