### ISSUE TITLE
Incompatible with styled-components4.x

### ISSUE THREAD

**Issue by wilrho** [elrumordelaluz/reactour#85]
Found that the module has issues with using styled-components4.x, reverted back to version 3.x seems to be working fine. Note that our Project uses Typescript so not sure if this is related as we have not tested this on a non-Typescript project.

**Comment by elrumordelaluz** [comment]
curious what version of `reactour` you are using, since from `v1.9.1`

> From v1.9.1 styled-components it isn't bundled into the package and is required styled-components@^4 and react@^16.3 due to the use of createRef.

from [readme](https://github.com/elrumordelaluz/reactour#install)

**Comment by elrumordelaluz** [comment]
[here](https://codesandbox.io/s/pm3lj5oy27?module=%2Fpackage.json) is a working example using `styled-components@4.x` and `reactour@1.9.1`

**Comment by wilrho** [comment]
Hey there, thanks for the response. Yes were using v1.9.0 of reactour and found that it was failing when we had a v4x of styled-components. We were only able to get it work when we used a v3x of styled-components.

**Comment by elrumordelaluz** [comment]
awseme, two options, update `reactour` into `1.9.1` or downgrade `sc` as you did.

**Comment by designbyadrian** [comment]
Is it possible to remove the dependency to styled components? It's a bummer having to install it in a project just to use one library.
