### ISSUE TITLE
Uncaught Errors on update={this.props.location.pathname}

### ISSUE THREAD

**Issue by mateuswolkmer** [elrumordelaluz/reactour#86]
So some of the tours I'm using go through different pages. For example, I have a registration tour that guide the user on clicking on the "Sign up" button to go to the sign up page, and the tour continues on giving information about what to fill in 'till the "Submit" button.

I've set up the tour **steps** for the different paths and set `update` to `this.props.location.pathname` (`update={this.props.location.pathname}`). The issue I noticed when doing this is when the user is in, let's say, step 5, and then changes page and the steps for that page have less than 5 steps, the `steps` update but the "current step number" doesn't, so it tries to access `steps[current]` and it throws errors like this:
![image](https://user-images.githubusercontent.com/20559356/48133061-b842ae80-e27c-11e8-871a-f015718c154c.png)
There are also other spots in the code that it tries to access `steps[current]` attributes without verifying if it exists. So I think it is something to look at for future versions.

For now, is there a way of reseting the `current` number everytime the `steps` update or something like this?

**Comment by elrumordelaluz** [comment]
Hi @mateuswolkmer, I'm sorry to get back to you now, but just wanted to know if this _Issue_ persisted, if you have a way to reproduce in a [codesandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js) otherwise I'll close to focus on other _Issues_.

Thanks in advance,

**Comment by mateuswolkmer** [comment]
Hey @elrumordelaluz, unfortunately I've changed companies and don't use React, nor Reactour anymore. I've checked on the website I used to work in and the problem seems to persist, but I can't confirm if they updated the library or not.
It happens only when the user go back to a page with less steps than the current one, shouldn't be hard to reproduce if you have some time, but it is ok to close the issue if no one else complains about it.

**Comment by poromaa** [comment]
"reactour": "^1.16.1",
does not work in this version

As mateuswolkmer say, if you reroute to a screen that has a tour with less steps than the tour you came from, it will crash. I does not seem to exist any workaround as far as I can see. Even if I say, force the update to "Math.random()" it still seem to keep the current step at the new screen.

**Comment by kaelhem** [comment]
I'm facing the same issue... My dumb workaround is to use a timeout to force the component to re-render, like this:

```jsx
const MyTour = () => {
  const [steps, setSteps] = useState(/*...*/)
  const [isOpen, setIsOpen] = useState(true)

  const onUpdateSteps = (newSteps) => {
    setIsOpen(false)
    setTimeout(() => {
      setSteps(newSteps)
      setIsOpen(true)
    }, 0)
  }

  return isOpen ? (
    <Tour
      steps={steps}
      isOpen={true}
      ...
    />
  ) : null
}
```
... but it produce a little flashy effect that is not really great.

**Comment by elrumordelaluz** [comment]
@kaelhem could you please put a little reproduction in a sandbox in order to debug easier the app with the behaviour you are looking for? thanks!

**Comment by kaelhem** [comment]
Sure! 
In my case, I want to show several tours with a menu to switch between them.

Here's a codesandbox that reproduces the error
https://codesandbox.io/s/broken-sun-h6q29

And, here's the same with the workaround
https://codesandbox.io/s/sad-oskar-jdxh4

Indeed, the workaround make an undesired "flashy" effect on Chrome (but not on Safari...) 

Hope it helps !

**Comment by elrumordelaluz** [comment]
Hey @kaelhem thank you for creating and sharing a sandbox.

I solved this particular _use case_ with the following approach: since the `step.content` could be a `func` I switched into it the `content` for steps of _first_ and _second_ sections, like this:

```diff
// ...
first: (Step, onLoadTourSection) => [
  {
    selector: "#bt1",
-   content: <Step>the first button</Step>
+   content: props => <Step {...props}>the first button</Step>
  },
  {
    selector: "#bt2",
-    content: <Step>the second button</Step>
+   content: props => <Step {...props}>the second button</Step>
  }
],
// ...
```

Then, use the `prop.goTo` inside the _Step_ Component to go back to `0` when clicking the `button`. something like this:

```diff
- const Step = ({ children }) => (
+ const Step = ({ children, goTo }) => (
  <div>
    {currentSteps !== "main" && (
      <button
        style={{ position: "absolute", left: 5, top: 5 }}
        onClick={() => {
          onLoadTourSection("main");
+          goTo(0);
        }}
      >
        back
      </button>
    )}
    {children}
  </div>
);
```

Since the `main` section has only one `step`, _going to_ the `step` 0 you are sure the _Tour_ will found an element in the Array.

[Here](https://codesandbox.io/s/sharp-saha-s739l?fontsize=14&hidenavigation=1&theme=dark) is the working example.
Please, let me know if this approach makes sense for you.

**Comment by kaelhem** [comment]
@elrumordelaluz Nice! Thanks for that. I didn't think to use the goTo like this. Good catch.
Also, for posterity, I've [updated the sample](https://codesandbox.io/s/sleepy-bash-cucr4) to be able to re-open the 'main' tour (with  the `startAt` parameter set to 0).
Now, I've got an easy way to make a lot of tours for my app :)
