### ISSUE TITLE
Change the width of the tour box

### ISSUE THREAD

**Issue by beeti1sushruth** [elrumordelaluz/reactour#87]
Hey. max-width given in 331px for every tour box, how can i change, is there any prop for that

**Comment by elrumordelaluz** [comment]
hey @beeti1sushruth, thanks for the answer 

You could _style_ the `helper` through `className` prop. ie:

```js
<Tour
  {...}
  maskClassName="my-mask"
  className="my-helper"
/>
```

```css
.my-helper {
  max-width: initial;
}
```

**Comment by beeti1sushruth** [comment]
thanks man! It worked.

**Comment by chrisfoster22** [comment]
@elrumordelaluz I've tried the above code per the documentation and at least the `min-width` doesn't get overridden without an `!important` tag. Is this expected?

**Comment by elrumordelaluz** [comment]
I have the override value without `!important` here
<img width="1141" alt="Screenshot 2021-03-10 at 10 16 30" src="https://user-images.githubusercontent.com/784056/110605829-d04ad580-8189-11eb-81e5-a3512ffa8928.png">
