### ISSUE TITLE
overflow-y added to body not removed - broken scroll

### ISSUE THREAD

**Issue by tmaiaroto** [elrumordelaluz/reactour#88]
Hi! Thanks so much for this wonderful library!

I noticed an `overflow-y` was added to the `<body>` which I imagine prevented scrolling down in the tour? I'm trying to read through the demo code, now that I've found it, but still unsure how to make the tour scroll down.

At any rate, the bigger issue here is that this overflow is added, but not removed when the tour is closed. This then makes my page un-usable. So I need to manually remove the style that was added to the body.

Any insight around this?
Thanks!

**Comment by tmaiaroto** [comment]
Actually, I realized I made a check to render the component. I removed that because there's a prop already on the `Tour` component. That fixed the scroll issue on close. However, it still will not auto scroll down the page if I use a selector off screen.

**Comment by elrumordelaluz** [comment]
hey @tmaiaroto thanks for the _issue_,
you could set those things using `onAfterOpen` and `onBeforeClose` props.

However right now this behaviour is set ad [defaultProps](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L55-L56)

Could you please try passing a noop function (`()=>{}`) to try override both props? 

For the next `patch` version those props will be empty by default so the solution is up to the end-user.

Is already working in the [demo](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L55-L56) in case you want to give an eye.

**Comment by elrumordelaluz** [comment]
Closing since doesn't have any aditional info. Please feel free to re-open or open another _Issue_ in any case.
