### ISSUE TITLE
Improve Observer

### ISSUE THREAD

**Issue by elrumordelaluz** [elrumordelaluz/reactour#9]
At the moment, the [`MutationObserver`](https://github.com/elrumordelaluz/reactour/blob/master/src/TourPortal.js#L128) observes elements that appears in the DOM. Could be useful to observe also `css` changes, like `display`, `opacity` used to show/hide UI elements.

**Comment by PetrykowskiM** [comment]
I would suggest to take advantages from the possibility to listen to attribute changes. That is actually supported by the `MutationObserver`.

Would be great to see what kind of behaviour you suggest for the different kind of mutations.

**Comment by elrumordelaluz** [comment]
hey @PetrykowskiM, absolutely!
In fact when see your other _Issue_ #55 reminds me this one.

A possible change could be add `attrs` changes, but I think still remaining uncovered css changes. Probably inline `style` changes will covered.

**Comment by PetrykowskiM** [comment]
Yeah they would probably be covered. But still, as we are dealing with react here, it would not be that big of a deal to add certain node attribute changes for the tour
