### ISSUE TITLE
Use children component inside main Tour component

### ISSUE THREAD

**Issue by gdsrosa** [elrumordelaluz/reactour#95]
To clarify I want to be able to do this:

`<Tour>
    <Children />
</Tour>`

**Comment by gdsrosa** [comment]
Yes, want it to render the children inside the Portal

**Comment by gdsrosa** [comment]
Yes! Same as in content config

**Comment by elrumordelaluz** [comment]
It's available in `reactour@1.11.2`, [here](https://codesandbox.io/s/zl74plp0y4) a working demo.

Thanks @gdsrosa for the input!
