### ISSUE TITLE
font error

### ISSUE THREAD

**Issue by keesgboog** [elrumordelaluz/reactour#97]
When my app loads the overlay; I get 
`Failed to decode downloaded font: https://fonts.gstatic.com/stats/Lato/normal/400`
Is there a way around this?

**Comment by elrumordelaluz** [comment]
Hi @keesgboog,
I don't think a _Google Font_ download issue is related to the library. 

Could you please share some code to understand better what happens?

**Comment by elrumordelaluz** [comment]
Closing, since I consider and _Issue_ not related to the library. Please feel free to re-open or open a new one in any case.
